### ISSUE TITLE
Using attribute without value

### ISSUE THREAD

**Issue by yunyu** [nuxt/vue-meta#129]
I was wondering if it's possible to use an attribute without a value, e.g.

    <link rel="preload" href="..." type="font/woff2" crossorigin>

I tried defining it as 

    { rel: 'preload', href: '...', as: 'font', type: 'font/woff2', crossorigin: null }

But I end up with `crossorigin="null"` rather than the expected output.

**Comment by aykut-rocks** [comment]
according to the vue-meta documentation:

htmlAttrs: {
        lang: 'en',
        amp: undefined // "amp" has no value
}

**Comment by manniL** [comment]
As @NicoPennec said. Please use the long form for now.
