### ISSUE TITLE
Feature Request: Strip Html from meta content

### ISSUE THREAD

**Issue by keithmancuso** [nuxt/vue-meta#140]
This is hopefully a simple thing that could save someone a lot of hassle. Right now if you accidently pass a string with html into a meta tag it escapes it and passes it through the content. 

I cant think of any reason why you'd want html to pass through to the meta tags so id love to see vue-meta just automatically strip out html? Just a simple regex replace would do the trick I think? html in the description breaks facebooks and twitters linters so should never really be in there!

Just got burned by this so would love to see this build into the system. In the meantime Im solving it like this but seem easy to get burned

```
 {
            'hid': "description",
            'property': 'description',
            'content': this.short_description.replace(/(<([^>]+)>)/ig, "")
 },
```

**Comment by manniL** [comment]
There are valid reasons to do so. For example the `innerHTML` of a script.
