### ISSUE TITLE
is "metaInfo", at a "SubClass" level, supposed to be merged with a "SuperClass" component's "metaInfo"?

### ISSUE THREAD

**Issue by akhoury** [nuxt/vue-meta#172]
Right now the whole `metaInfo` object gets overwritten. 

## Example code:

```javascript
var SuperClass = Vue.extend({
    metaInfo: {
        titleTemplate: '%s - MyCompany'
    }
});

var SubClass = Vue.extend({
    // using this option: https://vuejs.org/v2/api/#extends
    extends: SuperClass, 

    metaInfo: {
        title: 'Home Page'
    }
}); 

var app = new SubClass({
    el: '#app'    
});

console.log( app.$options.metaInfo );
/// { title: "Home Page" }

```
## Live example code:

* example above: https://jsfiddle.net/d9em8msL/
* another example: https://jsfiddle.net/9w84bd39/1/

## Use case

It's nice to have a `Page` superclass component that all the other "pages" (pages, and not all the other "components") extends, this way we can have a `titleTemplate` for all, and each page would just override the `title` property.

Thanks

**Comment by pimlie** [comment]
Isnt this wat mixins are for in Vue? So I'd propose to close this issue as the above pattern just wont be possible in Vue v2 afaik. I'll leave the closing to @manniL if he agrees, he might have a possible solution for this

**Comment by manniL** [comment]
@akhoury This was added but had been removed since because it caused issues (see https://github.com/nuxt/vue-meta/pull/273 and following).
