### ISSUE TITLE
"TypeError: Cannot read property 'title' of undefined" when opening and closing a v-img

### ISSUE THREAD

**Issue by x42y** [nuxt/vue-meta#188]
When clicking on, and closing, an image in a `v-img` tag (https://github.com/crowdbotics/v-img), the I get the following error:
```
Uncaught TypeError: Cannot read property 'title' of undefined
    at getMetaInfo (W:\vue-stuffs\nuxt-test\node_modules\vue-meta\lib\vue-meta.js:479)
    at VueComponent.refresh (W:\vue-stuffs\nuxt-test\node_modules\vue-meta\lib\vue-meta.js:924)
    at W:\vue-stuffs\nuxt-test\node_modules\vue-meta\lib\vue-meta.js:1068
    at W:\vue-stuffs\nuxt-test\node_modules\vue-meta\lib\vue-meta.js:964
```

In `vue-meta.js:479`, it's this code:
```
// backup the title chunk in case user wants access to it
if (info.title) {
    info.titleChunk = info.title;
}
```

`info`, which is `undefined` in the error, is set just above:
```
var info = getComponentOption({
    ...
});
```

I guess `v-img` acts as a component in some respects, but does not provide the necessary data for it to be a "real" component, hence the error?

**Comment by manniL** [comment]
Stale. Please ping/answer here if the issue persists.
