### ISSUE TITLE
base doesn't work (in Nuxt)

### ISSUE THREAD

**Issue by hackuun** [nuxt/vue-meta#193]
Hi. I have in `nuxt.config`

```js
head: {
    base: { target: '_blank', href: '/' }
}
```
But it doesn't render `base` tag.

**Comment by merrylmr** [comment]
@hackuun hello ,Has this problem been solved?

**Comment by pimlie** [comment]
@merrylmr This should be working fine, please create a new issue with a minimal reproduction if you experience a similar issue still
