### ISSUE TITLE
When I use prerender-spa-plugin, packaged files, vue-meta does not take effect

### ISSUE THREAD

**Issue by chavesgu** [nuxt/vue-meta#195]
When I use prerender-spa-plugin, packaged files, vue-meta does not take effect

**Comment by kingsloi** [comment]
Hey @guchunwen, were you able to fix this? I am also running into this issue

Vue-meta works fine but (<title>, <meta> tags are applied) but once `?_escaped_fragment_=1` is applied, they load for a brief second, and then are removed (leaving blank <title>)

**Comment by manniL** [comment]
Stale. Please ping/answer here if the issue persists.
