### ISSUE TITLE
Access current route's metaInfo

### ISSUE THREAD

**Issue by chasebank** [nuxt/vue-meta#197]
I'm trying to find some way to get a route's metaInfo title on route change.

Something like...
```
watch: {
    '$route' (to, from) {
      // console.log(this.$root.$options.components.App.metaInfo)

      console.log(this.$metaInfo)
  }
}
```

Or maybe inside `router.beforeResolve()`

Is there any way to access it?

**Comment by tfoxy** [comment]
You can use the function form of `metaInfo`:

https://github.com/declandewet/vue-meta#how-do-i-populate-metainfo-from-the-result-of-an-asynchronous-action

**Comment by lighth7015** [comment]
That doesn't exactly work. I'm trying to do something similar, I need the meta info, so I can customize the HTML shell of my Vue application.

**Comment by mfullbrook** [comment]
So I have found a solution... Vue-meta emits an "event" with the new info https://github.com/declandewet/vue-meta/blob/2cfb8c3531ce593e388fa5e99eb7a4379c72c8f8/src/client/updateClientMetaInfo.js#L55 therefore in your root component you can add a `changed` property to the `metaInfo` object.  e.g.

```js
export default {
  name: 'App',
  metaInfo: {
    titleTemplate: '%s | MyApp',
    changed: (newInfo) => {
      console.log(newInfo)
    }
  }
}
```

**Comment by mfullbrook** [comment]
Well if i had just RTFM... https://github.com/declandewet/vue-meta#changed-function
