### ISSUE TITLE
Add memoization to `inject()`

### ISSUE THREAD

**Issue by utatti** [nuxt/vue-meta#198]
To use vue-meta in SSR and Vue SSR template, it's recommended doing the following, according to README.md.

```html
<head>
  {{{ meta.inject().title.text() }}}
  {{{ meta.inject().meta.text() }}}
</head>
```

However, by a quick look in the implementation of [`inject()`](https://github.com/declandewet/vue-meta/blob/master/src/server/inject.js), it seems like not caching the result. It means it'll generate the meta object every time it's referenced in a template. The texts won't be changed after `inject()`, so I think we can memoize the result of `inject()` call for each meta object.

**Comment by manniL** [comment]
Sounds like a great idea! It sounds like you know more about memoization, so why not PR it? :relaxed: @utatti

**Comment by pimlie** [comment]
Isnt it possible for a ssr page to contain user state when eg the url has query parameters which are 'ignored' by the router but are used in e.g. nuxt's asyncData? Cause that would make this caching much more difficult I guess?

**Comment by manniL** [comment]
@pimlie That's correct, yeah. We probably can't find out all "dependencies" for the vue meta attributes easily.

**Comment by manniL** [comment]
I'd close here as it's not "that easy" 🙈
