### ISSUE TITLE
使用vue-ssr构建的项目，title和meta标签未在源码里更新

### ISSUE THREAD

**Issue by dandan888111** [nuxt/vue-meta#199]

**Comment by aiyou666666** [comment]
me too

**Comment by heyikang** [comment]
me too

**Comment by calamus0427** [comment]
me too

**Comment by clarkdo** [comment]
@dandan888111 Could you provide a reproducible repo and more detailed description ?

**Comment by pimlie** [comment]
Based on google translate I would say this is a possible duplicate of #224?
