### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by declandewet** [nuxt/vue-meta#2]
- [x] basic usage
- [x] basic render function usage
- [ ] using component data as data source
- [ ] using component props as data source
- [x] usage with `vue-router`
- [x] usage with `vuex`
- [x] async usage with `vuex`
- [ ] overriding parent `metaInfo`
- [ ] sibling `metaInfo` (not sure how this behaves atm)
- [ ] SSR with `renderToString`
- [ ] SSR with `renderToStream`
- [ ] disabling sanitization
- [x] documentation on running examples

**Comment by manniL** [comment]
Stale as we have tests in the https://github.com/nuxt/vue-meta/tree/next branch.

If specific examples are still wanted, please raise another issue.
