### ISSUE TITLE
Delayed update causes errors

### ISSUE THREAD

**Issue by ChambreNoire** [nuxt/vue-meta#200]
Hello,

I have created a DateField component which uses bootstrap-datepicker. I load it in my component's mounted() hook thus :

    mounted() {
      $('#my-input').datepicker({ format: "dd/mm/yyyy" });
    }

I also use vue-meta to load in the appropriate .js file thus :

    metaInfo() {
      return {
        script: [
          { type: 'text/javascript', src: '/static/js/bootstrap-datepicker.js' },
        ],
        link: [
          { rel: 'stylesheet', href: '/static/css/common/bootstrap-datepicker3.css' },
        ],
      };
    },

However I've noticed that I get the following error message. It seems that mounted() is called before the vue-meta update. I tried putting the init code in metaInfo's changed(). Same problem. 

    vue.esm.js?efeb:1733 TypeError: $(...).datepicker is not a function

I tried putting the metaInfo() in the parent component of my DateField component which helps a bit but if I refresh the page and the component is immediately visible the same thing happens...

Any ideas?

Thanks

**Comment by manniL** [comment]
Stale. Please ping/answer here if the issue persists.
