### ISSUE TITLE
Ability to reset meta content to parent's value

### ISSUE THREAD

**Issue by peronczyk** [nuxt/vue-meta#204]
Is there any way to be able of resetting meta content value within nested component? For example I have "parent" component with this code:
```
export default {
  metaInfo() {
    return {
      title: 'Some default title'
    }
  },
  ...
}
```

and "child" component:
```
export default {
  metaInfo() {
    return {
      title: this.pageTitle
    }
  },
  computed: {
    pageTitle() {
      return <some async result>
    }
  }
  ...
}
```

I don't know what will be the result of async action so I would like to return for example 'false' to pageTitle in order to tell vue-meta to skip <title> change in "child" component and use title from parent component.

Is there any way to do this?

**Comment by pimlie** [comment]
This issue has been closed as changes for it are included in the [v2 release candidate](https://github.com/nuxt/vue-meta/releases/tag/v2.0.0-rc.0). Please help us testing the release candidate and report any follow-ups in a new issue
