### ISSUE TITLE
Using with beforeRouteEnter

### ISSUE THREAD

**Issue by hansy** [nuxt/vue-meta#213]
What's the proper way of populating my meta info from data I asynchronously set in my `beforeRouteEnter` [navigation guard](https://router.vuejs.org/en/advanced/navigation-guards.html)? While I think the async instructions generally work (by using `metaInfo()`), I encounter undefined errors on initial page load. Ideally, I'd like the meta information to only be set after the async request.

Example component:

```
// Example.vue

<template>
  <p>Example Component</p>
</template>

<script>
export default {
  data() {
    return {
      name: undefined,
    };
  },
  beforeRouteEnter(to, from, next) {
    AsyncRequest(URL)
      .then((response) => {
        next((vm) => {
          vm.name = response.name;
        });
      });
  },
  metaInfo() {
    return {
      title: this.name,
    };
  },
};
</script>
```

**Comment by Atinux** [comment]
Could you try so set `name` to an empty string instead of `undefined`, I think this will solve your issue.

**Comment by hansy** [comment]
That can work; but what about for less trivial examples where I'm setting an object and then would be accessing the object's properties?

**Comment by manniL** [comment]
Stale. Please ping/answer here if the issue persists.
