### ISSUE TITLE
Use a custom keyName dynamically

### ISSUE THREAD

**Issue by KaelWD** [nuxt/vue-meta#215]
In vuetify we use vue-meta if `this.$meta` exists, but I had to hard-code `metaInfo` and `head` (for nuxt). Is there a way for my library to dynamically use whatever keyName the end user passed in?

- https://github.com/vuetifyjs/vuetify/blob/d724779defded93f887afb257869063fc22d0b43/src/components/VApp/mixins/app-theme.js#L61-L83
- vuetifyjs/vuetify#3314
- vuetifyjs/vuetify#3488

**Comment by Atinux** [comment]
Hi @KaelWD 

What if you could get it trought `this.$meta().options.keyName`?

I believe we should add it here: https://github.com/declandewet/vue-meta/blob/master/src/shared/%24meta.js#L14

**Comment by KaelWD** [comment]
Yeah that should be good. Do you know how I could use that though? I had [this](https://github.com/vuetifyjs/vuetify/commit/b2a7a02d7f366111ec578a2025a2c4acafb844ca#diff-b4befa9d618deb303d9def8da0583bbeL54) before which worked fine in SSR, but I think caused a race condition on the client-side because it would sometimes not apply.

**Comment by miniplus** [comment]
Just ran into this issue with vuetify having the hardcoded value and my project using a different keyName. Took me quite some time to debug.

As this issue is half a year old, has this been considered? Just looking for an update @Atinux.

Thanks! :)

**Comment by pimlie** [comment]
vue-meta v2 will have a getOptions method so you can call `this.$meta().getOptions().keyName`

**Comment by theprojectsomething** [comment]
@pimlie `this.$meta().getOptions()` is currently listed in the 1.6 API docs: https://vue-meta.nuxtjs.org/api/#meta-getoptions

**Comment by pimlie** [comment]
This issue has been closed as changes for it are included in the [v2 release candidate](https://github.com/nuxt/vue-meta/releases/tag/v2.0.0-rc.0). Please help us testing the release candidate and report any follow-ups in a new issue
