### ISSUE TITLE
__dangerouslyDisableSanitizers not working?

### ISSUE THREAD

**Issue by kont-wayfinder** [nuxt/vue-meta#216]
Hi,

I have an escaped string title like this - if you don& #8217; t (don't)

I have tried the option:
__dangerouslyDisableSanitizers: ['title']

But it doesn't work. In my vue file i used v-html to render the title. How do i render it in vue-meta info?

**Comment by manniL** [comment]
Stale. Please ping/answer here if the issue persists.
