### ISSUE TITLE
cannot read property length of undefined

### ISSUE THREAD

**Issue by funkysoul** [nuxt/vue-meta#227]
While using metainfo in function form I'm getting this error: 

Uncaught TypeError: Cannot read property 'length' of undefined
    at updateTags (vue-meta.js?a778:797)
    at eval (vue-meta.js?a778:908)
    at Array.forEach (<anonymous>)
    at VueComponent.updateClientMetaInfo (vue-meta.js?a778:882)
    at VueComponent.refresh (vue-meta.js?a778:944)
    at eval (vue-meta.js?a778:1091)
    at eval (vue-meta.js?a778:983)

Not exactly sure why, but i think it has something to do with using vue-meta as a function.

`metaInfo() {
    return {
      title: this.json.meta_title,
      description: this.json.meta_description,
      titleTemplate: '%s · xyz',
      meta: [
        { vmid: 'og:title', property: 'og:title', content: this.json.meta_title },
        { vmid: 'description', name: 'description', content: this.json.meta_description },
      ],
    };
  },`

Changing Line 811 in /lib/vue-meta-js to check if tags are available before continuing solves the issue. 

I'm not sure if I'm using it wrong.. what do you think?

**Comment by manniL** [comment]
Stale. Please ping/answer here if the issue persists.
