### ISSUE TITLE
Allow bodyAttrs keys to have values as array or object.

### ISSUE THREAD

**Issue by moltar** [nuxt/vue-meta#231]
# Problem:

Setting `bodyAttrs.class` in a component, and then a layout (Nuxt) will not merge them properly, as both values are strings. The component seems to always win.

# Solution:

Allow `bodyAttrs` keys to have values as array or object.

This would allow `deepmerge` module to merge the values correctly.

Then a rendered version would just concat with a space or something like that.

E.g.:

```js
    bodyAttrs: {
      class: ['foo', 'bar']
    }
```

OR

```js
    bodyAttrs: {
      class: { foo: true, bar: true }
    }
```

**Comment by pimlie** [comment]
This issue has been closed as changes for it are included in the [v2 release candidate](https://github.com/nuxt/vue-meta/releases/tag/v2.0.0-rc.0). Please help us testing the release candidate and report any follow-ups in a new issue
