### ISSUE TITLE
$meta is not defined in Vue interface type.

### ISSUE THREAD

**Issue by nicolasigot** [nuxt/vue-meta#242]
Hello,

While using vue-meta with SSR and typescript, I have issue as we need to expose meta server side using:

app.$meta();

Using typescript I have
const meta = app.$meta();
[ts] Property '$meta' does not exist on type 'Vue'.

What I need to do then as workaround is:
const meta = (app as any).$meta();

Can you please update types definitions?

**Comment by manniL** [comment]
Feel free to submit a PR.
