### ISSUE TITLE
Styles in body

### ISSUE THREAD

**Issue by Mattchewone** [nuxt/vue-meta#244]
I am using `Nuxtjs` and I have within a layout a `head()` which I am defining some Vue meta information to customise the head.

I am defining some styles but I wish for the styles to come in after the compiled styles are added, so I am adding a `body: true` to the styles so that they are added after any initial main styles in the head. This does not seem to work though, if I add the attribute and HMR reloads the app it works, but if I do an actual reload then nothing is added, not even to the head.

Is this a bug or am I doing something wrong?

**Comment by pimlie** [comment]
Please add a reproduction if this is still an issue, when I test this with
```js
    style: [
      { body: true, innerHTML: 'body { background: cyan }' }
    ],
```
there is a style tag added at the end of the body and my body has a blue background

**Comment by manniL** [comment]
Closing this as stale. If there are still problems, please ping us here :relaxed:
