### ISSUE TITLE
meta templates does not work correctly

### ISSUE THREAD

**Issue by sqal** [nuxt/vue-meta#257]
### Version
1.5.3

### Reproduction link
[https://github.com/sqal/vue-meta-bug-reproduction](https://github.com/sqal/vue-meta-bug-reproduction)

### Steps to reproduce
- Clone repo -> `npm install && npm run serve`
- Open devtools and watch how meta tag `og:title` is rendered while you switch back and forth between two pages, `home` and `about`.

### What is expected?
Meta tag `og:title` should always have the correct `content` attribute `Homepage - My page` for home route and `About - My page` for about route.

### What is actually happening?
Everytime you switch to another page, vue-meta appends tags' template to the previous template and in result it sets incorrect attribute:

Homepage - My page
About - My page - My page
Homepage - My page - My page - My page

...and so on

And one more thing I noticed. If you add console.log inside template function in App.vue, like this

```js
template: chunk => {
  console.log(chunk) 
  return `${chunk} - My page`
}
```

you can see that it is called twice after changing the route. But I am not sure whether this is related to this issue.  Thanks for looking into this issue :)

**Comment by manniL** [comment]
Fixed with #248
