### ISSUE TITLE
Scripts being over ridden by consecutive components

### ISSUE THREAD

**Issue by devanflaherty** [nuxt/vue-meta#272]
I'm wanting to utilize vue-meta in a component that outputs content from a wysiwyg. This wysiwyg content can have embed scripts and vue's template renderer doesn't render script tags.

What I've done in the past is to just find the scripts, and append them to the head.

But I'd like to utilize Vue-Meta as I feel it's a better pattern to follow.

**The problem:**
Because there can be multiple wysiwyg blocks output on one page the script tag seems to be overridden. I'd like for each script in vue-meta to be appended to one another rather than replaced.

Is there a way to do this?

**Code Example**:
```js
metaInfo () {
    return {
      script: this.foundScripts ? this.foundScripts : null
    }
},
computed: {
    foundScripts () {
      let doc = document.implementation.createHTMLDocument()
      doc.body.innerHTML = this.wysiwygContent

      return [].map.call(doc.getElementsByTagName('script'), (el) => {
        return {
          src: el.src ? el.src : null,
          type: el.type ? el.type : null,
          async: el.async ? el.async : null
        }
      })
    }
}
```

**I'd like to do something something like this at the very least**:
```js
metaInfo () {
    return {
      script: this.foundScripts ? [...this.metaScripts, ...this.foundScripts] : this.metaScripts
    }
},
```

Can a component access `vue-metas` current scripts via variable?

Any help would be great!

**Comment by pimlie** [comment]
You might have found a workaround already in the mean time, but vue-meta already merges all metaInfo objects from all components on a page. So it seems what you want should already work as far as I can deduct from your code example
