### ISSUE TITLE
vmid doesn't overwrite parent's tag, but creates a new tag with data-vmid

### ISSUE THREAD

**Issue by VincentMRA** [nuxt/vue-meta#277]
Hi guys!

I'm not using any SSR.

Simple VUE 3 framework.

when using vmid on one of the children's components, it creates new tag instead of replacing the parents.

Parent tag:
```
meta:[
     {property:'description', content:'parent description'}
]
```
child tag:
```
meta:[
     {vmid:'description' ,property:'description', content:'child description'}
]
```

Expected result: 
`<meta name="description" content="child description>`

actual result:
`<meta name="description" content="parent description" data-vue-meta="true">`
`<meta data-vmid="description" name="description" content="child result" data-vue-meta="true">`

Any idea how to solve this issue?

**Comment by james-brndwgn** [comment]
You need to have `vmid:'description'` on the parent meta as well.

Parent
```
meta:[
     { vmid:'description', property:'description', content:'parent description' }
]
```

Child
```
meta:[
     { vmid:'description', property:'description', content:'child description' }
]
```
