### ISSUE TITLE
Title Tags do not load when pages are opened on new tabs

### ISSUE THREAD

**Issue by lanbau** [nuxt/vue-meta#283]
Title Tags do not load when pages are opened on new tabs

**Comment by manniL** [comment]
Please create a reproduction (eg. GitHub repo, CodeSandbox, ...)

**Comment by manniL** [comment]
Stale

**Comment by pimlie** [comment]
@manniL This is a confirmed issue, will include a fix in the next branch

**Comment by manniL** [comment]
@pimlie updated

**Comment by Timibadass** [comment]
Hi @manniL , how do I get my app to reflect this update?

**Comment by manniL** [comment]
@Timibadass It'll take a bit until the next release will be published, but you can try out the `next` branch in the meantime.

**Comment by pimlie** [comment]
This issue has been closed as changes for it are included in the [v2 release candidate](https://github.com/nuxt/vue-meta/releases/tag/v2.0.0-rc.0). Please help us testing the release candidate and report any follow-ups in a new issue
