### ISSUE TITLE
Getting the title metaInfo from another component?

### ISSUE THREAD

**Issue by idaviddesmet** [nuxt/vue-meta#285]
I've got a subheader component that currently renders a title and a breadcrumb from the $route.meta object and I would like to know if there's a way to obtain the metaInfo into this component in order to be able to use the title defined in the view components.

This is the code I'm using to get the title using the route path:

```javascript
this.$route.meta.title
```

Thanks in advance!

**Comment by MatthewBooth** [comment]
Agreed. I've got a "Jumbotron" that I want to pick up the title and description from the metaInfo.

**Comment by pimlie** [comment]
You could manually call the refresh method `this.$root.$meta().refresh()` which returns the metaInfo object

@manniL Do you think we should add a method which returns the last metaInfo?

**Comment by manniL** [comment]
@pimlie Well, I'd say that depends on the overhead of refresh. If it's a "costly" method to call, then we could think about adding a "fast" one.

**Comment by pimlie** [comment]
With the changes in the next branch its less costly then it was before ;)

So lets leave this be until there are complaints about the performance

Please note that the return signature of `refresh` will change in vue-meta 2.0
