### ISSUE TITLE
Title not working from prop info

### ISSUE THREAD

**Issue by shiibbyy** [nuxt/vue-meta#292]
Hey there!

So, I am currently running into an issue when using live-data.
I have set it up to work if I input strings of static data, but when trying to pull data from an array (already used to define the page text on screen) it won't.

For example, I have an array of "Resources" in which an object "Title" is in there.
To refer to it in the template, I use {{ resource.resourceTitle }} and it displays.

But doing the same thing in Meta Info shows nothing at all (just blank when loaded). I cannot seem to find a work around?

**Comment by manniL** [comment]
Need reproduction.
