### ISSUE TITLE
Declare $metaInfo into a component on runtime

### ISSUE THREAD

**Issue by DidoMarchet** [nuxt/vue-meta#299]
Hi,
I'm trying to make an util based on your plugin.
I've create a plugin that automates the creation of canonical, hreflang if locales are detected and meta tags through data gived from one endpoint.

Basically I watch the $route, I check if the component is a view of the router and I do some logics.
If the component is not a route view I return false and the plugin "is not attached"  on the component.

```
      watch: {
        '$route': {
          immediate: true,
          handler (to) {
            // this.$router.getMatchedComponents() get the list of matched components
            if (!_isRouteComponent(this.$router, this.$options.name)) return false
            metaInfoData = Object.assign(metaInfoData, {
              link: this.$_getLinks(to), // Get Links
              title: this.$_getTitle(), // Get Title
              meta: this.$_getMeta() // Get Meta
            })
            // Refresh metaInfo
            this.$meta().refresh()
          }
        }
      }
```

When I want to render the tag I've got the metaInfo function. 

```
    metaInfo () {
        // Create Meta
        return metaInfoData
      }
    })
```
My issue is about `$metaInfo` computed, because It's attached into all components.
It's possibile to declare `$metaInfo` only into a component on runtime? 
For example after kind of filter that I use above?

My goal is use your plugin without touch any component but only giving a single endpoint.

Here my code (is quite clean because it's in draft)
[https://github.com/DidoMarchet/vue-seo-boilerplate/blob/dev/src/plugin/vueSeoMetaBoilerplate/index.js](https://github.com/DidoMarchet/vue-seo-boilerplate/blob/dev/src/plugin/vueSeoMetaBoilerplate/index.js)
Plugin starts from row 82

I hope you understand,

thanks and regards,

**Comment by DidoMarchet** [comment]
Hi,
after a check I've see my needed is get this function public `_refresh`.
It's possible?

thanks and regards,

Davide

**Comment by pimlie** [comment]
This has been (mostly) fixed in the next branch, we still set a global mixin for all components on the page but now only inject `$meta` when the component has metaInfo defined.

**Comment by DidoMarchet** [comment]
Great! Have a nice day!
