### ISSUE TITLE
Does not only support v8js engines?

### ISSUE THREAD

**Issue by cherryred5959** [nuxt/vue-meta#302]
I would like to perform meta tag operations on server side rendering in v8js using your package.

I first started following your SSR guide.
However, there was a problem with the following sources: [batchUpdate] https://github.com/declandewet/vue-meta/blob/master/src/client/batchUpdate.js)

The problem occurred with an undefined timer-related function.
clearTimeout and setTImeout are only provided in the web API and nodejs.

Is there a solution to this problem?

**Comment by manniL** [comment]
Never used `v8js`. Feel free to send in a PR!

**Comment by pimlie** [comment]
During SSR the timeout functions shouldnt be called as they are client side only, this might have been a packaging issue because there was only an umd build which always included batchUpdate even though batchUpdate would never be called on SSR.

Starting with vue-meta 2.0 this should be more separated, so please try again once v2.0 has been released

**Comment by cherryred5959** [comment]
Oh, I don't know why I closed this issue....  

I haven't found a decent solution yet.

**Comment by manniL** [comment]
Have you tried it with vue-meta v2?

**Comment by pimlie** [comment]
There is still a timeout being used to try to batch/debounce fast occuring updates: https://github.com/nuxt/vue-meta/blob/master/src/client/update.js

I am looking into another way of doing the updates (current solution is not really optimal performance wise), but can take a while for that to materialize

**Comment by pimlie** [comment]
vue-meta v2.3 introduces a [`debounceWait`](https://vue-meta.nuxtjs.org/api/#debouncewait) property. If you set this to `0`, then there wont be any timeout called and the meta info update is run immediately

**Comment by cherryred5959** [comment]
@pimlie Thanks, It's awesome!! [This works very well](https://github.com/cherryred5959/laravel-v8-vue-meta).
