### ISSUE TITLE
JSON LD as `script` example in  `README.md` seems misleading

### ISSUE THREAD

**Issue by williamchong007** [nuxt/vue-meta#303]
Currently the `script` example in `README.md`  look like this
> Each item in the array maps to a newly-created `<script>` element, where object properties map to attributes.
> ```js
> {
>   metaInfo: {
>     script: [
>       { innerHTML: '{ "@context": "http://schema.org" }', type: 'application/ld+json' }
>     ],
>   }
> }
> ```
> ```html
> <script type="application/ld+json">{ "@context": "http://schema.org" }</script>
> ```

This code would not work, as `__dangerouslyDisableSanitizers` is required for json-ld, but not shown in the example.

However for a simple`script` example, putting `__dangerouslyDisableSanitizers` in seems too much complication, and might promote poor pratice of adding unneeded `__dangerouslyDisableSanitizers`. People might just take a quick glance at README for copy and paste, without really understanding what each line does.

Will we consider changing the `script` example to something more trivial, and put json ld as `__dangerouslyDisableSanitizers` example instead?

**Comment by manniL** [comment]
Feel free to send in a PR ☺️
