### ISSUE TITLE
Allow shorthand for HTML tag attributes

### ISSUE THREAD

**Issue by manniL** [nuxt/vue-meta#311]
```js
export default {
  htmlAttrs: {
    lang: 'en',
    amp: true
  }
}
```

Should render `<html lang="en" amp></html>`

**Comment by pimlie** [comment]
I guess this is the same as boolean attributes? Or do you mean something else with shorthand?

**Comment by manniL** [comment]
@pimlie Exactly! But I think that this example doesn't work properly at the moment.

**Comment by pimlie** [comment]
It should be as easy as adding `amp` to here: https://github.com/nuxt/vue-meta/blob/next/src/shared/constants.js#L56

Do you know of more missing attributes?

**Comment by manniL** [comment]
@pimlie Exactly. Not so far, no :thinking: Maybe we could give the users an option to force a certain behavior for these values? :thinking:

**Comment by pimlie** [comment]
Hmm, I am not in favor of making everything configurable. Especially in this case where html attributes should adhere to a standard. Whats useful for one user should be useful for others as well. I prefer that we force the users to make a pr so other users can benefit from the missing attribute as well

**Comment by manniL** [comment]
fair enough :relaxed:
