### ISSUE TITLE
Meta tags from pages not showing up

### ISSUE THREAD

**Issue by X1machinemaker1X** [nuxt/vue-meta#316]
When I use `yarn generate` aka `nuxt generate` to get the html files, the title I set in any of the pages doesn't appear. the template set in nuxt.config.js is there, but the title is not. nor are any of the other head tags set in pages.

[example page](https://github.com/PanyanaResearch/panyana-science/blob/master/pages/index.vue)
[when generated](https://github.com/PanyanaResearch/panyana-science/blob/gh-pages/index.html) 
as you can see, the %s part of the titleTemplate is blank.

It is updated on the client however, (the title is updated when you go to the actual page) but I thought that generate would fill in the appropriate head tags. so that I could use opengraph meta tags to display info about each page.

**Comment by manniL** [comment]
It should do that (as on https://developmint.de/about-us/index.html)
![image](https://user-images.githubusercontent.com/640208/52203466-2fcaae80-2869-11e9-97f4-6ab1f8c1258a.png)

Can you try it with a function instead of a string template and see if the issue persists? 🤔

**Comment by X1machinemaker1X** [comment]
ok, done. but the generated html files still are missing the title. (see the links above).

**Comment by X1machinemaker1X** [comment]
I found the issue. in the default.vue layout, I had `<no-ssr>` tags around the `<nuxt />` tags. I basically took the project apart and put it back together to find the issue.

**Comment by manniL** [comment]
Well, that explains it :tongue:
