### ISSUE TITLE
Dynamic meta robots index or no index

### ISSUE THREAD

**Issue by codigodo** [nuxt/vue-meta#321]
Hello, I'm trying to get the right index or no index status for google bot. Currently the pages are showing the right status in the browser and source view. 
But fetching as google displays the default, no index status, when for me in the browser shows index status.

Currently using nuxtJS. is Universal

I'm missing something?

```
// landing and location are fetched from the API inside asyncData method
computed: {
    indexStatus() {
      let indexStatus = 'noindex, follow';
      if (this.landing) {
        const foundItem = this.landing.provincesToIndex.find(
          p => p === this.location._id
        );
        if (foundItem) indexStatus = 'index, follow';
      }

      return indexStatus;
    }
  },
  head() {
    return {
      title: `${this.landing ? this.landing.title[0] : ''} ${
        this.location ? this.location.label : ''
      }`,
      meta: [{
          name: 'robots',
          content: this.indexStatus
        },
```

**Comment by manniL** [comment]
@codigodo Could you provide a reproduction repo/Codesandbox?

**Comment by codigodo** [comment]
> @codigodo Could you provide a reproduction repo/Codesandbox?

Sure i'll prepare one

**Comment by codigodo** [comment]
Looks like the problem was related to the google console, suddenly it disappeared.
