### ISSUE TITLE
vue-meta updates only on hot reload

### ISSUE THREAD

**Issue by janswist** [nuxt/vue-meta#326]
I have a problem wit `vue-meta` where on normal page load nothing happens and when I change something in the code and hot reload kicks in it suddenly update all the meta properties.

I'm using Vue.js SPA. Anyone knows what that could be?

**Comment by pimlie** [comment]
Hot reload as in during development? Could you maybe create a minimal reproduction (github or csb)?

**Comment by janswist** [comment]
Yes, during development. I don't know what to reproduce - I just added as stated in vue-meta readme and it worked earlier normally and now it's not without changing anything (?)

**Comment by pimlie** [comment]
Not updating means its probably a reactivity thing. A reproduction shows me what you are trying to do, eg do you use a plain object or a fn for metaInfo?

**Comment by janswist** [comment]
I'm using fn for metaInfo like this:
```
metaInfo () {
    return {
      // Children can override the title.
      title: `${this.job.title }`,
      // Result: My Page Title ← My Site
      // If a child changes the title to "My Other Page Title",
      // it will become: My Other Page Title ← My Site
      titleTemplate: '%s ← Refair.me',
      // Define meta tags here.
      meta: [
        // {'http-equiv': 'Content-Type', content: 'text/html; charset=utf-8'},
        // {name: 'viewport', content: 'width=device-width, initial-scale=1'},
        {'name': 'description', 'content': this.job.project.description},
        
        {'property': 'og:type', 'content': 'website','vmid': 'og:type', },
        {'property': 'og:image', 'content': this.job.company.log, 'vmid': 'og:image'},
        {'property': 'og:title', 'content': this.job.title, 'vmid': 'og:title' },
        {'property': 'og:description', 'content': this.job.project.description, 'vmid': 'og:description' },
        {'property': 'og:url', 'content': `https://refair.me/job/${this.job.id}`, 'vmid': 'og:url' },
      ]
    }
  },
```

**Comment by janswist** [comment]
I'm using fn for metaInfo like this:
```
metaInfo () {
    return {
      // Children can override the title.
      title: `${this.job.title }`,
      // Result: My Page Title ← My Site
      // If a child changes the title to "My Other Page Title",
      // it will become: My Other Page Title ← My Site
      titleTemplate: '%s ← MySite',
      // Define meta tags here.
      meta: [
        // {'http-equiv': 'Content-Type', content: 'text/html; charset=utf-8'},
        // {name: 'viewport', content: 'width=device-width, initial-scale=1'},
        {'name': 'description', 'content': this.job.project.description},
        
        {'property': 'og:type', 'content': 'website','vmid': 'og:type', },
        {'property': 'og:image', 'content': this.job.company.log, 'vmid': 'og:image'},
        {'property': 'og:title', 'content': this.job.title, 'vmid': 'og:title' },
        {'property': 'og:description', 'content': this.job.project.description, 'vmid': 'og:description' },
        {'property': 'og:url', 'content': `https://mysite.com/job/${this.job.id}`, 'vmid': 'og:url' },
      ]
    }
  },
```

**Comment by pimlie** [comment]
So the problem might be that this.job is not reactive, please take a look at https://vuejs.org/v2/guide/reactivity.html and especially the caveats section.

If that still doesnt solve your issue, please create a working reproduction so I can see all the code that is causing this issue.

**Comment by janswist** [comment]
I thought about that, but all the other aspects of page that are dependant upon `this.job` are loading properly (and asynchronously) - can async be the case?

**Comment by pimlie** [comment]
Every line of code is a possible bug, so no but yes ;)

**Comment by pimlie** [comment]
@janswist My last comment might not have been very helpful, but please create a reproduction which we can check as that is much easier/faster for us then discussing all theoretical possible causes. If you managed to solve this issue in the mean time, please close it.

**Comment by janswist** [comment]
I'm closing it for now because I had to move on with project, but when I will get back at it I will try to provide something more tangible.

**Comment by willianrr** [comment]
try initializing in data and once mounted set all variables to a specific meta tag
![image](https://github.com/nuxt/vue-meta/assets/54675459/7fa1bfc5-00f2-4a00-9e49-567014a80de6)
![image](https://github.com/nuxt/vue-meta/assets/54675459/e4e3b807-6f15-4248-9802-784376b469a1)
![image](https://github.com/nuxt/vue-meta/assets/54675459/2a6e2f57-141a-4959-ab89-1ea7e1b9f994)
