### ISSUE TITLE
[v2] build size is too large

### ISSUE THREAD

**Issue by pimlie** [nuxt/vue-meta#328]
When working on v2.0 I was advised to follow the doctrine of letting the transpiler worry about language features, but it seems this resulted in a hugh increase in package size. Current v2 minified size is ~30KB

Possible solutions:
- fix the build (maybe I am missing a magic feature in the rollup config?)
- refactor to dont use 'modern' language features
- create separate umd-classic and umd-modern builds with modern being the default

**Comment by pimlie** [comment]
resolved through bffc742 and b42618c

**Comment by manniL** [comment]
Really wondering how object spread/object assign already causes trouble/issues there.

The current workaround is decent but I'd suggest finding the root cause in a future version so we can keep using new features in the code :relaxed:

**Comment by pimlie** [comment]
What I did was remove babel, add buble, imported a `polyfill.js` in `browser.js` and added to the polyfill module 
```js
import 'core-js/modules/es6.array.includes'
```
Thats where the 4KB came from, without the single polyfill it was 10KB, with 14+KB

I also simply checked babel's polyfilled 30KB gzipped lib to see what was in it. Eg it also contained quite a bit of stuff about regexes, probably because the polyfills not only enable features but also fix wrong behaviour without checking whether the exact cases where that wrong behaviour is triggered are at all used in the source (the only regexes which we use are in eg `escape()`) and I checked by converting all regexes to simple string replacements but that didnt change anything in size.

Could very well be that I am wrong in my observations, but for now I will leave this issue as is. Also please note that this has never been an issue before due to the major difference between buble and babel. For good comparison we should probably take the current v1 codebase and see what babel tries to polyfill, I will leave that to you if you think thats interesting ;)
