### ISSUE TITLE
Title flickers on page change

### ISSUE THREAD

**Issue by BRafols** [nuxt/vue-meta#333]
1.- Go to: [https://nuxtjs.org](https://nuxtjs.org)
2.- Click on "Examples"
3.- You can see that the title flickers for a very short time in which it shows: 'https://nuxtjs.org' as the title.

Then it goes to the normal title.

Expected behavior:

It should wait for the new page to be ready before changing the title and only then take the title from the `head()` method from the new page

**Comment by pimlie** [comment]
This could be solved in `v2.0` with enabling `refreshOnceOnNavigation`. Otherwise its just a quirck of how vue-meta retrieves metadata from (page) components

**Comment by manniL** [comment]
There'll be an edge package soon.

**Comment by pimlie** [comment]
Closing as changes for this issue are included in the [v2 release candidate](https://github.com/nuxt/vue-meta/releases/tag/v2.0.0-rc.0). Please help us testing the release candidate and report any follow-ups in a new issue
