### ISSUE TITLE
Javascript onload hook

### ISSUE THREAD

**Issue by janesser** [nuxt/vue-meta#335]
Hi folks,

we have a use-case where we are lazy loading some library, e.g. from component.mount().
Then we sleep for 100 millies and use some methods from the js-lib loaded.

The usage is from vue-components typescript and will place some result into one of the components properties.

https://stackoverflow.com/questions/16230886/trying-to-fire-the-onload-event-on-script-tag

Actually there is the 'onload' hook that could help here. Is there some example of vue-meta using the onload hook on a script-tag?

What would be required to enable vue-meta to do so?

Kind regards,
Jan

**Comment by pimlie** [comment]
See #240, at the moment this is unfortunately not supported nor is it planned for v2.0

**Comment by manniL** [comment]
Duplicate of #240
