### ISSUE TITLE
Third-party library not adding dependency to Window

### ISSUE THREAD

**Issue by earthtone** [nuxt/vue-meta#345]
When trying to inject a `script` tag with a third-party library into the head from `App.vue` using vue-meta, the script tag is added to the DOM correctly, but the dependency is not attached to the `window` as expected. 

This looks similar to issue #139 , which seems resolved for SSR, but I am trying to achieve this on a single-page application generated with vue-cli.

![Screen Shot 2019-04-16 at 4 30 46 PM](https://user-images.githubusercontent.com/9401180/56187542-4316a900-6066-11e9-86b6-aff8dc6a3f4c.png)

### Expected Behavior

Library should be injected into head **and** dependency should be attached to `window`.

### Actual Behavior

Library is injected into head _but_ dependency is not attached to `window`.

### Code to Reproduce
App.vue

```js
export default {
  name: 'app-root',
  metaInfo () {
    return {
      ...defaults,
      scripts: [{ src: process.env.VUE_APP_EXTERNAL_SDK }]
    }
  }
}
```

SDK URL is provided in `.env.local` file.

### Specification

- vue-meta version: 1.5.2
- vue version: 2.5.17
- vue-cli version:  3.2.1
- system: MacOS Mojave v10.14.4
- browsers: Google Chrome v73.0.3683.103 & Firefox Developer Edition 67.0b10 

Any information would be helpful. Thanks!

**Comment by pimlie** [comment]
Normally when the tag is added (which it apparently is), then vue-meta job's is done and its up to the browser to load the script. But are you sure the script file is being loaded? Eg please check the Network tab and make sure the script request doesnt result in some http error (eg due to adblockers or csp rules)

**Comment by earthtone** [comment]
@pimlie thanks for the response. 

Yes, it looks like my issue is that the browser is not loading the script. I'm receiving warnings regarding "unsafe-inline" and "https within script-src", but no errors are being thrown. Monitoring the network tab, it looks like the script is not being downloaded, even when I append a timestamp.

I know it's not the responsibility of `vue-meta` to do anything more than append the tag to the head, but does anyone know of any useful tricks to get the browser to actually load the script? I'm trying to avoid messing about with the actual DOM API if I can.

**Comment by pimlie** [comment]
@earthtone This should give you insights on how to solve it: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

If you are using Nuxt its just a question of adding the domain to your nuxt.config, see here: https://nuxtjs.org/api/configuration-render#csp

**Comment by earthtone** [comment]
Thanks for the information. Unfortunately we're not using Nuxt, so I'll have to probably update the CSP rules.

To clarify, it's completely expected that adding the script tag via the DOM API's `appendChild` method works for loading the script, but adding it via vue-meta, correct? Just want to make I understand what the problem is.

**Comment by pimlie** [comment]
Well, if the csp rules are the only issue that prevents the script from loading then afaik not really. Your browser should respect those csp rules, no matter if it parses a script tag from html or when a script tag is added with appendChild.

Besides, if the script tag doesnt exist (on page load) after which the tag is added by vue-meta, then vue-meta also uses appendChild. See here: https://github.com/nuxt/vue-meta/blob/master/src/client/updaters/updateTags.js

**Comment by earthtone** [comment]
After reading through the JSDoc comments, I realized I made an embarrassing typo in my implementation -- `scripts` vs `script`! 😅

@pimlie thanks so much for the help debugging this.
