### ISSUE TITLE
Minor Validation Error with Async and Defer in Meta Info

### ISSUE THREAD

**Issue by mjatharvest** [nuxt/vue-meta#346]
## Description

This is a very small thing, when adding a script tag to the head via metaInfo, I see that the async and defer attributes on the script tag have a value of true.

### Steps to reproduce

```
<script>
  import MainNav from '~/components/MainNav.vue'
  import Footer from '~/components/Footer.vue'

  export default {
    metaInfo: {
      script: [
        { src: '//www.google.com/recaptcha/api.js', async: true, defer: true }
      ]
    },

```
### Expected result
`<script data-vue-tag="true" src="//www.google.com/recaptcha/api.js" async defer></script>`

### Actual result
`<script data-vue-tag="true" src="//www.google.com/recaptcha/api.js" async="true" defer="true"></script>`

This end up giving a validation error: Bad value true for attribute async on element script.

### Environment

<pre><code>
- gridsome version: 0.5.7
</code></pre>
![Screen Shot 2019-04-12 at 9 27 09 AM](https://user-images.githubusercontent.com/285877/56044636-39f3a800-5d05-11e9-91de-fbbdd8f272a8.png)
![Screen Shot 2019-04-12 at 9 14 00 AM](https://user-images.githubusercontent.com/285877/56252221-78c68c80-607c-11e9-89d8-65b086502f6b.png)

**Comment by pimlie** [comment]
Closing as changes for this issue are included in the [v2 release candidate](https://github.com/nuxt/vue-meta/releases/tag/v2.0.0-rc.0). Please help us testing the release candidate and report any follow-ups in a new issue

See here for specific info about boolean attributes in `v2`: https://vue-meta.nuxtjs.org/guide/special.html#boolean-attributes
