### ISSUE TITLE
base doesn't render (in Nuxt)

### ISSUE THREAD

**Issue by merrylmr** [nuxt/vue-meta#349]
hi, @pimlie ,The problem is as follows
in nuxt.config.js:
![image](https://user-images.githubusercontent.com/21325085/56569470-9d29e800-65eb-11e9-9349-6fb0e198a849.png)

but  it doesn't render base tag.
![image](https://user-images.githubusercontent.com/21325085/56569585-d5c9c180-65eb-11e9-8fc6-7e98ca1dd84c.png)

**Comment by pimlie** [comment]
Thanks for the report. Nuxt has its own base implementation and they ignore the base set within head: https://github.com/nuxt/nuxt.js/blob/f5bbc585eefb4f72f03a26f125319cf6592072af/packages/vue-renderer/src/renderers/ssr.js#L58

You can try to set [router.base](https://nuxtjs.org/api/configuration-router/#base) in your nuxt.config to `/`, but if you also really need the `target` it seems you are out of luck for now.

As this is not a vue-meta issue, please report an issue in the nuxt repository if setting `router.base` isnt sufficient for you
