### ISSUE TITLE
Issue with accessing Vuex Computed Property

### ISSUE THREAD

**Issue by youngbobby** [nuxt/vue-meta#366]
Hi,

I'm finding it difficult to access a computed properties from Vuex. I've tried everything I read from the examples and it still doesn't seem to work. 

I am getting this error: **Cannot read property 'job' of undefined**

**Code:**
```
  computed: {
    ...mapGetters({
      job: 'oneJob'
    })
  },

  metaInfo: {
    title: this.job.title,
}
```

Any help would be greatly appreciated.

**Comment by pimlie** [comment]
Please see: https://vue-meta.nuxtjs.org/faq/component-props.html

**Comment by youngbobby** [comment]
Thank you so much!
