### ISSUE TITLE
Truncate Long Texts if above certain length

### ISSUE THREAD

**Issue by youngbobby** [nuxt/vue-meta#367]
Is it possible to truncate long texts (in my case, Meta descriptions, og:description etc) with ellipses (...) appended at the end ?

**Comment by manniL** [comment]
Pretty sure you can do that in userland :relaxed:

**Comment by youngbobby** [comment]
You're right. It turns out my problem is not a truncation problem. For some weird reasons, I am not able to access all my Vuex computed properties in **metaInfo**.

```
    return {
      title: this.title,
      titleTemplate: '%s - SiteName',
      meta: [
        {
          name: 'description',
          content: this.description
        },
    ]
}
```

`this.title` returns fine but `this.description` and every other data returns undefined which made me think I was not truncating the string properly 

I could really use some help :(

**Comment by youngbobby** [comment]
Fixed.

**Comment by youngbobby** [comment]
Would you believe if I told you, there was no bug in the first place? The `meta` code I was looking for was there the whole time! However, it was not outputted with the same convention as the code was written so ... there, I felt embarrassed.

As for truncating long texts which is the original reason why this issue was opened, I ended up using the code below:

```
String.prototype.trunc = 
      function(n){
          return this.substr(0,n-1)+(this.length>n?'&hellip;':'');
      };
```

Usage: 

```
var s = 'not very long';
s.trunc(25); //=> not very long
s.trunc(5); //=> not...
```

As seen on [StackOverflow](https://stackoverflow.com/a/17177423)
