### ISSUE TITLE
Feature Request: add scripts right after opening <body> tag

### ISSUE THREAD

**Issue by derz** [nuxt/vue-meta#370]
Right now it is possible to add a script before the closing </body> tag using the `body: true` flag, however it is often desired to also have the option to add them right after the opening <body> (for example to implement this one: https://github.com/nuxt-community/modules/issues/263). Any chance this gets impelmented? I'm happy to assist/implement if we can decide/find a proper API .

**Comment by pimlie** [comment]
From vue-meta's side this is easily implemented, but it would be up to Nuxt to use/implement that extra functionality.

@manniL @pi0 @clarkdo Wdyt?

**Comment by manniL** [comment]
I think it's a good idea to have that option available 👍

**Comment by f3r** [comment]
Hi guys, I need to add Google Tag Manager to my Nuxt app. Tried adding https://www.npmjs.com/package/@nuxtjs/google-tag-manager but keep getting a 404.

![image](https://user-images.githubusercontent.com/970858/60503291-4a3d7280-9cb7-11e9-85a2-b447c2dc3b6f.png)

I can easily add the first part as a script and load it with:

```
import pkg from './package'
export default {
  mode: 'spa',
  head: {
    script: [
      { src: '/gtm.js' }
    ]
    ...
```

But I can't find a workaround for adding the No-Script iframe content, and therefore, I can't collaborate with the marketing team to manage tags directly :(

Is this feature going to be integrated in Nuxt soon? Are there any quick workarounds people use for this?

Thanks so much!!
