### ISSUE TITLE
Not rendering meta tags

### ISSUE THREAD

**Issue by liftyourgame** [nuxt/vue-meta#378]
I've been experimenting with vue-meta in a Vuetify app. I'm not using Nuxt so I'm expecting vue-meta to work client side.

It seems to render titles correctly but "meta" tags are not being rendered.

I've stepped through the code in Chrome Dev tools and it seems the tags are being generated but for some reason are not being added to Head when I look in Chrome Dev tools sources for Index page.

In router.js I have:

```
Vue.use(Router)
Vue.use(VueMeta, {
  refreshOnceOnNavigation: true
})
```
In App.vue I have:

```
  export default {
    name: 'App',
    metaInfo: {
      meta: [
        { charset: 'utf-8' },
      ],
      // if no subcomponents specify a metaInfo.title, this title will be used
      title: 'mysite.com',
      // all titles will be injected into this template
      titleTemplate: '%s | mysite.com'
    },

```
In Home.vue I have:

```
  export default {
    name: 'Home',
    metaInfo: {
      title: 'Home',
      meta: [
        { vmid: 'description', name: 'description', content: 'This is a site to ...' }
      ]
    },

```

Using     "vue-meta": "^1.6.0" via yarn

Title tag correctly sets to: Home | mysite.com

Neither the charset or description tags are set in the rendered page.

**Comment by pimlie** [comment]
Please note that `refreshOnceOnNavigation` is a vue-meta v2 feature, it doesnt do anything in v1.x. 

Unfortunately I cant reproduce this behaviour, see : https://jsfiddle.net/9dLg1fjr/ which works both with vue-meta v1 as v2

**Comment by liftyourgame** [comment]
Thanks for your attention @pimlie 

Your fiddle generates head tag:

```
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title></title>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="robots" content="noindex, nofollow">
  <meta name="googlebot" content="noindex, nofollow">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

```

How do I yarn add v2? Not in the documentation.

**Comment by pimlie** [comment]
Use the `next` tag, eg run `yarn add vue-meta@next`

We will probably release v2 in the next week :)

**Comment by liftyourgame** [comment]
Thanks @pimlie 

Was looking in the wrong place. I was just used to seeing meta tags at the top of head. In my actual page they were inserted after a bunch of <style> tags injected by my framework.

Thanks for your help. All the best with the v2 release.

**Comment by zheeeng** [comment]
@pimlie I'm using vue-meta@2.0.3 and have the same issue.
