### ISSUE TITLE
IE11 doesn't work with latest version of Vue Meta. Vue.js cli + SSR.

### ISSUE THREAD

**Issue by SavkaTaras** [nuxt/vue-meta#387]
Vue js cli 3 doesn't open the page in IE11. Using server side rendering.

IE11 console throws the error: SCRIPT1002: Syntax Error (app.js).

I have "es6-promise": "^4.2.8" that works well for IE11 to render ES6 syntax.

This is Vue Meta issue. I upgraded all packages but vue meta and it worked well. Once I updated Vue-Meta IE11 crashed. IE11 works well with Vue meta version "^1.6.0".

Anyone else having the same issue?

Thank for the help.

**Comment by pimlie** [comment]
Will have a look at this tomorrow. Actually somebody mentioned this already this afternoon but I misunderstood what he meant I guess (sry @pi0 :+1: )

**Comment by pimlie** [comment]
This should be fixed in v2.0.2, please try and let me know

**Comment by SavkaTaras** [comment]
Confirmed, working as it should.

Thank you!

**Comment by SavkaTaras** [comment]
Resolved. Thanks
