### ISSUE TITLE
Can we use meta injection feature without Vue?

### ISSUE THREAD

**Issue by zheeeng** [nuxt/vue-meta#398]

**Comment by manniL** [comment]
Please add more information.

**Comment by zheeeng** [comment]
Separate the core feature meta-injection and vue-binding.
I'm using prerendering and want to inject stylesheet as soon as possible by programming.
Consider we have already had vue-meta, it is unnecessary to install another meta injector to do it.
At present, this vue-meta injects head meta after component mounted.

**Comment by pimlie** [comment]
Thanks for the reply, unfortunately I still have troubles understanding your use-case. Where does the metaInfo come from if you are not using Vue components? Could you share some (pseudo)code to clarify maybe?

Small nitpick. On ssr a component will never be 'mounted', just created. See https://ssr.vuejs.org/guide/universal.html#component-lifecycle-hooks

**Comment by zheeeng** [comment]
```js
// main.js

// declare top level meta info
import { inject } from 'vue-meta'

inject({
      title: 'My website',
      link: [
         { rel: 'stylesheet', href: 'https://third-party/widget/large-size.css' }
      ],
     script: [
        { src: 'https://third-party/widget/large-size.js', async: true, defer: true }
      ]
})

// startup Vue app
...
```
I wish we insert these tags as soon as possible for improving the first meaningful screen painting and decreasing the hanging time to interactive.

**Comment by pimlie** [comment]
Interesting thoughts. Did you by chance already take some measurements how this approach could benefit the time to first paint? If so, could you share those and also how you measured this (preferably also the code so we could repeat the tests)?

Would be very interested in those if you have them, if there is a consistent benefit i'd most likely be interested to add official support for this approach.

Unfortunately at the moment no builds give you direct access to the inject method. For testing purposes you could clone this repo, run `yarn link` and in your project run `yarn link vue-meta` (or add a webpack alias). Then you should be able to investigate if it would work or not.

**Comment by zheeeng** [comment]
I have no measure data for this and I'm digging how to improve the score of the page speed insights(https://developers.google.com/speed/pagespeed/insights) and the third party widget indeed is a concern part.

**Comment by pimlie** [comment]
I think most of the benefit this approach would see comes from the difference in render time on the server for the full page. This can already be largely be optimized by implementing a [component cache](https://ssr.vuejs.org/guide/caching.html#component-level-caching).

To be honest, unless you really have a need for extreme optimizations, I dont think this approach will be really worthwhile just to improve the page speed. And you are limiting yourself quite a bit by removing a core-feature of vue-meta's flexibility.

Eg, the following questions are important:
- what is the total render time of a full page?
- is this the fastest render time possible or can you improve this by general code optimization (eg functional components), caches etc?
- how much of that render time can you mitigate with a early return of the `<head>`?
- how does that time compare with the average network latency to your users?
- is it guaranteed that the early return is immediately sent to the browser or is there some optimisation in the network stack that waits for a minimum size of a tcp packet?

Also this only applies to SSR, not [Prerendering](https://ssr.vuejs.org/#ssr-vs-prerendering). If you use prerendering the html is created on build so it has no connection at all with page speed.

Maybe all you need is [`body: true`](https://vue-meta.nuxtjs.org/api/#special-attribute-body-true) to defer not important scripts to the html body so they dont block the first render time (you will need an additional [call](https://vue-meta.nuxtjs.org/guide/ssr.html#add-vue-meta-to-the-context) to context.meta.inject in your page template)?

**Comment by zheeeng** [comment]
Thx for your reply.

Assume a situation that meta injection doesn't happen in the pre-rendering process or SSR (avoid by env var). Only when users visited the pre-rendered/SSR outputed HTML some meta tags will be injected. We could load these scripts asynchronously by `async` prop, but now it is put off till vue bundle is loaded and be executed.

Separated injection feature provides us a flexible usage.

**Comment by pimlie** [comment]
Hmm I see, not sure if this is an edge-case we should support as it doesn't sound like a good architecture to me. This package is aimed at being used with Vue and not with vanilla js (even though it has to use vanilla js to update metadata client side).

@manniL would appreciate your thoughts

**Comment by manniL** [comment]
FUlly agree with @pimlie here. I think this is out of the scope of vue-meta. It should also not be the bottleneck / a perf issue compared to other parts like 3rd party code, code splitting etc.

**Comment by pimlie** [comment]
@zheeeng Hey, so it took a while unfortunately but we finally realized there is indeed a good use-case for the feature you requested. Sorry for that.

In `v2.2.0` you can directly generate the tags without using Vue, [see the docs here](https://vue-meta.nuxtjs.org/api/#generate-since-v2-2)
