### ISSUE TITLE
IE/Edge error: 'use strict'

### ISSUE THREAD

**Issue by NCJasper** [nuxt/vue-meta#420]
Browser: Microsoft Edge 42.17134.1.0
Vue-meta version: 2.1.0

Ran into same issue as #418 which I "fixed" by updating to my babel to `babel/core:7.5.5`, however IE/Edge now throw another error:
`SCRIPT1028: Expected identifier, string or number` pointing to line 7403 the attached screenshot.
![image](https://user-images.githubusercontent.com/45785931/61950737-13edcd00-afaf-11e9-99d1-676ae3093abc.png)

It works perfectly fine in Chrome and Firefox, of course...

Any hints to fix this would be helpful!

**Comment by pimlie** [comment]
This was probably also caused by the missing babel config, please try v2.1.1

**Comment by NCJasper** [comment]
Great! Thanks for fixing this :)
