### ISSUE TITLE
I want support head.insertBefore

### ISSUE THREAD

**Issue by flyhope** [nuxt/vue-meta#425]
vue-meta can use 
* body.insertBefore
* body.appendChild
* head.appendChild

but can't support head.insertBefore. I want support head.insertBefore.

Because builder's remote css must be load first, own project's vue style load second.
So we need insert <link href="xxxx"> to head first line.

Thanks !

**Comment by pimlie** [comment]
Do you mean for server side rendering?

**Comment by flyhope** [comment]
no. my html in xxx.vue js file.

**Comment by pimlie** [comment]
Could you share some minimal example of code that you currently use?

Eg if your builders css is included in the html as tag, then it has no use to use insertBefore within VueMeta because there is a significant delay between the time your browser parses the style tag in the html and the time your browser has finished downloading all javascript, started your Vue app and finally VueMeta initializes to dynamically insert your projects' styles.

**Comment by flyhope** [comment]
> Could you share some minimal example of code that you currently use?
> 
> Eg if your builders css is included in the html as tag, then it has no use to use insertBefore within VueMeta because there is a significant delay between the time your browser parses the style tag in the html and the time your browser has finished downloading all javascript, started your Vue app and finally VueMeta initializes to dynamically insert your projects' styles.

for example:

`http://www.chengxuan.li/debug/main.css` looks like builder's public common style.

In this components, I want to change h1 color "red". But vue-meta append end of head, not insert first of head.
so h1 color can't change to red.

```vue
<template>
<div>
    <h1>I want color is red</h1>
</div>
</template>

<style>
h1, h2 {
    color:red;
}
</style>

<script>
export default {
    metaInfo: {
        title: "demo",
        link: [
            {
                rel: "stylesheet",
                href: "http://www.chengxuan.li/debug/main.css"
            }
        ]
    }
}
</script>
```

**Comment by pimlie** [comment]
You could ofc also fix this by just making sure your custom css has a higher priority then your builders style.
```css
#yourAppId h1, #yourAppId h2 {
  color: red;
}
```
or import the main.css within the style tag:
```html
<style>
@import url('http://www.chengxuan.li/debug/main.css');

h1, h2 {
    color:red;
}
</style>
```

@manniL would appreciate your thoughts

**Comment by flyhope** [comment]
> You could ofc also fix this by just making sure your custom css has a higher priority then your builders style.
> 
> ```css
> #yourAppId h1, #yourAppId h2 {
>   color: red;
> }
> ```
> 
> or import the main.css within the style tag:
> 
> ```
> <style>
> @import url('http://www.chengxuan.li/debug/main.css');
> 
> h1, h2 {
>     color:red;
> }
> </style>
> ```
> 
> @manniL would appreciate your thoughts

In our team, `<style>`'s css code and html code write by a other builder, is not me. I write javascript only. so not use higher priority.


Before create this issue, I use `@import main.css`. But it's have some problem. 

a.vue
```vue
<style>@import url('http://www.chengxuan.li/debug/main.css');</style>
<style src="@/assets/css/custom.css"></style>
```

b.vue style is the same as a.vue, `@/assets/css/custom.css` is to big.

When a jump to b use vue router history mode, `@/assets/css/custom.css` is only load once when a.vue load. Because webpack4 auto splite chunk custom.css. So the end of css file is main.css. The h1 color is green, not red.


So i want vue-meta support a attribute `data-phead`(provisional), looks like `data-body` and `data-pbody`. Then my problem was solved perfectly.

**Comment by manniL** [comment]
I don't see a good use case for prepending scripts in head instead of appending. Using `scoped` styles should also work in this use case.

**Comment by flyhope** [comment]
> `scoped`

My child components well be use parent component's style. So can't use `scoped` style.

**Comment by manniL** [comment]
Well..

All in all, this sounds more like an issue of your CSS "architecture" than vue-meta.

**Comment by flyhope** [comment]
> Well..
> 
> All in all, this sounds more like an issue of your CSS "architecture" than vue-meta.

Our builder's css is not problem. but with use vue together has som problem.

vue-meta support `phead` attitude looks like 'pbody' and 'body' can resolve my problem.

**Comment by pimlie** [comment]
We might consider to add this later on but it has no priority for me.

I also think that relying on the tag order to correctly apply your css is inherently wrong and prone to errors. As suggested above, it would be much better to use id's and/or classes to reach the [specifity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) you need
