### ISSUE TITLE
Node v8/9: Cannot set property console of #<Object> which has only a getter

### ISSUE THREAD

**Issue by lincenying** [nuxt/vue-meta#428]
vue-meta: v2.1.0 +
vue 2.6.0
======
There are no errors in downgrading to version 2.0.5
or
del this line `var console = _global.console = _global.console || {};` Are right

**Comment by pimlie** [comment]
Hmm, interesting. Which environment, eg node or browser? Which version?

**Comment by lincenying** [comment]
in node, node ver: 8.16.0

**Comment by pimlie** [comment]
Did a quick check, seems both Node v8 as v9 are affected. v10+ are safe to use.

**Comment by vjandrei** [comment]
I have the same issue when I deploy to Firebase hosting server.

**Comment by pimlie** [comment]
Will release a new version in the next couple of minutes/hours

**Comment by pimlie** [comment]
Should be fixed in `v2.2.1`

**Comment by lincenying** [comment]
thanks
