### ISSUE TITLE
<meta> elements on newline instead of minimized

### ISSUE THREAD

**Issue by geoffreymcgill** [nuxt/vue-meta#432]
Hi. Are there any secrets to rendering each `<meta>` element onto a newline instead of as one minimized block of tags?

For example:

```js
meta: [
    { vmid: "description", name: "description", content: "description here" },
    { vmid: "og:title", property: "og:title", content: "og title here" },
    { vmid: "og:description", property: "og:description", content: "og description here" },
]
```

#### Template

```html
<head>
    {{{ meta.inject().title.text() }}}
    {{{ meta.inject().meta.text() }}}
    {{{ meta.inject().link.text() }}}
</head>
```

### Existing

```xml
    <meta name="description" content="description here"><meta property="og:title" content="og title here"><meta property="og:description" content="og description here">
```

### Revised?

```xml
    <meta name="description" content="description here">
    <meta property="og:title" content="og title here">
    <meta property="og:description" content="og description here">
```

I searched through all the docs and open/closed issues and could not find any related info. Keywords included: `newline`, `linebreak`, `format`, `formatting`

**Comment by manniL** [comment]
What's reason behind that feature request? :thinking: 	
It doesn't make a difference for the client AFAIK

**Comment by geoffreymcgill** [comment]
> It doesn't make a difference for the client AFAIK

Correct, there is no difference on the client and minimizing would actually reduce the payload ever so slightly. Defaulting as a minimized block is likely best.

Our goal is that we're working on a process to clean up the formatting of the html, so it looks prettier and is more human-readable during development. We rely on another process to minimize the response (+ gzipping).

Hope this helps.

**Comment by manniL** [comment]
I see.

You could probably hook in here https://github.com/nuxt/vue-meta/blob/master/src/server/generators/tag.js#L87-L89 and add a line break or so.

Not sure if it is suitable for a PR though. WDYT @pimlie 	?

**Comment by pimlie** [comment]
My suggestion would be to do something like this for now (just watch out with noscripts containing html):

```js
{{{ meta.inject().meta.text().replace('><', '>\n<') }}}
```

This seems such an edge-case that I dont think we should add support for this. But I have been thinking about refactoring the inject interface so I will keep this in my mind anyway when I look at that.

**Comment by geoffreymcgill** [comment]
Thanks @pimlie. Nice clean work-around using `replace`. 👍 

Instead of a substr pattern, we went with a regex pattern to replace all instances of `><` in the block. The string replacement technique also enables us to inject some leading spaces (or a `\t` if that's your thing) as a prefix into the newline.

```js
{{{ meta.inject().meta.text().replace(/></g, '>\n    <') }}}
```

Hope this helps.
