### ISSUE TITLE
[types] missing `content` in MetaPropertyEquiv

### ISSUE THREAD

**Issue by SilentDepth** [nuxt/vue-meta#435]
If I read the MDN page right, a `<meta>` which has a `http-equiv` attribute should not require a `name` attribute but a `content` attribute?

Relating code:

https://github.com/nuxt/vue-meta/blob/master/types/vue-meta.d.ts#L60-L64

References:

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#Notes
* https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element

**Comment by pimlie** [comment]
THanks, probably just a typo or wrongly copied as it lists the `template` but no content at all. Do you want to submit a pr for it?
