### ISSUE TITLE
_hasMetaInfo has been deprecated, use hasMetaInfo(vm) instead

### ISSUE THREAD

**Issue by HapLifeMan** [nuxt/vue-meta#437]
Hey, I've just upgraded the dependency and this warning is now in the console:
```
VueMeta DeprecationWarning: _hasMetaInfo has been deprecated and will be removed in a future version. Please use hasMetaInfo(vm) instead
```
Could you take a look at it? Thanks!

**Comment by pimlie** [comment]
There isnt really anything to look at for me. Somewhere in your project the _hasMetaInfo is used but that has been deprecated since v2, exactly as the message says ;)

**Comment by HapLifeMan** [comment]
Thanks for your quick reply! I searched for this in my whole project before opening this issue and there's nothing like this, even something with "metainfo" 🤔

**Comment by pimlie** [comment]
Do you use Nuxt? Eg I know the nuxt-i18n module was using it but that's fixed in v6.0.2

**Comment by HapLifeMan** [comment]
Yes I do. Oh, I didn't see the `nuxt-i18n` upgrade yesterday, thanks 😊

**Comment by noureddinenoureddine** [comment]
reappears in nuxt `2.10.2`

**Comment by pimlie** [comment]
@noureddinenoureddine Maybe you could report this in the nuxt-i18n repo? Nothing much we can do about that here unfortunately.
