### ISSUE TITLE
[types] Individiual meta object types not exported

### ISSUE THREAD

**Issue by rchl** [nuxt/vue-meta#440]
Types export `MetaInfo` object but not invidivual types that it consits of. Let's say I want to mark script object in my code with `ScriptPropertySrc`. How can I do that?

```ts
const scriptObject: ScriptPropertySrc = {
  src: 'some-script.js',
};
```

I have no access to `ScriptPropertySrc` type.

**Comment by pimlie** [comment]
Hmm, seems you cant at the moment indeed.

@kevinmarrec Could you maybe advice on this? I.e. should we just export all the individual types as well or is there a better/smarter way?

**Comment by kevinmarrec** [comment]
https://github.com/nuxt/vue-meta/blob/master/types/vue-meta.d.ts#L129

The types are not exported through the main `index.d.ts` but they are still exported so can be imported like this :

```ts
import { ScriptPropertySrc } from 'vue-meta/types/vue-meta'

const scriptObject: ScriptPropertySrc = {
  src: 'some-script.js'
}
```

**Comment by rchl** [comment]
But is that optimal? You kinda have to know about it. Wouldn't it make sense to export everything public from main endpoint?

**Comment by rchl** [comment]
@kevinmarrec are you open to just doing
```js
export * from './vue-meta'
```
?

Alternatively painstaingly selecting just the exports that are really supposed to be public...

**Comment by kevinmarrec** [comment]
Dunno, i'm fine with it @pimlie WDYT ?

**Comment by pimlie** [comment]
As I am not (yet) a typescript user myself I will follow @kevinmarrec advise in this.

If someone else wants to spent time on this then I am happy to merge a PR though. But we really should only export types that are meaningful which means the types need to be _painstakingly_ checked :)

**Comment by rchl** [comment]
> let user use #440 (comment) solution which IMO still logic

User shouldn't know the package's internals (how the files are structured). User should only rely on public parts which is the main export. Otherwise it's fairly easy for things to break if @pimlie decides to refactor stuff and move types around for some reason, for example.

**Comment by kevinmarrec** [comment]
@rchl That's not true cause for example, to extend the `Vue` interface or even Component options, it needs to be declared around `vue/types/vue` & `vue/types/options`, not just `vue`.

In JS land, User indeed shouldn't know the package's internals, but in TS land, user often care of internal typings and often get used to extend them.
