### ISSUE TITLE
Memory leak (fixed in v2.2.2)

### ISSUE THREAD

**Issue by frlinw** [nuxt/vue-meta#442]
Initial state of Route 1:
![image](https://user-images.githubusercontent.com/11896237/64013977-514ef880-cb21-11e9-9bbf-255fc7a3aebd.png)
Navigation to route 2 -> back to route 1 -> force garbage collection (with vue-meta):
![image](https://user-images.githubusercontent.com/11896237/64014062-83f8f100-cb21-11e9-8d45-4e0b6cab4f52.png)
Navigation to route 2 -> back to route 1 -> force garbage collection (without vue-meta):
![image](https://user-images.githubusercontent.com/11896237/64014156-c6bac900-cb21-11e9-94a1-73ba408c188e.png)

Components are never garbage collected, does vue-meta keep a ref of them somewhere?

**Comment by pimlie** [comment]
Not that I am aware off. What does your app look like, can you share a small reproduction?

**Comment by pimlie** [comment]
Hmm, actually I notice that indeed the VueComponent count keeps increasing with taking memory dumps of the example with vue-router.

**Comment by frlinw** [comment]
vue-meta was mentioned in the `Retainers` view of a VueComponent, I removed it and then the memory leak disappeared. I can't help further for now because I switched to vue-head. I'll try to reproduce when I'll have more time.

**Comment by pimlie** [comment]
Thanks for the report btw, this might actually be related to an issue in Vue.js. It took a while but I have tracked it down to a possible issue with programmatically adding destroyed hooks, see https://github.com/vuejs/vue/issues/10458

When I add the destroy hooks directly on the mixin then there isnt a memory leak. Unfortunately that means the destroyed hook will run for every component on the page. Might do that as workaround for the time being.

**Comment by edwh** [comment]
If you do that, then wouldn't that provoke the timer thrash which I saw in the related issue?

**Comment by pimlie** [comment]
Nah, would still check if the component has any metaInfo defined before adding those times (you can have a look at the `src/shared/plugin.js` file of the v1 branch)

**Comment by pimlie** [comment]
I have released `v2.2.2` with a workaround for the memory leak. Will keep this issue open until the Vue issue gets resolved

**Comment by AndrewBogdanovTSS** [comment]
@pimlie the issue is still present even after upgrading to v.2.2.2

**Comment by pimlie** [comment]
@AndrewBogdanovTSS Thanks but again, please provide proof through a reproduction!

Just spent half an hour searching for that needle and I cant reproduce it.

**Comment by frlinw** [comment]
I retested with 2.2.2 and can confirm it's fixed.
@pimlie Feel free to close unless you want to leave it open until you have a better way to do it

**Comment by pimlie** [comment]
@frlinw Thanks for the confirmation.

Will keep this issue open for visibility, but have locked the conversation.

If someone has a reproduction of another memory leak in vue-meta, please create a new issue.
