### ISSUE TITLE
Docs - Update link to Nuxt docs

### ISSUE THREAD

**Issue by novellac** [nuxt/vue-meta#445]
**Issue**
Within the [current vue-meta guide page](https://github.com/nuxt/vue-meta/blob/master/docs/guide/frameworks.md), the link to the Nuxt docs leads to [Async](https://nuxtjs.org/api/), but there is a more specific [Head](https://nuxtjs.org/api/pages-head) page we could link.

**Impact**
Forces users to read through unrelated documentation before finding where vue-meta is referenced.

**Possible Fix**
On the [Frameworks](https://github.com/nuxt/vue-meta/blob/master/docs/guide/frameworks.md) page, I will change the link from [Async](https://nuxtjs.org/api/) to [Head](https://nuxtjs.org/api/pages-head).

**Comment by manniL** [comment]
PR welcome ☺️
