### ISSUE TITLE
The vue-meta not support prerender-spa-plugin?  why?

### ISSUE THREAD

**Issue by Coding-Yuan** [nuxt/vue-meta#450]
The vue-meta not support prerender-spa-plugin? thanks.

**Comment by pimlie** [comment]
Please ask your question in English and add a reproduction of whats not working

**Comment by Coding-Yuan** [comment]
> Please ask your question in English and add a reproduction of whats not working

Why is there no title, description, keywords that are set by vue2.x when it is rendered from prerender-spa-plugin? thanks

**Comment by Coding-Yuan** [comment]
> Please ask your question in English and add a reproduction of whats not working

The vue-meta not support prerender-spa-plugin? thanks.

**Comment by pimlie** [comment]
@Coding-Yuan Could please let me and future people searching for this know if (and how) you got vue-meta to work with prerender-spa-plugin?

Thanks!

**Comment by Coding-Yuan** [comment]
> @Coding-Yuan Could please let me and future people searching for this know if (and how) you got vue-meta to work with prerender-spa-plugin?
> 
> Thanks!

Sorry, I used `vue-cli-plugin-prerender-spa` and `vue-meta-info` to solve this problem. Maybe configuring the `captureAfterElementExists` option can also solve this problem. 🙂

**Comment by thomason84** [comment]
> Thanks! Hmm, actually never tried but doesnt the prerender-spa-plugin just load the webpage in puppeteer and extracts the html?
> 
> Maybe try to set the prerender-spa config option `captureAfterElementExists` to wait for one of the head tags vue-meta should be adding. In a default vue-meta config you should be able to set `captureAfterElementExists: '[data-vue-meta]'` as it will then wait for any tag with the [`data-vue-meta`](https://vue-meta.nuxtjs.org/api/#attribute) attribute set.

This worked perfectly! Thank you so much pimlie
