### ISSUE TITLE
Vuetify after 2.0.11 fail support vue-meta

### ISSUE THREAD

**Issue by orionych** [nuxt/vue-meta#451]
Hi - after updating vuetify - vue-meta fails with many errors , like BeforeHook smAndDown and so on - can you check it?

**Comment by pimlie** [comment]
Thanks for the report. Probably it would be better to create an issue in their repo. I know there are/have been some issues with it but i believe @kevinmarrec has submitted a pr with a workaround for that.

**Comment by kevinmarrec** [comment]
@orionych Last Vuetify version needs Vue Meta 2 to properly work, what is yours ?

**Comment by orionych** [comment]
1.6.0
i try to upgrade

вт, 10 сент. 2019 г. в 22:39, Kevin Marrec <notifications@github.com>:

**Comment by kevinmarrec** [comment]
I did a fix that will make last Vuetify version works back with vue-meta@1.
You can either wait next Vuetify release OR upgrade to vue-meta@2.

**Comment by orionych** [comment]
I upgrade to vue-meta@2.1.1 but it's removing all colors from vuetify - i
didnt' check why yet - but forced to remove it untill i figured out why so

Original colors:
[image: Снимок экрана 2019-09-11 в 9.59.29.png]
Colors after making vue-meta enabled:
[image: Снимок экрана 2019-09-11 в 10.01.16.png]


ср, 11 сент. 2019 г. в 09:57, Kevin Marrec <notifications@github.com>:

**Comment by kevinmarrec** [comment]
Which Vuetify version ?

**Comment by orionych** [comment]
2.0.15, today i upgrade to 2.0.16

ср, 11 сент. 2019 г. в 10:04, Kevin Marrec <notifications@github.com>:

**Comment by kevinmarrec** [comment]
Weird. Unless having a repository with reproduction I won't be able to figure out what's going on

**Comment by orionych** [comment]
i will check it soon and write if there is a problem

ср, 11 сент. 2019 г. в 10:19, Kevin Marrec <notifications@github.com>:

**Comment by ctwhome** [comment]
I also found a weird error that i don't know from where it comes, but when using vue-meta with vuetify (2.0.18), the colors for components do not apply if they are = 'primary', 'success', etc..

example: 
`<v-app-bar app color="primary">`
this will be and app bar without color at all. But if you change it to color="red" then it works.

**Comment by yariksav** [comment]
Now in 2.1.0
meta.getOptions is function, its stub "showWarningNotSupport" and returns undefigned
![image](https://user-images.githubusercontent.com/2553313/66047937-54c70c80-e531-11e9-9cbd-bd641642102b.png)
anf meta.getOptions().keyName throws error "TypeError: Cannot read property 'keyName' of undefined" and application falls down

**Comment by kevinmarrec** [comment]
Closing initial issue as there isn't really reproduction and I think every `vue-meta` issue has been resolved for now.

About Nuxt 2.10 @yariksav, please see https://github.com/vuetifyjs/vuetify/issues/9181 :)

**Comment by yariksav** [comment]
> Closing initial issue as there isn't really reproduction and I think every `vue-meta` issue has been resolved for now.
> 
> About Nuxt 2.10 @yariksav, please see [vuetifyjs/vuetify#9181](https://github.com/vuetifyjs/vuetify/issues/9181) :)

Thank you, waiting for fixes
