### ISSUE TITLE
option to inject a script as is.

### ISSUE THREAD

**Issue by dcustodio** [nuxt/vue-meta#455]
Hey everyone! 
I am trying to inject a specific script in a specific page.
That script adds some function to the window object and also reads the it's configuration from there.  
Typically I can interact with the script like so:
```
window.bot.push(['say','hello world'])
```
I tried using Vue's mounted() hook without success. After researching I found that I could use vue-meta, and I've configured my page like this:
```
export default {
    head() {
        return {
            script: [
                {
                    src: '/bot.js',
                    body: true,
                    defer: true,
                    async: true,
                    type: 'text/javascript'
                }
            ]
        }
    }
```
The script loads the bot fine but it still can't listen to the `window.bot.push` events.
Any hints on how this should be done?
I am not sure if it's something with nuxt's SSR or whatnot. I just wanted to be able to paste a script that would run without interference from the platform.

**Comment by pimlie** [comment]
Hey! You have to use the callback option to make sure your `window.bot.push` is only called once the bot.js script is loaded. See here for an example: https://vue-meta.nuxtjs.org/api/#callback-since-v2-1

**Comment by dcustodio** [comment]
Hi @pimlie I tried using a callback but somehow the hooks didn't respond there. Manually adding them in the devtools console seems to work. I reckon it could be something related to the script initialization so I will go the easy way and use an iframe for the time being. 
Thanks for the help!
