### ISSUE TITLE
Add titleTemplate option to plugin global config (e.g. Vue.use)

### ISSUE THREAD

**Issue by georgyfarniev** [nuxt/vue-meta#456]
Hi, it would be nice to have option to set template globally instead of repeating in on every page. Something like that:

`Vue.use(Meta, { titleTemplate: ‘mysite | %s’});’`

If needed, this global option can be overriden  by templateTitle returned from component head() method.

**Comment by pimlie** [comment]
Thanks for the suggestions, but I dont think we will implement this.

You only have to set the `titleTemplate` once in a component which stays active, eg if you use Nuxt set it once in your `nuxt.config` and you can forget about it in the components.

If you are not using Nuxt you can mimic the same behaviour with the `vm.$meta().addApp` feature which will be introduced in `v2.3` and which you can already test in the beta.

**Comment by georgyfarniev** [comment]
@pimlie thanks for quick reply. I just missed out that I can specify title in nuxt.config.ts, thank you for poiting me out. It solves my use case, closing this one.
