### ISSUE TITLE
Generate mode, changes inline script

### ISSUE THREAD

**Issue by aihsanm** [nuxt/vue-meta#457]
Basically, Im using Nuxt 2.9.2, and trying to using innerHTML method to inline a Google Optimize script, but whenever i run npm run generate, the code transforms certain aspects even though __dangerouslyDisableSanitizers is whitelisting innerHTML..

This is my Script in Nuxt Config head object 
  ```js
 script: [
      {
        innerHTML: `(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;})(window,document.documentElement,'async-hide','dataLayer', 500 , ${JSON.stringify(
          { [process.env.GOOGLE_OPTIMIZE_ID]: true }
        )})`
      }
    ],
    __dangerouslyDisableSanitizers: ['innerHTML']
  },
```
Which renders out as the below,  tried multiple different ways. could not get it to inline as expected
```js
  !function(e,n,t,a,c,s,d){n.className+=" "+t,s.start=1*new Date,s.end=d=function(){n.className=n.className.replace(RegExp(" ?"+t),"")},(e[a]=e[a]||[]).hide=s,setTimeout(function(){d(),s.end=null},500),s.timeout=500}(window,document.documentElement,"async-hide","dataLayer",0,{"GTM-XXXXXX":!0})
```
should be 
```js
(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;})(window,document.documentElement,'async-hide','dataLayer', 500 , {'GTM-XXXXXX': true })
```

**Comment by pimlie** [comment]
Please use __dangerouslyDisableSanitizersByTagID, it gives much better control which tag to disable the sanitizer for. 

Because you include the script with innerHTML, the code will be minimized by terser, thats why it looks different. If you dont want that add that code as an external script instead. But is there a problem with the minimized code?

**Comment by aihsanm** [comment]
@pimlie  that does not work. it changes the code to this, the problem i have with the code it changes the 500 to 0 i can live with the change of true to !0 but the 500 i need as the number it gets set to in order for google Optimize to work. 
(function (a,s,y,n,c,h,i,d,e){s.className+=&#x27; &#x27;+y;h.start=1*new Date;h.end=i=function(){s.className=s.className.replace(RegExp(&#x27; ?&#x27;+y),&#x27;&#x27;)};(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;})(window,document.documentElement,&#x27;async-hide&#x27;,&#x27;dataLayer&#x27;,500,{&#x27;GTM-WSMN65K&#x27;:true})
```

**Comment by pimlie** [comment]
I dont see the 500 being converted to a 0? Could you please highlight the exact parts which are wrong according to you?
