### ISSUE TITLE
Cannot read property '_t' of null

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/vue-meta#458]
Hi,
I have errors when using vue-i18n inside vue-meta using nuxt.
Should this be working correctly ?
this.$t is always defined in the head() function, but sometime this.$i18n is not defined and this.$t calls this.i18n. 
Seems to only occur on the client-side.
The error never occurs on the server-side.

Exemple code:
```js
head() {
    console.log('t', this.$t);
    console.log('i18n', this.$i18n);
    return {
        title: this.$t('home'),
    }
}
```
![Capture d’écran, le 2019-09-26 à 14 53 43](https://user-images.githubusercontent.com/17392251/65716598-7a55a100-e06d-11e9-85bb-a42343b91e5f.png)

![Capture d’écran, le 2019-09-26 à 14 50 39](https://user-images.githubusercontent.com/17392251/65716462-2d71ca80-e06d-11e9-87f1-1e958cef190c.png)

**Comment by pimlie** [comment]
Maybe it would be better if you'd report this on the nuxt-i18n repo?

**Comment by pimlie** [comment]
@mrleblanc101 Do you maybe have a follow-up on this? Were you able to fix this?

**Comment by mrleblanc101** [comment]
No :/

**Comment by pimlie** [comment]
Can you make a reproduction please?

**Comment by mrleblanc101** [comment]
Updating nuxt-i18n to version 6 fixed the issue even though nothing seems mentioned about that in the changelog

**Comment by pimlie** [comment]
@mrleblanc101 to prevent issues like this i can highly recommend the [`npm-check-updates`](https://www.npmjs.com/package/npm-check-updates) package. You can install it globally and then you only have to run `ncu` to see all possible updates or `ncu -u` to apply those updates to your package.json

If you use a lerna monorepo you can run `yarn lerna exec "ncu"` to run the command in each package
