### ISSUE TITLE
Instagram in-app browser doesn't support the dynamic title change

### ISSUE THREAD

**Issue by byang-codebrick** [nuxt/vue-meta#460]
If my site is linked in the Instagram profile as a website, Instagram opens an internal window (in-app browser) and fetches the initial title tag to show it on the top of the in-app window.

My site is using Vue-meta and it changes the document title on initial load. However, it seems that Instagram doesn't update title after it's initial fetching.

![Untitled](https://user-images.githubusercontent.com/52553532/65847932-a4190b80-e37e-11e9-88ed-9d2b82b7815a.png)

**Comment by pimlie** [comment]
Please share instructions on how to reproduce this and which vue-meta version you are using.

vue-meta v1.x uses rAF by default and v2.x uses setTimeout. Please try and see if you can get it working with one of those versions.

**Comment by byang-codebrick** [comment]
Currently, we're using `v2.2.1`but I'll try v1.x

**Comment by byang-codebrick** [comment]
Reproduction steps:
1. Give a default <title> in index.html (ex: <title>DEFAULT TITLE</title>)
2. Using vue-meta, change the title inside the `metaInfo()` (ex: {'title': 'SOMETHING ELSE'}
3. Set the site in your instagram's profile as your website
4. Open the website link in instagram iOS app
5. The title of the document is still `DEFAULT TITLE`

**Comment by pimlie** [comment]
Please make sure to use `v2.2.2`, see the pinned issue about a memory leak

I'm not sure how to debug this, it's probably a ios limitation somewhere but no idea how to find that out in a 3rd party app.

**Comment by pi0** [comment]
@pimlie Can you confirm final status of this issue?

**Comment by pimlie** [comment]
As mentioned, no idea how I can begin to debug an issue like this in a third party app. Also dont have access to an ios device. Im fine with leaving this issue open for some time, maybe somebody else comes along who has more insights in how to debug this.
