### ISSUE TITLE
vue-meta is not waiting for nuxtServerInit or asyncData

### ISSUE THREAD

**Issue by citananda** [nuxt/vue-meta#462]
First thanks for this great module !

I am trying to define meta tags depending on API response, but it seems that the vue-meta is not waiting for the reponse of the API.
I tried 2 cases:

1. Fetch data from nuxtServerInit and use it in the head() section of the page
To do some test go to this url: https://i9et5.sse.codesandbox.io/?theme=1

2. Fetch data from the asyncData and use it in the head() section of the same page
To do some test go to this url: https://i9et5.sse.codesandbox.io/?theme=2

I created a sandbox here: https://codesandbox.io/s/codesandbox-nuxt-i9et5

Does anybody knows how to make vue-meta to wait for api response?

**Comment by pimlie** [comment]
@citananda Did you find the cause of this?

**Comment by citananda** [comment]
After some tests, it is working in my sandbox, so I have no problem ;)

**Comment by citananda** [comment]
@pimlie After some tests, it is working in my sandbox, so I have no problem ;)
