### ISSUE TITLE
JSON.parse issue in 2.3.0-beta.0

### ISSUE THREAD

**Issue by matthieusieben** [nuxt/vue-meta#464]
In a Nuxt.js layout, I have the following `head()` function:
```js
head() {
  return {
    htmlAttrs: { aaa: 'bar', lang: this.$store.state.locale },
  }
}
```

The following line causes an error:
https://github.com/nuxt/vue-meta/commit/d9b0ab29da25bb55f2a4f2afa491e1afc0c5c0f3#diff-cba0880c28dd98835c4c104cb1467d57R17

It seems that the vueMeta attribute is not a JSON string but rather a comma separated list.

<img width="466" alt="Capture d’écran 2019-10-03 à 11 48 35" src="https://user-images.githubusercontent.com/813661/66116899-d2435900-e5d3-11e9-9c51-4b7e3c1a01f2.png">

**Comment by pimlie** [comment]
Hmm interesting, the comma separated list is the old syntax (pre v2.3). This has been converted to a json string to support setting attributes from multiple apps.

Could it be you are mixing v2.2 and v2.3 somehow? Do you have a reproduction?

**Comment by matthieusieben** [comment]
I have no idea how i got there. I tried to reproduce and there was no error anymore...
