### ISSUE TITLE
debounceWait is not working as expected in universal mode

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt/vue-meta#468]
**Version:** 2.3.0

**How to recreate:**
Add 
```
head() {
      this.$meta().setOptions({debounceWait: 50})
    },
```
into layouts/default.vue

**Result:**
All meta info is undefined. Page meta is not updated on router change.

Removing `debounceWait` fixes an issue

**Comment by pimlie** [comment]
The head function is not really the place to change options, better to do that in a created hook or something like that.

**Comment by AndrewBogdanovTSS** [comment]
@pimlie strange, as far as I remember, you've been recommending to do this in head()

**Comment by pimlie** [comment]
But still it shouldnt error out, there seems to be a regression now when you dont return anything in head/metaInfo

**Comment by AndrewBogdanovTSS** [comment]
I see...the fact that I used head() without returning anything caused an override of the internal components head() data, right?

**Comment by pimlie** [comment]
no, the issue is that vue-meta returns only when the result is not an object but that also means child components wont be traversed. 

Have a fix ready, just trying to add a test for it now

**Comment by AndrewBogdanovTSS** [comment]
@pimlie so it would be safe to set options in head() after this PR? 
Do you recommend to still set them in `created` hook or it's better to be done in `head` ?

**Comment by pimlie** [comment]
Changing options should be done outside of the metaInfo / head function. That is specifically meant for collecting meta info and can be called many times during the lifecycle of a Vue app.
