### ISSUE TITLE
Document json option

### ISSUE THREAD

**Issue by manniL** [nuxt/vue-meta#470]
The json option from https://github.com/nuxt/vue-meta/pull/415 has to be documented, ideally with a structured data example.

**Comment by quaj** [comment]
is that we need make document for #415?

**Comment by manniL** [comment]
@quaj yes!

**Comment by marcelxpfeifer** [comment]
This has been resolved?

**Comment by pimlie** [comment]
Nope, not yet :)

**Comment by marcelxpfeifer** [comment]
Didn't you put it in with #416

**Comment by pimlie** [comment]
Ah yes, but the prop is not yet listed under Special metainfo properties: https://vue-meta.nuxtjs.org/api/#special-metainfo-attributes

**Comment by marcelxpfeifer** [comment]
Alright working on it
