### ISSUE TITLE
Get the current meta of the page ?

### ISSUE THREAD

**Issue by Xationch** [nuxt/vue-meta#471]
Actually I need to make a refresh for get the current meta informations like title, titleChunk,... like this

```javascript
this.$meta().refresh().title
```

It's not possible to get this informations without refresh ?

**Comment by pimlie** [comment]
By default vue-meta doesn't keep the latest state indeed, but you could easily implement something like that using the [`changed`](https://vue-meta.nuxtjs.org/api/#changed) callback

**Comment by Xationch** [comment]
Perfect thx
