### ISSUE TITLE
mistake in docs vue-meta/docs/faq/chaining.md

### ISSUE THREAD

**Issue by neonVoice** [nuxt/vue-meta#488]
vue-meta/docs/faq/chaining.md

Since v2.1 you can add a callback attribute to your metaInfo **proerties** which you can use to chain loading.

proerties -> properties

**Comment by manniL** [comment]
PR welcome :relaxed:

**Comment by neonVoice** [comment]
can i close issue or should i link to commit first ?
https://github.com/nuxt/vue-meta/pull/489

**Comment by manniL** [comment]
Linking it in the PR is the key (I've edited that)
