### ISSUE TITLE
The metaInfo property 'base' does not render <base> tag

### ISSUE THREAD

**Issue by gwest4** [nuxt/vue-meta#490]
The [`base`](https://vue-meta.nuxtjs.org/api/#base) metaInfo property doesn't render a `<base>` tag.

I'm using [Nuxt.js](https://nuxtjs.org/api/pages-head), so this is the relevant portion of my `nuxt.config.js`.

```js
module.exports = {
  head () {
    return {
      base: { target: '_blank', href: 'http://www.mysite.com' }
    }
  }
  // ...
}
```

The result is no `<base>` in the `<head>`.

![image](https://user-images.githubusercontent.com/11031514/69355997-5d41e680-0c48-11ea-9666-ff1a4c3b8f5f.png)

**Nuxt.js:** 2.8.1
**vue-meta:** 1.6.0

**Comment by gwest4** [comment]
Did some poking around in the Nuxt.js docs. Maybe this issue has something to do with [`router.base `](https://nuxtjs.org/api/configuration-router#base) overriding the behavior of vue-meta?

**Comment by pimlie** [comment]
Indeed, Nuxt.js doesnt allow you to set the base through head. Or better worded, it [doesnt use](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/ssr.js#L105) that base property to set the base tag in the head.

**Comment by gwest4** [comment]
Okay, sounds like this isn't up to vue-meta to resolve. Thanks!

**Comment by radames** [comment]
here is a quick workaround, add this to your mounted method inside the page you want want all links target changed.

```js
  mounted () {
    const base = document.createElement('base')
    base.setAttribute('target', '_blank')
    document.head.appendChild(base)
  },
```

**Comment by gwest4** [comment]
@radames, thanks for the workaround, but it only works client-side. I need the `<base>` to be correctly rendered server-side since the website relies on a service that only reads the initial HTML response.

**Comment by radames** [comment]
@gwest4 good point, that workaround is definitely client side. it seems like nuxtjs ssr render is override that property, specially if you're using the router 

https://github.com/nuxt/nuxt.js/blob/1936de6930e65bc9e20c221212c8c9f2a0cab806/packages/vue-renderer/src/renderers/ssr.js#L128-L131

**Comment by og-neth** [comment]
Did anyone find a solution for this? It's kind of ridiculous that the router.base overrides this, you can't even make a simple deployment of a static site in a sub directory without some hack for static assets... ridiculous...

**Comment by pimlie** [comment]
There really isnt a fix within vue-meta's domain possible for this. Its really up to Nuxt.js to provide this functionality. You should create an issue in the Nuxt.js repo to request this

**Comment by og-neth** [comment]
I'm just going to drop my images for this build into the assets folder, I take my comment back, looks like I should've been using this instead of the static folder.

**Comment by og-neth** [comment]
Actually that was a bad idea... wow... simple image paths have become over engineered due to fancy shmancy module loading and building... wow...

**Comment by pimlie** [comment]
@og-neth Dude, please loose the attitude and check our [CODE of CONDUCT](https://github.com/nuxt/nuxt.js/blob/dev/CODE_OF_CONDUCT.md). There are a lot of reasons why things work like they work, in a project like Nuxt.js we just cant optimize for every use-case so we have to make choices. You still have many options, some being easier then others. Use an ENV var on every static image, hook into Vue-compiler to add this prefix for src/href tags, write a webpack plugin to fix these paths. There are many road to Rome, just don't complain here sarcastically that for your specific use-case you cant take the shortest route.

That said, Nuxt.js is an open-source project so if you have a suggestion how we can improve the project (while not loosing functionality/flexibility) please create an issue with your suggestion and explain in detail why your suggestion would be better then the current approach. We would be more than happy to implement your suggestion if its really an improvement.

**Comment by og-neth** [comment]
@pimlie Hey man, I didn't say anything that was insulting or derogatory, but if it offended you then I apologize. I'm simply stating that loading images, regardless of the caching or inlining of a file to base-64 benefits, seems to have evolved into a complicated task. I mean they are just resource links, this was solved back in the 90s, that's all I'm saying, and I think it's a fair statement.

**Comment by pimlie** [comment]
@og-neth Hmm, is your issue about setting a base tag or about loading images? If its the latter it seems out of scope of this issue. Feel free to create a separate issue with a code example on eg codesandbox of what you are trying to do and maybe I can help you find the best solution

**Comment by og-neth** [comment]
@pimlie it's with both, the `<base href="" />` solves the issue and allows me to use the static assets of my nuxt app within in a sub-directory of a bigger website where I have deployed the nuxt app. I just did a work around right now (manual intervention on the server). But will have to  look at a long term solution, seems `metaInfo { base }` is not adding the base tag at all when I configure it in my `nuxt.config.js`. I am using `nuxt@2.10.2` at the moment.

**Comment by og-neth** [comment]
@pimlie I also have `router { base } ` configured which solved the issues with the js files under the `_nuxt/` directory after `npm run build`. I disabled that and still didn't get the `<base href="" /` in my head as I was hoping.

**Comment by pimlie** [comment]
Its not totally clear to me what you are trying to do. You have a website and use Nuxt.js only on a sub-path? Eg only the path `/nuxt-project` is serving your Nuxt website? But static images needs to be loaded from `/` while Nuxt build assets need to be loaded from `/nuxt-project/_nuxt` ?
