### ISSUE TITLE
Breaks if setting up using dynamic import

### ISSUE THREAD

**Issue by mhluska** [nuxt/vue-meta#491]
It would be nice if I could set up the library like so:

```
import('vue-meta').then(lib => Vue.use(lib.default));
```

It seems to break unless using a regular static import. By break I mean the top level `metaInfo()` in `App.vue` doesn't get called. 

Most other libraries work fine when imported this way.

**Comment by pimlie** [comment]
Could you give more info about your env, eg are you using webpack which makes dynamic imports a separate chunk that needs to be downloaded?

If your app is created/instantiated before the vue-meta plugin has finished loading then the issue you are experiencing is expected unfortunately
