### ISSUE TITLE
FaceBook not detecting the vue meta properties

### ISSUE THREAD

**Issue by FreddyCrugger** [nuxt/vue-meta#492]
Hello,

I am using Vue and not Nuxt with Vue Meta.

If you have a spa, does vue meta works with facebook? at the moment whatever I do with your plugin, FaceBook wont detect any of the properties:
                    {property: 'fb:app_id', content: ""},
                    {property: 'og:title', content: this.title},
                    {property: 'og:site_name', content: this.$store.state.homepage_title},
                    {property: 'og:type', content: 'article'},
                    {property: 'og:url', content: document.URL},
                    {property: 'og:image', content: this.getImagePath + this.image},
                    {property: 'og:description', content: this.seo_description},

I can see them using the chrome tool, I don't get it.

Thank you

**Comment by pimlie** [comment]
Hey, I'm afraid not. This is the main reason why [Vue SSR](https://ssr.vuejs.org/) was created. Nuxt.js is just one of the frameworks utilizing that.

Also, although you see them in the chrome tool you will probably not see them if you do a real view-source. The collapsable tree in the chrome inspector is runtime code, not the bare server response (view-source should be).

**Comment by benjick** [comment]
Can it be done with `nuxt generate`?

**Comment by manniL** [comment]
@benjick if you use universal mode and not SPA, sure.

**Comment by sushmitabajgain** [comment]
> Hello,
> 
> I am using Vue and not Nuxt with Vue Meta.
> 
> If you have a spa, does vue meta works with facebook? at the moment whatever I do with your plugin, FaceBook wont detect any of the properties:
> {property: 'fb:app_id', content: ""},
> {property: 'og:title', content: this.title},
> {property: 'og:site_name', content: this.$store.state.homepage_title},
> {property: 'og:type', content: 'article'},
> {property: 'og:url', content: document.URL},
> {property: 'og:image', content: this.getImagePath + this.image},
> {property: 'og:description', content: this.seo_description},
> 
> I can see them using the chrome tool, I don't get it.
> 
> 

@Benoit1980 
Did you find any solution? I am facing same issue.

**Comment by josoye24** [comment]
Same issue, any solution?
