### ISSUE TITLE
Does vue meta work in the vuetify project?

### ISSUE THREAD

**Issue by positivethinking639** [nuxt/vue-meta#496]
I want to implement vue meta to  my vuetify project

is that possible and is it really useful for search engine optimization? I tried several ways. but when I right-click and select the source page view, the title and description don't change. I am pessimistic that this can work

**Update**

I had install it to my vuetify project

It works. The title bar is change. But if I click right on the mouse and select the source page view, the title and description don't change

**Comment by pimlie** [comment]
It is possible to use vue-meta with vuetify, mainly to a lot of work by @kevinmarrec who also maintains the vuetify nuxt module.

Not sure what the problem is you are describing, could you create a reproduction to show the issue?

**Comment by positivethinking639** [comment]
@pimlie Steps:

1. I had vuetify project
2. I install vue meta
3. It works. I see on every page, the title bar matches what I define
4. I tried right-clicking on my project vuetify and selecting the view page source to see the title page. Title page still uses the title page from public/index.php. it does not override the title page that we define on each page using vue-meta

**Comment by pimlie** [comment]
Im sorry but I have no experience with Vuetify so I cannot help you with that Im afraid. Feel free to ask on the vuetify repository
