### ISSUE TITLE
Attribute output error on html element

### ISSUE THREAD

**Issue by oemueller** [nuxt/vue-meta#499]
My config: 

`
htmlAttrs: {
    lang: 'de'
  },
`

Gets rendered on page like this: 

`<html data-n-head="%7B%22lang%22:%7B%22ssr%22:%22de%22%7D%7D" lang="de">`

I came across `encodeURI(JSON.stringify(data))` in some places in the vue-meta code- so maybe this is related? 
Or is there anything wrong with my config? 

I'm using vue-meta within a Nuxt project

**Comment by romukey** [comment]
the same thing happens in my project as well.

**Comment by pimlie** [comment]
Nope, just as its meant to be. The json string is added to track which app added which attribute on the tag.
