### ISSUE TITLE
Nuxt. 

### ISSUE THREAD

**Issue by sowinski** [nuxt/vue-meta#501]
How can I add something to the head programmatically?

I use Nuxt and I want to add something on serverside within a middlware to the head. Is this possible?

This was my first try: https://stackoverflow.com/questions/59300315/nuxt-how-to-add-content-scripts-to-the-head-dynamically-on-server-side

**Comment by pimlie** [comment]
See the response in your Nuxt issue: https://github.com/nuxt/nuxt.js/issues/6786 :)
