### ISSUE TITLE
How to wait until  all data loaded in SPA?

### ISSUE THREAD

**Issue by BonBonSlick** [nuxt/vue-meta#504]
The issue is when the method is parsed
```

metaInfo () {
      return {
        title:         this.postTitle, // dynamic, need to wait when data is available
        titleTemplate: `%s - ${this.siteTitle}`, 
        meta:          [
                         {
                           description: this.description, // dynamic, need to wait when data is available
                         },
                       ]
```

We try to access dynamic data which is loaded with async promise ajax request. As a result, there are many errors when a user visits the first time page, as data is not cached yet. The page is broken.

Is there any way to wait while data is loading and then trigger the parsing metaInfo() method? Or there are else better ways?

Also tried these
https://github.com/nuxt/vue-meta/blob/master/examples/vuex-async/views/Post.vue
https://github.com/nuxt/vue-meta/blob/master/examples/async-callback/app.js
```

    computed:   {
      ...mapGetters({
        currentEpisodeDetails:            'getter_path',
...
   metaInfo () {
      return {
        title: this.currentEpisodeDetails ?
 'Loading...' : this.currentEpisodeDetails.episode.name, // always false
        meta:  [
          {
            name:     'description',
            property: 'description',
            vmid:     'description',
            content: this.currentEpisodeDetails.description, 
// undefined even after data loaded to Vuex!
          },
        ],
```

store state
```

const state = () => (
  {
    entity:              { },
 // here can be any type of entity, fields are different, as a result no defult
    isLoadingInProgress: false,
  }
);
```

**Comment by BonBonSlick** [comment]
Tried also do this way
`        title: this.isLoadingInProgress ? 'Loading...' : this.currentEpisodeDetails.episode.name,
`

Error anyway

>  Cannot read property 'name' of undefined

**Comment by BonBonSlick** [comment]
Default data is required, eg

```
const state = () => (
  {
    entity:              {
      episode:     {
        name:        ''', // without this, error thrown
      },
    },
    isLoadingInProgress: false,
  }
);
```

Have to add more modules 1 per entity. EG video, user, comments etc, that is a lot to write and test :(

**Comment by pimlie** [comment]
Hi, the default data shouldnt be required when you would explicitly use Vue.set / this.$set when adding a new prop. See: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by BonBonSlick** [comment]
@pimlie thanks, not tested that approach yet.
