### ISSUE TITLE
how can I order links and scripts into head

### ISSUE THREAD

**Issue by saqueib** [nuxt/vue-meta#505]
I have a nuxt project which has some `scripts` and `links` injected from component and some of them are coming from `global css` from nuxt.config.js.

I want to know is it possible to control the order of script and css links added on the final head html. Its overriding some css because of the order both links are injected into head.

**Comment by pimlie** [comment]
Unfortunately this is not possible, new tags are always appended to the head. You can make use of [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) to make sure that earlier css is still preferred above later css.

**Comment by saqueib** [comment]
So it's appends any new links as it creates the component. Please consider adding some order key in object so it's possible to do the sorting.

**Comment by pimlie** [comment]
We probably wont any ordering. Relying on style ordering to determine how your page looks like doesnt sound like good practice to me.

**Comment by saqueib** [comment]
problem is my css is overriding cdn css. what will happen for scripts, if I want to append something at end of the head?

**Comment by pimlie** [comment]
Can you give an example of the class definitions from your cdn css and what you use in your own css?

**Comment by gustawdaniel** [comment]
This should not be closed. I experienced the sam error. My code:

```
  head: {
    script: [
      { src: 'assets/js/jquery.min.js' },
      { src: 'assets/js/bootstrap.min.js' },
```


Error in console:

```
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
```

**Comment by OzanKurt** [comment]
Any updates?

**Comment by Djenkaa** [comment]
I also have problem with this, cuz it append new script into head when i change page

**Comment by evguu** [comment]
This is still a problem!

**Comment by professorhaseeb** [comment]
I was able to solve this issue using `key` param like this
```js
{
    "script": [
        {
            "key": "01.some_script"
        },
        {
            "key": "02.another_scrip"
        }
    ]
}
```
