### ISSUE TITLE
Impossible to use mixins ?

### ISSUE THREAD

**Issue by leoclipet** [nuxt/vue-meta#506]
I'm trying to use mixins to be able to share that code in every component.

// metaInfo mixin

```
export default {
  metaInfo() {
    return {
      title: 'test',
      meta: [
        { vmid: 'description', name: 'description', content: this.description },
      ],
    };
  },
};

```

When using the mixin in each component, it does not take into account the metaInfo. Is there a workaround ?

**Comment by pimlie** [comment]
Not sure why thats not working for you, when i add the following mixin to the vue-router example the `og:title` meta tag is added so it should work:
```js
Vue.mixin({
  metaInfo() {
    return {
      meta: [
        { name: 'og:title', content: 'tittltltlte' }
      ]
    }
  }
})
```

**Comment by leoclipet** [comment]
I tried again and it is indeed working... Sorry about that.
