### ISSUE TITLE
Bad build?

### ISSUE THREAD

**Issue by dsanders11** [nuxt/vue-meta#507]
It seems like the build for `2.3.0` and `2.3.1`, and the current dist files in the repo, are missing the code for `serverInjector.extraData` in `dist/vue-meta.common.js` and `dist/vue-meta.esm.js`. If you build from master and do `git diff` you can see the difference.

Rebuilding `2.3.1` after copying over `package.json` from master seems to fix it. Perhaps there was a bug in Babel?

@pimlie, thoughts?

**Comment by pimlie** [comment]
Interesting, thanks for finding this. Seems a bug in a dependency indeed. When on the master branch and checking out tags/v2.3.0 without re-installing dependencies that `if` is indeed included in the build. But when re-installing the dependencies the `if` is indeed missing.

**Comment by pimlie** [comment]
Should be fixed in v2.3.2
