### ISSUE TITLE
How to hide auto-generated meta data from package.json?

### ISSUE THREAD

**Issue by yuonoda** [nuxt/vue-meta#510]
Hi there, 

I want to ask you about how to hide auto-generated metadata which comes from package.json. I'm using vue-meta:2.3.1 within nuxt.js. 

For example, vue-meta gets an author name from package.json and automatically write it to the head section. I want to hide this kind of information and manually set all meta-data.

Is it possible to hide them? 

Thak you.

**Comment by pimlie** [comment]
> vue-meta gets an author name from package.json and automatically write it to the head section

Thats you doing that right? Its not default behaviour of Nuxt or vue-meta to do that

It sounds its probably best to write your own abstraction and maybe not to rely on vue-meta. But normally child meta data should override parent meta data (with the same `hid`), except for this case: https://vue-meta.nuxtjs.org/guide/special.html

**Comment by steveDL** [comment]
I am seeing the same behaviour using the default nuxt cli project and it has auto-generated metadata which comes from package.json such as the description and author. Is there a way to prevent this?

**Comment by gerbenqikker** [comment]
This is still the case, it's also happening with the `name` key in package.json and its outputted as `og:title` if no other value is set by Nuxt (e.g. on a page without metadata). 

I simply removed the author key in package.json and that got rid of the author meta in the head, but for the `og:title` I havent found a solution yet.

**Comment by alejandroyunes** [comment]
I was able to remove the key name from the package.json with the titleTemplate below:

`app: {
  head: {
    htmlAttrs: { lang: 'es' },
    title: 'default title', 
    titleTemplate: '%s',
  },
}`
