### ISSUE TITLE
Uncaught ReferenceError: marked is not defined

### ISSUE THREAD

**Issue by panhaoyu** [nuxt/vue-meta#512]
Hello, I use CDN to import some third-party libs, and I used to put them in index.html, and it worked well. Then I want to use vue-meta, and I wrote such code:

```js
metaInfo() {
    return {
        title: this.data.title,
        script: [
            {src: 'https://cdn.bootcss.com/marked/0.7.0/marked.min.js', async: true, defer: true},
            {src: 'https://cdn.bootcss.com/highlight.js/9.15.10/highlight.min.js', async: true, defer: true},
        ]
    }
}
```

Now it raised an error at runtime: 
![image](https://user-images.githubusercontent.com/23495987/72694353-ab536780-3b6f-11ea-9662-6e94bb6fe225.png)

Here is my previous code:

```html
<...>
<div id="app"></div>
<script src="https://cdn.bootcss.com/vue/2.6.10/vue.runtime.min.js"></script>
<script src="https://cdn.bootcss.com/vuex/3.1.1/vuex.min.js"></script>
<script src="https://cdn.bootcss.com/vue-router/3.1.3/vue-router.min.js"></script>
<script src="https://unpkg.com/vue-meta@2.3.2/dist/vue-meta.min.js"></script>
<script src="https://cdn.bootcss.com/axios/0.19.0/axios.min.js"></script>
<script src="https://cdn.bootcss.com/marked/0.7.0/marked.min.js"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.10/highlight.min.js"></script>
</body>
</html>
```

Here is my config.

```js
//vue.config.js
module.exports = {
    configureWebpack: {
        externals: {
            'vue': 'Vue',
            'vue-router': 'VueRouter',
            'vue-meta': 'VueMeta',
            'marked': 'marked',
            'highlight.js': 'hljs',
            'vuex': 'Vuex',
            'axios': 'axios',
        }
    }
};
```

I'm new in frontend, so could you help me? If this is not a bug, I will import the libs in html, and I hope documentation could tell this bug. In the documentation, it imported `vue.js`, I don't think this is a correct case.

**Comment by pimlie** [comment]
Have a look at the [callback](https://vue-meta.nuxtjs.org/api/#callback) property. Add this to your marked script, then make you only use marked anywhere in your code until that callback has ran
