### ISSUE TITLE
Meta description not showing in Google

### ISSUE THREAD

**Issue by jacquesmatthieu** [nuxt/vue-meta#513]
Hello,
I've used your boiterplate into my project. 

When I make search with Google my meta description not appear.
<img width="710" alt="Capture d’écran 2020-01-15 à 09 12 49" src="https://user-images.githubusercontent.com/3845269/72416595-57174480-3777-11ea-8366-4cfb917c3e5e.png">

But when I inspect the DOM I can see the meta description, do you know what's the problem ?

```
<meta data-vue-meta="ssr" data-vmid="description" name="description" content="Calculez rapidement et facilement votre moyenne au bac général 2021 ! Saisissez les notes que vous connaissez déjà (bulletins scolaires, épreuves communes...). Le simulateur s’occupe du reste !">
 
```
My app is here => https://www.letudiant.fr/bac/simulateur-de-moyenne-au-bac/bac-general.html

**Comment by pimlie** [comment]
Hey, unfortunately the reasons why Google does this are not totally clear. If you search for this then you will see its a common occurence that Google decides to not use the meta description you've provided.

I dont have a link for you with any definitive information, but maybe this one is helpful: https://www.quora.com/Why-is-Google-not-showing-the-given-meta-description-under-the-search-result

**Comment by manniL** [comment]
Probably related to the new law in France. See https://www.seroundtable.com/google-french-search-results-snipets-28420.html

**Comment by jacquesmatthieu** [comment]
Thanks a lot
