### ISSUE TITLE
Accessing the Meta Info from a sibling component?

### ISSUE THREAD

**Issue by JayteeNZ** [nuxt/vue-meta#520]
Hi Everyone,

Apologies for posting this question here. I have a component that is a sibling to the `<router-view></router-view>` component.

The component is basically just a header, with includes the page title. I wanted to make use of the meta title, to populate the page title, since it's going to be the same in any case.

The problem I have is, navigating to a different page will of course update the document title and set the meta, but of course, I can't update my header component to include the new value.

Is there an easy way to accessing the current meta info? I've tried having a callback for the `afterNavigation`, and it did work, but wasn't ideal. I know I could access it with `document.title` and do a little string regex to get the value I need, but that also seems a little tedious too.

Is there an API method that I'm missing to which I could just do something like `this.$metaInfo.titleChunk` or `this.$metaInfo.title` within the header component to get the latest meta (for the current page that we have navigated to; not the metaInfo for the header component itself)?

The header component is part of the default layout, so it'll always be loaded.

Cheers.

**Comment by pimlie** [comment]
Hey, the only way to get the current information is to use the [`changed`](https://vue-meta.nuxtjs.org/api/#changed) property. It will be called everytime vue-meta is updating meta tags, so probably not every call will update the title
