### ISSUE TITLE
Setting og:description, og:title, twitter:description, twitter:title not working (Open Graph)

### ISSUE THREAD

**Issue by michaeljakob** [nuxt/vue-meta#526]
We're using the following code snippet in our Vue.js project (not Nuxt or gridsome installed). Dynamically updating `title` works great, but `og:description` won't update at all. Is this a known bug and how to solve it? 

```
metaInfo() {
    return {
      title: this.stockinfo.proper_name,
      htmlAttrs: {
        lang: "de",
        amp: true
      },
      meta: [
        { 'property': 'og:description', 'content': 'Wow', 'vmid': 'og:description'}
      ]
    }
  },
```

**Comment by manniL** [comment]
1. Please add a codesandbox/jsfiddle/similar reproduction repo
2. Be aware that the og tags are *not* used when sending link previews on SPA as they can't be detected w/o SSR.

**Comment by seekingtheoptimal** [comment]
this issue still exists, so at the moment vue-meta is actually only capable of changing the title tag only, all else is failing
