### ISSUE TITLE
Head function from nuxt.config.js is only considered on the first request

### ISSUE THREAD

**Issue by manniL** [nuxt/vue-meta#535]
Hey 👋🏻

First of all, sorry for the long title 🙈	

When defining a `head` function or object in the `nuxt.config.js`, it is only evaluated and taken into consideration on the first request / first page a user is visiting.

Reproduction: https://codesandbox.io/s/codesandboxnuxt-oqqsj

Steps:

1. Go to https://oqqsj.sse.codesandbox.io/
2. Open inspector -> see `tabindex="0"` on the body
3. Click the link to go to /about (it *has* to be the link, no manual input).
4. `tabindex="0"` is gone.

--

Originally reported by @codeofsumit

**Comment by pimlie** [comment]
The issue seems to be that `0` is a falsy value, if I use `tabIndex: 1` it keeps being listed. Working on a fix.
