### ISSUE TITLE
Set meta tags on SPA

### ISSUE THREAD

**Issue by natashagp** [nuxt/vue-meta#536]
Hi, i'm trying to set the headers of a blog page dynamically, but it's not working. 
I'm using Nuxt in mode SPA, I tried using in mode Universal with asyncData, an it partially worked, but crashed other parts of the site, so I'm trying again with SPA.
[https://github.com/nuxt/vue-meta/issues/532](url)

How do I make the head data wait until all data is loaded in my object post?

PS: if i don't use the meta tags, my object returns normally, but with the default meta tags used in my nuxt.config.js file
```js
data () {
    return {
      post: null
    }
  },
  created () {
    this.slug = this.$nuxt._route.params.slug
    if (this.slug === null || this.slug === '') {
      this.$router.push('/blog')
    } else {
      this.getPosts(this.slug).then((r) => {
        if (r.length && r.length === 0) {
          this.$router.push('/blog')
        } else {
          this.post = r[0]
        }
      })
    }
  },
  head () {
    const site = 'https://natashapaulon.netlify.com/'
      return {
        title: this.post.titulo + ' - Blog',
        meta: [
          { hid: 'description', name: 'description', content: this.post.descricao },
          { property: 'og:type', content: 'website' },
          { property: 'og:url', content: site + '/blog/' + this.post.slug },
          { property: 'og:title', content: this.post.titulo + ' - Blog' },
          { property: 'og:description', content: this.post.descricao },
          { property: 'og:image', content: site + this.post.imgDescricaoFileName },
          { property: 'og:image:secure_url', content: site + this.post.imgDescricaoFileName },
          { property: 'og:image:width', content: '187' },
          { property: 'og:image:height', content: '117' },
          { property: 'twitter:card', content: 'summary_large_image' },
          { property: 'twitter:url', content: site + '/blog/' + this.post.slug },
          { property: 'twitter:title', content: this.post.titulo + ' - Blog' },
          { property: 'twitter:description', content: this.post.descricao },
          { property: 'twitter:image', content: site + this.post.imgDescricaoFileName }
        ]
    }
  }
```

**Comment by pimlie** [comment]
Try to use `this.$set` to set post. By default Vue.js only shallow listens for changes, so it will be triggered when using `this.post` but not when using `this.post.descricao`. See https://vuejs.org/v2/guide/reactivity.html#For-Objects

- PS1: if you submit an issue on Github you can wrap code in  ``` to display it formattted and add the programming language after the opening ticks
- PS2: OpenGraph uses `property`, TwitterCard uses `name`. Just made the same mistake myself in a project ;)

**Comment by natashagp** [comment]
I tried using `this.$set` as you said, but it still doesn't show the meta tags on the page source code.
If i inspect the elements all the meta tags are shown correctly, but not on the source page.
I need the meta tags to show on source page so i can get a better SEO.
I've done a little bit of research, and one of the possible solutions is using the prerender-spa-plugin, but it's failing to prerender dynamic pages.
Do you have another suggestion that might help?

Also, thank you so much for helping me with this issue.

**Comment by pimlie** [comment]
If you need SEO then you shouldnt use `mode: 'spa'` in Nuxt.js, please use `universal` instead.

SPA stands for Single Page Application and that is exactly what will happen, there will only be one single html file that can show any of your routes. But the downside is it will only ever load on the client.
If you use universal mode then Nuxt.js will fully render the html for the specific route you are requesting. In production you can either run a Nuxt.js server or generate all the files for your routes. I would suggest to have a look at the [Nuxt docs](https://nuxtjs.org) to get a better understanding of the differences.

- Dont use _prerender-spa-plugin_ with Nuxt.js, its not needed at all. I might even go so far as to say just never use _prerender-spa-plugin_ at all because its mostly solving the wrong problem imo
- Please note that when running `nuxt generate` will always generate html files for each page/route in your project. The difference is that with mode: spa all these files will be exactly the same, but with mode: universal they will be different

**Comment by natashagp** [comment]
I changed the mode to universal like you said, and read the Nuxt docs, but i'm a little confused about the Nuxt.js server part.
Do I need to have another server (I already have a backend in PHP) just to render the pages, or does Nuxt already creates one for me automatically on production just for having the Universal mode?
If it's not too much to ask, could you show me an example of a server in Nuxt, please?

**Comment by pimlie** [comment]
Running a Nuxt server isnt a requirement, but you can do it if you need it. See this part of the docs: https://nuxtjs.org/guide/commands#server-side-rendered-deployment-universal-ssr-

But as mentioned you were looking into prerendered pages, this section is more suitable for you: https://nuxtjs.org/guide/commands#static-generated-deployment-pre-rendered-

With the last command you will get a folder with static html files you can upload to a webserver. If you are using dynamic routes, make sure to configure [`generate.routes`](https://nuxtjs.org/api/configuration-generate#routes) so Nuxt knows which dynamic routes exists so it can generate those for you. If you dont know these routes on before hand, or dont want to regenerate those html files anytime you write a new blog post you'd need to run a server instead. The server would always be able to check an api/db for the latest dynamic routes.

**Comment by natashagp** [comment]
I'm trying to use the Universal mode with the Serverless framework and AWS to deploy the server to render the pages.
But thank you for the help on everything.
