### ISSUE TITLE
Custom noscript

### ISSUE THREAD

**Issue by farhodhojiev** [nuxt/vue-meta#537]
Hello
I searched but could not find an answer.
I can set **noscript** like this.
`noscript: [{ innerHTML: 'This website requires JavaScript.' }]`
Is it possible set not only text, but with tags like.
`noscript: [{ innerHTML: '<strong>This website requires JavaScript.</strong>' }]`

**Comment by pimlie** [comment]
Possibly you need to disable sanitazion: https://vue-meta.nuxtjs.org/api/#dangerouslydisablesanitizersbytagid

**Comment by farhodhojiev** [comment]
```
noscript: [{
      innerHTML: "This website requires JavaScript.",
      body: true,
      vmid: 'test'
    }],
    __dangerouslyDisableSanitizersByTagID: {
      test: ['innerHTML']
    }
```
This not work ((

**Comment by pimlie** [comment]
Are you using Nuxt.js by any chance? Then you need to use `hid` not `vmid`

**Comment by farhodhojiev** [comment]
Dear @pimlie, thanks.
Yes I use Nuxt.js, and `hid` work fine.
