### ISSUE TITLE
Facebook not detecting the meta tags

### ISSUE THREAD

**Issue by writerity-jovica** [nuxt/vue-meta#545]
Missing Properties
The following required properties are missing: og:url, og:type, og:title, og:image, og:description

![image](https://user-images.githubusercontent.com/36668857/79645407-6b704080-81af-11ea-8123-842891eadab0.png)

Any help?

**Comment by pimlie** [comment]
`data-vue-meta="1"` indicates you are using a SPA? Check view-source in your browser to see if the html loaded from the server contains there props. If not or if you dont use a server/ssr then thats why ;)
