### ISSUE TITLE
vue-meta no longer renders tags

### ISSUE THREAD

**Issue by ejkelley** [nuxt/vue-meta#546]
My pages droped in Google this week.  I dug in and found that my meta tags (including title) are no longer in my pages.

Nothing has changed with my metaInfo() sections from the time it was working to now.

I have upgraded to Vue CLI 4.2.3 around the same time this issue started, but I'm not 100% this was the cause.

**Comment by ejkelley** [comment]
Rolled back my version of vue-meta to 2.3.3 and all is fine now.

**Comment by pimlie** [comment]
@ejkelley How do you mean rolled back? v2.3.3 is the latest version?

**Comment by ejkelley** [comment]
Uninstalled vue-meta from project then reinstalled.  I believe I was on v2.3.4 prior to removing and adding back in.
