### ISSUE TITLE
Is there way to manually call triggerUpdate with hook "destroyed" ?

### ISSUE THREAD

**Issue by towry** [nuxt/vue-meta#547]
`<f7-page>` is framework7 component represent a `page`. but if you have deep history, the page will not be destroyed.

I need to let `vue-meta` know that the component is destroyed even it is not so after navigate to next page(no metaInfo) the page title will be set to the default title(not the previous one).

**Comment by pimlie** [comment]
Im a little bit confused by your title, because after the lifecycle hook _destroyed_ is called then the page component should not exist anymore? 

If the component still exists in the virtual dom then atm I think the only thing you can do is to use a  metaInfo function and check yourself if the page is active or not. Vue-meta will always [walk the component tree](https://github.com/nuxt/vue-meta/blob/master/src/shared/getComponentOption.js) starting from $root to search for any active component that has metaInfo defined

**Comment by towry** [comment]
> If the component still exists in the virtual dom then atm I think the only thing you can do is to use a metaInfo function and check yourself if the page is active or not.

Thanks for the help. so how to use `a metainfo` function? which function/method to use?

**Comment by pimlie** [comment]
@towry Could you please share a simple reproduction of your code? It would help with suggesting the proper solution

**Comment by towry** [comment]
DEMO: https://jsfiddle.net/nolimits4web/jcwzqovz/

![Screen Shot 2020-04-26 at 6 47 38 PM](https://user-images.githubusercontent.com/8279858/80305368-e0b2c580-87ee-11ea-97e0-91e508700dde.png)


the `<f7-page>` component has its own event called `@page:afterin` and `@page:afterout`, but it have nothing to do with vue lifecycle. https://framework7.io/docs/page.html#page-events

**Comment by pimlie** [comment]
When in your demo I add vue-meta [v2.2.2](https://unpkg.com/vue-meta@2.2.2/dist/vue-meta.min.js) as resource (just noticed v2.3 doesnt auto load on the client) and change the page components to include a metaInfo function the title seems to be set just fine?

```js
// Init Page Components
Vue.component('page-about', {
  metaInfo() {
  	return {
      title: 'About'
    }
  },
  template: '#page-about'
});
Vue.component('page-form', {
  metaInfo() {
  	return {
      title: 'Form'
    }
  },
  template: '#page-form'
});
```

**Comment by towry** [comment]
https://jsfiddle.net/towry/v1djk9r8/8/

<img width="977" alt="截屏2020-04-26下午10 30 17" src="https://user-images.githubusercontent.com/8279858/80310529-c9370500-880d-11ea-8548-3ada5fcaa731.png">

<img width="1021" alt="截屏2020-04-26下午10 32 35" src="https://user-images.githubusercontent.com/8279858/80310544-d81db780-880d-11ea-9b94-8a3de96edab5.png">

In about page we can navigate to form page, so the about page will be previous page in history. and form page do not have metaInfo, the title will not change(the about page not destroyed), but it should be set to default title.

**Comment by pimlie** [comment]
Ah ok. Well, in the `metaInfo` fn you have access to `this`, so not sure how F7 tracks which page is active (Im assuming there is a better way then checking `page-current` class) but you should probably do something like:

```js
metaInfo() {
  if (!this.f7.isActivePage()) {
    return {}
  }

  return {
    title: 'about'
  }
}
```

**Comment by towry** [comment]
Thanks, I will try it.
