### ISSUE TITLE
Callback on Page Load not called in production mode

### ISSUE THREAD

**Issue by chrispreisler** [nuxt/vue-meta#549]
Hey guys,

I am not sure, if this is a bug, but when using vue-meta with Gridsome the Callback isn't called on page load in production mode. When navigating from another page to this page, it is working as expected. In dev mode it is also working as expected.

This is my code:

```
metaInfo() {
    return {
      script: [
        {
          vmid: "eventbrite",
          async: true,
          defer: true,
          src: "https://www.eventbrite.com/static/widgets/eb_widgets.js",
          callback: () => console.log("called")
        }
      ]
    };
  }
```

Thanks for your help in advance. 

Best regards
Chris

**Comment by pimlie** [comment]
Could you please add a reproduction on codesandbox?

**Comment by chrispreisler** [comment]
Hey @pimlie,

it is difficult to create a reproduction, because it happens only in production mode. So to reproduce this, you would have to build it.

Shall I create a example on Github, which you can clone?

Best regards
Chris

**Comment by pimlie** [comment]
Hey, thats why https://codesandbox.io/ is really cool. They allow you to create a minimal reproduction using eg a node server :)

**Comment by chrispreisler** [comment]
Hey,

ah I didn't know, that you can also deploy it directly to Vercel. I created the reproduction example for you. Now it even doesn't work in dev mode. But I can see in the Network tab, that the script is loaded. (https://www.dropbox.com/s/ifi4pyqor5ii25w/Vue%20Meta%20Callback%20Bug.png?dl=0)

https://codesandbox.io/s/busy-worker-rreob?file=/src/pages/Index.vue

Thanks again for looking into that.

Best regards
Chris

**Comment by pimlie** [comment]
Hey, thanks for the repro. The issue is that you need to use `key` and not `vmid`. The name `vmid` is the [default setting](https://vue-meta.nuxtjs.org/api/#tagidkeyname) for vue-meta, but Gridsome overrides that to [`key`](https://github.com/gridsome/gridsome/blob/master/gridsome/app/head.js#L9)

**Comment by chrispreisler** [comment]
Ah, thank you so much. Now I also found it in the [Gridsome Docs](https://gridsome.org/docs/head/#how-to-overwrite-from-child-component).
