### ISSUE TITLE
configure csp in metaInfo?

### ISSUE THREAD

**Issue by shocker18** [nuxt/vue-meta#552]
Hey, i have a question about the CSP, can i configure it with vue-meta?
I have this in my code
```
<script>
export default {
  metaInfo: {
    script: [
      {
        vmid: "hotjar",
        innerHTML: '(function(h, o, t, j, a, r) {
          if (window.location.hostname !== "localhost") {
            h.hj =
              h.hj ||
              function() {
                (h.hj.q = h.hj.q || []).push(arguments);
              };
            h._hjSettings = { hjid: process.env.VUE_APP_HOTJAR_ID, hjsv: 6 };
            a = o.getElementsByTagName("head")[0];
            r = o.createElement("script");
            r.async = 1;
            r.src = t + h._hjSettings.hjid + j + h._hjSettings.hjsv;
            a.appendChild(r);
          }
        })(window, document, "https://static.hotjar.com/c/hotjar-", ".js?sv=")'
      }
    ],
    __dangerouslyDisableSanitizersByTagID: {
      hotjar: ["innerHTML"]
    }
  }
};
</script>
```

and get this error in my console

```
Refused to load the script 'https://static.hotjar.com/c/hotjar-undefined.js?sv=6' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' data: blob: https://*.website.com". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by pimlie** [comment]
Did you try to add a meta tag as described on [mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)?

vue-meta doesnt provide any shortcuts at least to do this

**Comment by jdrydn** [comment]
@pimlie As seen in the error @shocker18 posted, there is a Content-Security-Policy in place:

```
default-src 'self' 'unsafe-inline' data: blob: https://*.website.com
```

@shocker18 [add Hotjar to your CSP directives](https://help.hotjar.com/hc/en-us/articles/115011640307-Content-Security-Policies). I'd advise against using `vue-meta` to add a [CSP meta tag](https://content-security-policy.com/examples/meta/) & would stick to a header. There also appears to be a [CSP Webpack plugin](https://medium.com/@minozhenko/content-security-policy-for-webpack-b4d1dd305feb) for single-page applications if that fits your use-case better.
