### ISSUE TITLE
SSR thoughts (Gridsome, Wordpress & Yoast)

### ISSUE THREAD

**Issue by VivianSolide** [nuxt/vue-meta#554]
Hi there,

I'm working on a website with Wordpress and Gridsome.
As you may know, [Yoast](https://yoast.com/) is a famous SEO Wordpress plugin.

Currently, it's not easy to fetch metadatas from Yoast.
Indeed, Yoast is injecting the full head inside the api response.

yoastHead:
```
<!-- This site is optimized with the Yoast SEO plugin v14.0.4 - https://yoast.com/wordpress/plugins/seo/ -->
<title>...</title>
<meta name="description" content="..." />
<meta name="robots" content="noindex, follow" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="article" />
<meta property="og:title" content="..." />
<meta property="og:description" content="..." />
<meta property="og:url" content=".../" />
<meta property="og:site_name" content="..." />
<meta property="article:modified_time" content="2020-04-28T08:04:56+00:00" />
<meta property="og:image" content="..." />
```

It could have been great to get a JSON response :/ 

First of all, is there a way to inject this markup from a component thanks to the  metaInfo() method?

I didn't find a quick way, so I converted the html into json in order to match with the metaInfo() method.

It works well, but I'm wondering how to properly SSR the whole stuff.
Gridsome is building those Yoast metadatas inside ```window.__INITIAL_STATE__```
Is it possible to generate the metadatas with the ```meta data-vue-tag``` format instead of ```window.__INITIAL_STATE__```?

**Comment by pimlie** [comment]
There is no way atm to direct use html tags with vue-meta, so you were right to convert them to json :)

Doesnt Gridsome also render the meta tags on SSR? Normally you shouldnt have to worry about  `window.__INITIAL_STATE__` as long as it gets not too big

**Comment by VivianSolide** [comment]
I found a way to properly add my tags inside the ````<head>````
```
// WordpressPost.vue
export default {
  components: {
    ...
  },
  data() {
    return {
      meta: [],
      title: null,
      ...
    };
  },
  metaInfo() {
    return {
      title: this.title,
      meta: this.meta
    };
  },
  created() {
    this.fetchMetaDatas();
  },
  methods: {
    fetchMetaDatas() {
      // fetch and convert metadatas
    }
  }
}
```
Thanks to the ````created()```` life cycle event, Gridsome is building as expected my markup!

**Comment by pimlie** [comment]
Just wondering, does this also work when building your website for production?

fetchMetaDatas seem to be an async method, how does Gridsome await that method before fully rendering? Because there is no reactivity during a SSR build?

**Comment by VivianSolide** [comment]
Yes, it works.
The build command writes a bunch of metadatas directly within the head.
```<meta data-vue-tag="ssr">```

fetchMetaDatas() isn't async.
Here is the workflow:
1. Getting the yoastHead within the GraphQL schema
2. Convert the HTML markup in JSON
3. Sanitize and assign this object to ```this.meta```

**Comment by sndrgb** [comment]
@VivianSolide can you please share your parser? How did you convert all yoast meta to a json?

**Comment by VivianSolide** [comment]
Sure!
```
import sanitize from "sanitize-html";
import html2json from "html2json";

export default {
  data() {
    return {
      converter: html2json,
      sanitize,
      meta: [],
      title: null,
      description: null
    };
  },
  metaInfo() {
    return {
      title: this.title,
      meta: this.meta
    };
  },
  created() {
    this.fetchMetaDatas();
  },
  methods: {
    fetchMetaDatas() {
      const cleanHtml = this.sanitize(this.$page.post.yoastHead, {
        allowedTags: false,
        allowedAttributes: false
      });
      const rawJson = this.converter.html2json(cleanHtml);
      this.title = rawJson.child
        .map(el => (el.tag === "title" ? el.child[0].text : null))
        .filter(el => el)[0];
      const metas = rawJson.child.filter(tag => tag.node === "element");
      const metasArray = metas.filter(m => m.tag === "meta").map(m => m.attr);
      let meta = [];
      for (let i = 0; i < metasArray.length; i++) {
        let obj = {
          name: "",
          content: "",
          key: ""
        };
        obj.name = metasArray[i].property
          ? metasArray[i].property
          : metasArray[i].name;
        obj.content =
          typeof metasArray[i].content === "string"
            ? metasArray[i].content
            : metasArray[i].content.join(" ");
        obj.key = metasArray[i].property
          ? metasArray[i].property
          : metasArray[i].name;
        meta.push(obj);
      }
      this.meta = meta;
    }
  }
};
```

Hope this helps.
