### ISSUE TITLE
Update meta for each component in SPA mode?

### ISSUE THREAD

**Issue by adnanmuttaleb** [nuxt/vue-meta#556]
I am building vue app as an _SPA_ (outside of _nuxt_, using _vue-cli_), and I want to set different  _og_ meta tags for different  components, is this possible?

**Note**: I know this is not seo friendly, but I had to do it.

**Comment by pimlie** [comment]
Yeah sure, that should be possible. Actually thats one of the major reason why vue-meta exists :)

**Comment by adnanmuttaleb** [comment]
I was asking because I tried to add `meta` or `title` for some components, but this did not work. For the root component I was able to change the `title` but I could not add any `meta` also.
