### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded at escape

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/vue-meta#570]
I have started to get the following error, when switching pages (e.g. from English to Danish):

```
vue-meta.esm.browser.js?2fd6:677 Uncaught RangeError: Maximum call stack size exceeded
    at escape (vue-meta.esm.browser.js?2fd6:677)
    at escape (vue-meta.esm.browser.js?2fd6:725)
    at escape (vue-meta.esm.browser.js?2fd6:725)
    at escape (vue-meta.esm.browser.js?2fd6:725)
    at escape (vue-meta.esm.browser.js?2fd6:725)
    at escape (vue-meta.esm.browser.js?2fd6:725)
    at escape (vue-meta.esm.browser.js?2fd6:725)
    at escape (vue-meta.esm.browser.js?2fd6:725)
    at escape (vue-meta.esm.browser.js?2fd6:725)
    at escape (vue-meta.esm.browser.js?2fd6:725)
```

Which seems to happen in this script:

![image](https://user-images.githubusercontent.com/3786627/83939840-49bf2d00-a7e0-11ea-84f7-5657807e7fc7.png)

And this:

![image](https://user-images.githubusercontent.com/3786627/83939850-59d70c80-a7e0-11ea-94c9-5cb69197184a.png)

I have tried debugging my head properties, but don't find anything unusual:

This is the HEAD properties in my layout file:

```
{
   "htmlAttrs":{
      "lang":"da_DK"
   },
   "meta":[
      {
         "hid":"ogdescription",
         "property":"og:description"
      },
      {
         "hid":"fbappid",
         "property":"fb:app_id",
         "content":"577387899514438"
      },
      {
         "hid":"ogsitename",
         "property":"og:site_name",
         "content":"My Site"
      },
      {
         "hid":"ogtype",
         "property":"og:type",
         "content":"product"
      },
      {
         "hid":"ogurl",
         "property":"og:url",
         "content":"http://localhost:3000/da"
      },
      {
         "hid":"twittercard",
         "name":"twitter:card",
         "content":"summary_large_image"
      },
      {
         "hid":"twitterdescription",
         "name":"twitter:description"
      },
      {
         "hid":"twittersite",
         "name":"twitter:site",
         "content":"@MyHandle"
      },
      {
         "hid":"twittercreator",
         "name":"twitter:creator",
         "content":"@MyHandle"
      },
      {
         "http-equiv":"x-dns-prefetch-control",
         "content":"on"
      },
      {
         "hid":"og:locale",
         "property":"og:locale",
         "content":"da_DK"
      },
      {
         "hid":"og:locale:alternate-en_US",
         "property":"og:locale:alternate",
         "content":"en_US"
      }
   ],
   "link":[
      {
         "rel":"canonical",
         "href":"http://localhost:3000/da?search=true"
      },
      {
         "rel":"dns-prefetch",
         "href":"//tracking.domain.com"
      },
      {
         "rel":"dns-prefetch",
         "href":"//www.google-analytics.com"
      },
      {
         "rel":"dns-prefetch",
         "href":"//connect.facebook.net"
      },
      {
         "rel":"dns-prefetch",
         "href":"//www.googletagmanager.com"
      },
      {
         "rel":"dns-prefetch",
         "href":"//widget.trustpilot.com"
      },
      {
         "rel":"dns-prefetch",
         "href":"//assets.domain.com"
      },
      {
         "rel":"dns-prefetch",
         "href":"//static.zdassets.com"
      },
      {
         "hid":"alternate-hreflang-en_US",
         "rel":"alternate",
         "href":"/?search=true",
         "hreflang":"en_US"
      },
      {
         "hid":"alternate-hreflang-da_DK",
         "rel":"alternate",
         "href":"/da?search=true",
         "hreflang":"da_DK"
      }
   ]
}

```

This is the HEAD properties in my page file:

```
{
   "title":"Skandinaviens foretrukne og største smykkeshop med eftertragtede smykkemærker",
   "script":[
      {

      }
   ],
   "link":[
      {

      }
   ]
}
```

I have tried removing both `head()` methods in both Layout and Page, but the error message still appears.

I am using nuxti18n-beta version, not sure if it is related.

**Comment by pimlie** [comment]
Does it still happen when you disable nuxt-i18n?

My first guess would be that you have a circular reference somewhere in your head data, but looking at the nuxt-i18n source it doesnt immediately become clear what it could be.

**Comment by simplenotezy** [comment]
Hmm - Interesting. All of a sudden I get a warning:

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: You may have an infinite update loop in watcher with expression "$metaInfo"

found in

---> <Hero>
```

In my Hero.vue app, I have head like so:

	head () {
		return {
			meta: [
				{
					hid: 'ogimage' + this.data.title,
					property: 'og:image',
					content: this.$handleImageSrc((this.data.image.sizes && this.data.image.sizes && this.data.image.sizes.large) ? this.data.image.sizes.large : this.data.image.src)
				},
				{
					hid: 'twitterimage',
					property: 'twitter:image',
					content: this.$handleImageSrc((this.data.image.sizes && this.data.image.sizes && this.data.image.sizes.large) ? this.data.image.sizes.large : this.data.image.src)
				}
			]
		};
	},

**Comment by pimlie** [comment]
You might be touching any of your `this.data.image` props within `handleImageSrc` so the Vue observer will trigger all computed components again. You will need to fix that

From the above code it would also be better to just call `this.$handleImageSrc` once. `head` is just a function, so calculate the image content before you return and use that var in your return statement

**Comment by simplenotezy** [comment]
Not sure if it is related though, if I remove it, the warning changes to:

vue.runtime.esm.js?2b0e:619 [Vue warn]: You may have an infinite update loop in a component render function.

So I believe the issue was with my specific $handleImageSrc function, where I was touching the store, hence the deletion of my previous post. I think the two cases are not linked.

found in

---> <Hero> at components/templates/FlexibleContent/partials/Hero.vue

**Comment by simplenotezy** [comment]
The issue is still happening by the way.

**Comment by daniluk4000** [comment]
2022, still happening with nuxt composition api.
