### ISSUE TITLE
meta tags not working as placed at bottom of head

### ISSUE THREAD

**Issue by gotters** [nuxt/vue-meta#571]
I generated all the meta tags and they were showing up as expected when viewing the page on the vue App.
However no systems were picking up the meta tags eg facebook developer and other scraping sites.

I noticed that they were being inserted into the head tag at the bottom after a whole bunch of css and js references. I removed them all and added them manually into index.html and now its working.

Is there a way to force vue-meta to place them at the TOP of the head tag before all the other head references. It seems to make a difference to the scraping engines!

**Comment by pimlie** [comment]
Are you using a vanilla Vue app or a framework? If vanilla, are you using SSR or not? If not, then you need to use SSR to make sure that all meta tags are rendered on the server. Having the meta tags already populated is one of the biggest reasons for using SSR ;)

**Comment by gotters** [comment]
using vue-material - not sure you call that a framework. and not using SSR

**Comment by pimlie** [comment]
Thanks, in that case please have a look at using SSR to make sure the html is fully rendered on the client for the current page with all meta tags already part of the head so now additional javascript is required on the client to view those.

**Comment by vana-dev** [comment]
same problem, tags shows on the bottom of <head> in nuxt ssr, facebook take all data propertly, but linkedin not

**Comment by oscarcb** [comment]
yeah, the same happens , is there any way to insert it before the css chunks?

**Comment by TheKvikk** [comment]
This issue is still present. All meta tags with hid attribute are inserted after a bunch of style tags. My question is the same: is there any way to insert it before the CSS chunks?

At my company we're building for server and client side, targeting static. We've made a component that accepts few props and changes head so that we can use it across all of our pages not being limited to only layouts. Can this be the cause of this problem?

**Comment by jcjp** [comment]
Have you guys found a solution or a temporary workaround for this issue?

**Comment by jun1orDev** [comment]
I'm also having the same problem, is anyone working on this?
