### ISSUE TITLE
Tags with any tag ID (vmid) get deleted when refreshing other apps

### ISSUE THREAD

**Issue by jangarcia** [nuxt/vue-meta#574]
When there are multiple Vue Meta apps with different app ids, refreshing the meta tags of one of those apps deletes any tags with a vmid attribute generated by one of the other apps and not included in the refreshed app, even if this vmid is completely unrelated to the refreshing app and has never been handled by it. 

From my point of view, this doesn't make any sense, given that multiple apps are supposed to work independently from each other except when explicitly sharing the same vmid for a tag. I suppose that this behaviour is in place to support use cases where it is the explicit intent of one app to delete a tag with a specific vmid. But I think this should be done explicitly then, for example by returning the tag with the `vmid` and `skip: true`.

**Comment by pimlie** [comment]
Could you please make a reproduction? This doesnt sound like it should behave indeed
