### ISSUE TITLE
I can't set the meta `http-equiv` in Typescript

### ISSUE THREAD

**Issue by Jordan-T** [nuxt/vue-meta#575]
In typescript, the meta `http-equiv` is not allowed:

```ts
{
  'http-equiv': 'X-UA-Compatible',
  content: 'IE=edge,chrome=1'
},
```

In the types, I found `MetaPropertyEquiv` with `httpEquiv`, so I fix with:

```ts
{
  httpEquiv: 'X-UA-Compatible',
  content: 'IE=edge,chrome=1'
},
```

If I use this, the result is `httpequiv`, not `http-equiv`:

```html
<meta data-n-head="1" httpequiv="X-UA-Compatible" content="IE=edge,chrome=1">
```

How to fix this issue in typescript?

**Comment by pimlie** [comment]
We might need to add the variant with a dash to the type. Its probably caused because Vue translates camel to kebab case but we dont do that

**Comment by brunomperes** [comment]
Any chance we can have a release including this fix ? :)

**Comment by sgurin** [comment]
Is any news about issue? Why it has been closed?
