### ISSUE TITLE
Open Graph embed not working with default Vue.js

### ISSUE THREAD

**Issue by Feuerhamster** [nuxt/vue-meta#582]
Hello.
I am using vue-meta in my default Vue.js application.
My data will be loaded asnychronously in the mounted() function.

Now I want an open graph embed on social media with the content thats beeing loaded.
But it did not work.

I've tested it with a web share debugger and on discord.

Here is the code I am using: 
```javascript
metaInfo () {
            return {
                title: this.poll.title,
                meta: [
                    { name: "og:title", content: this.poll.title },
                    { name: "og:image", content: window.location.origin + "/logo.png" },
                    { name: "og:description", content: this.poll.description },
                ]
            }
        }
```
When I open the site in my Browser and look into the inspector, the meta tags are there.

Can anyone help me and explain me why this is not working?

**Comment by szduda** [comment]
Rename `name` to `property`, according to the protocol spec that's the correct attribute.
