### ISSUE TITLE
My conditional meta are well defined in head but not read by socialmedia

### ISSUE THREAD

**Issue by Emilie-thp** [nuxt/vue-meta#591]
Hello everyone !

I'm using vue-meta in a child component with dynamic variables as below (1).

If I inspect the `<head>`, all my metadatas are in the right place with the right content - see below (2) ! But.... when I try to share my link on social media or even to test it with this kind of debugger https://metatags.io/, nothing is showing up.... The only metadata that is read by social media is the title of my entire website which is define in my index.html, as below (3).

**(1) My child component :** 
```    
metaInfo() {
      let translations = this.$i18n.messages[this.$i18n.locale].experience.share;
      return {
        title: translations.og_title,
        meta: [
          // Primary Meta Tags
          { name: 'title', content: translations.og_title },
          { name: 'description', content: this.experience.description },
          // Open Graph / Facebook
          { property: 'og:type', content: translations.og_type },
          { property: 'og:url', content: this.baseUrl + this.experience.public_token },
          { property: 'og:title', content: translations.og_title },
          { property: 'og:description', content: this.experience.description },
          { property: 'og:image', content: this.experience.picture_url },
          // Twitter
          { property: 'twitter:card', content: 'summary_large_image' },
          { property: 'twitter:url', content: this.baseUrl + this.experience.public_token },
          { property: 'twitter:title', content: translations.og_title },
          { property: 'twitter:description', content: this.experience.description },
          { property: 'twitter:image', content: this.experience.picture_url },
        ]
      };
    },
```
 
________

**(2) The resulting head balise**

Start
![Capture d’écran 2020-07-23 à 14 46 57](https://user-images.githubusercontent.com/55739570/88287994-6b726600-ccf3-11ea-9fbd-7a7c56a2258c.png)

End
![Capture d’écran 2020-07-23 à 14 41 31](https://user-images.githubusercontent.com/55739570/88287871-38c86d80-ccf3-11ea-834c-a7e55b288dbd.png)

________

**(3) This is where the title "[STAGING] Highday" comes from => see public/index.html :** 

```<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, viewport-fit=cover, user-scalable=no">
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
<html>
```

Thanks a lot for your help !

**Comment by aldarund** [comment]
Are you using SPA mode?

**Comment by Emilie-thp** [comment]
Single Page Application you mean ? No it's a Progressive Web App (PWA)

**Comment by aldarund** [comment]
https://nuxtjs.org/api/configuration-mode/ - what mode?

**Comment by Emilie-thp** [comment]
It the default mode, universal

**Comment by aldarund** [comment]
Than it should work. Do u have a link to website where it happens?

**Comment by Emilie-thp** [comment]
I'm not 100% sure if I can publicly share this website which is not mine. But I follow the instruction of this article to write my metaInfo() =>

**Comment by Emilie-thp** [comment]
I'm not 100% sure if I can publicly share this website which is not mine
But I followed the instruction of [this article](https://www.epiloge.com/how-to-add-dynamic-meta-tags-to-your-vuejs-app-for-google-seo-0fa058) to write my metaInfo() and I feel like that the link he gave as an example at the end of the article is dealing with exactly the same issue... => https://www.epiloge.com/@axel-wittmann

**This is what his metadata looks like in head balise** 

![Capture d’écran 2020-07-23 à 17 41 22](https://user-images.githubusercontent.com/55739570/88307721-93ba8e80-cd0c-11ea-8c1c-2d4acd24bc79.png)

**And this is what social media can effectively read**

![Capture d’écran 2020-07-23 à 17 43 01](https://user-images.githubusercontent.com/55739570/88307818-a765f500-cd0c-11ea-8f35-803d568de318.png)

**Comment by aldarund** [comment]
I actually missed that its vue meta repo. 
That example that you linked is SPA app. It don't have tags rendered into HTML, so they wont be visible like you want them too. The only way is too do SSR or rendering. Otherwise it wont work for social tools, because they just grab your HTML and look at tags, they don't do any js

**Comment by Emilie-thp** [comment]
ok, thank you very much for this conversation that made me realize that indeed my app is probably a SPA... I was trapped by the idea that the SPA is only one page but found this https://forum.vuejs.org/t/universal-vs-single-page-app/41176/3 and now I get the difference better ! Thankssss
