### ISSUE TITLE
How to get hid of the current route?

### ISSUE THREAD

**Issue by SandroMaglione** [nuxt/vue-meta#604]
Hi,
I am looking for a way to get the meta `hid` of the current route from the component/page code.

```js
export const head = {
  title: 'Page',
  meta: [
    {
      hid: 'page1',
    }
  ]
}
```
```js
computed: {
  getHid() {
    return ??? // How to get 'page1'?
  }
}
```

Is there an option to access the `hid` directly from the component's code?

**Comment by pimlie** [comment]
What are you trying to accomplish? There is no such thing as a `hid` of the current route, at least not for vue-meta?

You can keep track of the metaInfo thats currently displayed by adding a calback for https://vue-meta.nuxtjs.org/api/#changed, that callback will be called anytime the metaInfo is updated so you can search your hid in the returned metaInfo object

**Comment by SandroMaglione** [comment]
What I am trying to accomplish is to change the color of a menu item when a specific route is displayed.

Like when you click on a link on a menu and it becomes highlighted, signaling to the user in which page he is currently in.

My idea was to get the id of the route, and if it matches a specific page, then I would change the color of the link in the menu.

Is there a better way to accomplish that?

**Comment by pimlie** [comment]
@SandroMaglione Yes :)

Router-link (and thus nuxt-link) support a active & active-class prop you can use for this, see the vue-router docs: https://router.vuejs.org/api/#active-class

**Comment by SandroMaglione** [comment]
Thanks @pimlie 

That is exactly what I was looking for 👍
