### ISSUE TITLE
Dynamic meta tags work only locally

### ISSUE THREAD

**Issue by Mantavall** [nuxt/vue-meta#605]
Hi guys!
I have a website where I would like to have default meta tags for all pages and dynamic only for blog posts.
In `nuxt.config.js`:
![Screenshot 2020-08-29 at 08 49 06](https://user-images.githubusercontent.com/26999755/91629803-beb39480-e9d4-11ea-9988-f638e8ce805a.png)

and in my blog post `/_slug` I have this:
![Screenshot 2020-08-29 at 08 47 49](https://user-images.githubusercontent.com/26999755/91629810-cecb7400-e9d4-11ea-9892-d01b86efd1f8.png)

When I test it locally, default tags are overwritten by dynamic tags and works just fine. However, when I deploy to production, only default tags are visible.
dynamic title appears correctly in both local/production. 
I use `mode: universal`

Additionally see, that after a page reloads, dynamic meta tags are missing as well(even though I put them as simple strings for testing purposes, so no data to await).

Any wise ideas why this is happening?

**Comment by pimlie** [comment]
Could you please create a reproduction of this? Not sure where to start searching for this, the examples are working for me.

One thing tho as you mention _no data to await_. The head function cannot be async, the head function is in essence a computed prop on your Vue component which cant be async in Vue2. You need to handle async/awaits outside of head and make sure to use reactive properties so Vue knows to update the computed `head` prop once your data has been awaited.

**Comment by Mantavall** [comment]
Actually found that it was a part of bigger issue, not only related to dynamic meta tags but to dynamic content loading in general. As this is not related to vue-meta , I close this issue.

**Comment by RolandVerner** [comment]
> Actually found that it was a part of bigger issue, not only related to dynamic meta tags but to dynamic content loading in general. As this is not related to vue-meta , I close this issue.

Hello, can you give some feedback hove you fixed it. I have the same problem.

**Comment by dashty94** [comment]
Hi, I have a similar issue. Could you provide an update on this?
