### ISSUE TITLE
Raw script injection in the head (New Relic installation)

### ISSUE THREAD

**Issue by xabikos** [nuxt/vue-meta#606]
We are trying to install New Relic's [browser component](https://newrelic.com/products/browser-monitoring) in our server side rendering nuxt application. To enable this we need to add a `script` tag in the head of HTML document and before loading other scripts in order to measure and report accurate data about loading time etc.

When putting the content of the script in an external file in `static` folder and load it through `vue-meta` by doing 
```
 script: [ { src: '/scripts/newrelic.js' }],
```
everything works as expected but this is not the required way. We really need to have the script inside the HTML document as when loaded from external file timings won't be accurate.

So what we are doing is in `nuxt.config.js` we have the following configuration
```
head: {
    title: 'Website title',
    meta: [{ charset: 'utf-8' }, { name: 'viewport', content: 'width=device-width, initial-scale=1' }],
    script: [ { innerHTML: stagingNewRelicContent, type: 'text/javascript' }],
    __dangerouslyDisableSanitizers: ['script'],
  },
```
where `stagingNewRelicContent` holds the huge script that we got from new relic. The main problem is that when we load the page we get a syntax error despite the fact we have disabled sanitization.

More specifically somewhere in the script content there is the following code

```
var o=null,i=null,a=/Version\/(\S+)\s+Safari/;if(navigator.userAgent){var c=navigator.userAgent,s=c.match(a);
```
but when looking inside the generated script tag in html's head section it has been changed to 
```
var o=null,i=null,a=/Version/(S+)s+Safari/;if(navigator.userAgent){var c=navigator.userAgent,s=c.match(a);
```
So there is a missing backslash after `Version` before `S` and `s`. Any idea why this is happening and how we could fix it?

**Comment by pimlie** [comment]
This is probably because the static head data is serialized & written by Nuxt to `.nuxt/index.js`. Could you maybe try to double escape your input?
