### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by pidogc** [nuxt/vue-meta#608]
![image](https://user-images.githubusercontent.com/42857270/92546464-75024f80-f207-11ea-8d0b-6f06140a0483.png)
not use nxut.js

**Comment by pimlie** [comment]
Please add a reproduction of the issue

**Comment by Xin-Ru** [comment]
i have the same problem with my vue cli project.

**Comment by manniL** [comment]
> i have the same problem with my vue cli project.

Same applies here, please add a minimal reproduction.
