### ISSUE TITLE
Meta tags are missing in Page Source but visible at the bottom of head section when I inspect the page

### ISSUE THREAD

**Issue by deepakavvari** [nuxt/vue-meta#610]
Hi,
I used vue-meta to insert meta tags into several pages of my app. When I try to inspect the page, I can see the meta tags at the very bottom of the head element after a bunch of style and script tags. But these meta tags are missing in the page source.

The meta tags are dynamic and distinct to each page. We get the meta tags content data from the backend through axios calls and store them in vue-store.

Google doesn't seem to recognize these meta tags because when I google the website, it just shows the site URL without any description in the search results. I also added a 'google-site-verification' meta tag with it's key but google is not recognizing it, because google is throwing an error when trying to connect Google Console to the site

Framework: Express.js v4.17.1

In Home.vue I have:
`export default {
  metaInfo() {
    return {
      meta: [
        {
          name: "description",
          content: this.metaDescription ? this.metaDescription : ''
        },
        {
          name: "keywords",
          content: this.metaKeywords ? this.metaKeywords : []
        }
      ]
    };
  },
};`

Using vue-meta@2.3.1 via yarn

**Comment by manniL** [comment]
Do you use server-side rendering?

**Comment by deepakavvari** [comment]
@manniL No we don't use SSR.

**Comment by manniL** [comment]
> @manniL No we don't use SSR.

That's normal then I'm afraid. Because Vue is generating HTML through JS (when not server-side rendered), Google won't pick up the tags. You could either switch to pre-rendering your site (or at least your app shell) or to full SSR.

**Comment by deepakavvari** [comment]
> That's normal then I'm afraid. Because Vue is generating HTML through JS (when not server-side rendered), Google won't pick up the tags. You could either switch to pre-rendering your site (or at least your app shell) or to full SSR.
 
Is there any other way to add dynamic meta tags that Google can pick up instead of SSR? Maybe a completely different package instead of vue-meta? Any suggestions?

**Comment by manniL** [comment]
Unfortunately no. This is not related to the vue-meta package but to how SPAs work.

What you can do for the google site verification though is adding it to your base HTML document (e.g. `public/index.html`.

**Comment by StirStudios** [comment]
We are experiencing the same issue however we are using Nuxt in SSR mode.

**Package json**
`"vue-meta": "^2.4.0"
"nuxt": "^2.14.5"`

**Nuxt Config**
`ssr: 'true'`

`
<script>
import PageHolder from "@/assets/components/Page";

export default {
  components: {
    Page,
  },
  data() {
    return {
      data: {},
      isLoading: false,
      isPageLoaded: false,
      pageType: null,
      metaItems: {
        site: "website",
        title: "Latest News | website",
        description:
          "Default description",
        coverImage:
          "https://cdn.website.com/files/logo.png",
      },
    };
  },
  async mounted() {
    window.scrollTo(0, 0);
    this.isLoading = true;
    const path = this.$route.path;
    await this.$axios
        .get(process.env.CMS_SERVER_DOMAIN + "/api/news/all")
        .then(async (response) => {
          const pageItem = response.data.filter((x) => x.link === path);
          if (
            pageItem != undefined &&
            pageItem.length > 0 &&
            pageItem[0].hasOwnProperty("nid")
          ) {
            const nid = pageItem[0].nid;
            await this.$axios
                .get(process.env.CMS_SERVER_DOMAIN + "/api/news/" + nid)
                .then((pageResponse) => {
                  this.pageType = false;
                  this.data = pageResponse.data[0];
                });
          }
        });
    this.isLoading = false;
    this.isPageLoaded = true;
  },
  metaInfo() {
    return {
      title:
        this.pageType == false ?
          this.data.title + " | News | " + this.metaItems.site :
          this.metaItems.site,
      meta: [
        {
          hid: "description",
          name: "description",
          content: this.data.seo_description,
        },
        {
          hid: "image",
          name: "image",
          content: this.data.seo_image,
        },
        {
          hid: "og:title",
          name: "og:title",
          content:
            this.pageType == false ?
              this.data.title + " | News" :
              this.metaItems.site,
        },
        {
          hid: "og:url",
          name: "og:url",
          content: "https://www.website.com" + this.data.link,
        },
        {
          hid: "og:image",
          name: "og:image",
          content: this.data.seo_image,
        },
        {
          hid: "og:description",
          name: "og:description",
          content: this.data.seo_description,
        },
        {
          hid: "twitter:card",
          name: "twitter:card",
          content: "summary",
        },
        {
          hid: "twitter:site",
          name: "twitter:site",
          content: this.metaItems.site,
        },
        {
          hid: "twitter:title",
          name: "twitter:title",
          content:
            this.pageType == false ?
              this.data.title + " | " + this.metaItems.site :
              this.metaItems.site,
        },
        {
          hid: "twitter:description",
          name: "twitter:description",
          content: this.data.seo_description,
        },
        {
          hid: "twitter:url",
          name: "twitter:url",
          content: "https://www.website.com" + this.data.link,
        },
        {
          hid: "twitter:creator",
          name: "twitter:creator",
          content: "@website",
        },
        {
          hid: "twitter:image",
          name: "twitter:image",
          content: this.data.seo_image,
        },
      ],
      link: [
        {
          rel: "canonical",
          href: "https://www.website.com" + this.data.link,
        },
      ],
    };
  },
};
</script>
`

Any help would be greatly appreciated!

**Comment by pimlie** [comment]
@StirStudios Small tip, you can use tripple backticks to add code in a code block on github

If you are using nuxt should be using the [`head`](https://nuxtjs.org/api/pages-head/) method, so I am actually a bit surprised you are getting any headers at all! ;)

Also:
- mounted only runs on the client not on the server, see https://ssr.vuejs.org/guide/universal.html#component-lifecycle-hooks
- Vue doesnt await the mounted hook, if you need to await it (to make sure the data from your api call is available before rendering the page) you need to use Nuxt's asyncData fn instead
- Because of the former, i would advise against using `async mounted`. Instead add an async component method `async loadNews()` and in mounted just call this method (without awaiting it, cause that doesnt have any use)
- Why do you use both async/await as thenables? Eg you can just do `const response = await this.$axios` and skip the then's
- Your two api calls are super inefficient, if you can you should fix your api so you only need to do one call

Hope this helps :)

**Comment by StirStudios** [comment]
@pimlie this was very helpful indeed.

With Nuxt we are using vue-meta so that is why we can use metaInfo() and it works throughout the site, but it fails to work on anything that requires an API call. I am also aware the API needs some review but the aim at this point is to get the data into metaInfo() so it renders correctly into the source.

With that said I followed your suggestions and the page loads as it did before but we still get undefined :(

So now we have the following:

```
mounted() {
    window.scrollTo(0, 0);
    this.loadNews();
  },
  methods: {
    async loadNews() {
      this.isLoading = true;
      const path = this.$route.path;
      await this.$axios
          .get(process.env.CMS_SERVER_DOMAIN + '/api/news/all')
          .then(async (response) => {
            const pageItem = response.data.filter((x) => x.link === path);
            if (
              pageItem != undefined &&
              pageItem.length > 0 &&
              pageItem[0].hasOwnProperty('nid')
            ) {
              const nid = pageItem[0].nid;
              await this.$axios
                  .get(process.env.CMS_SERVER_DOMAIN + '/api/news/' + nid)
                  .then((pageResponse) => {
                    this.pageType = false;
                    this.data = pageResponse.data[0];
                  });
            }
          });
      this.isLoading = false;
      this.isPageLoaded = true;
    },
  },
```

In theory this should have done the trick or am I still missing something?

**Comment by pimlie** [comment]
Yes and no, you are probably experiencing a Vue Change Detection caveat: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

A quick solution for this would be to do `this.$set(this, 'data', pageResponse.data[0])` to make sure that all the properties of the data object are responsive. Currently Vue isnt aware of that so it never recomputed the head function

To make sure, if you are using nuxt you need to make sure to use the `head` function, _not_ metaInfo.

**Comment by StirStudios** [comment]
Ah geez you are extremely helpful I just don't understand the logic enough. Where would I add

```this.$set(this, 'data', pageResponse.data[0])```

```js
<script>
import Page from "@/assets/components/Page";

export default {
  components: {
    Page,
  },
  data() {
    return {
      data: {},
      isLoading: false,
      isPageLoaded: false,
      pageType: null,
      metaItems: {
        site: "website",
        title: "Latest News | website",
        description:
          "Default description",
        coverImage:
          "https://cdn.website.com/files/logo.png",
      },
    };
  },
  mounted() {
    window.scrollTo(0, 0);
    this.loadNews();
  },
  methods: {
    async loadNews() {
      this.isLoading = true;
      const path = this.$route.path;
      await this.$axios
          .get(process.env.CMS_SERVER_DOMAIN + '/api/news/all')
          .then(async (response) => {
            const pageItem = response.data.filter((x) => x.link === path);
            if (
              pageItem != undefined &&
              pageItem.length > 0 &&
              pageItem[0].hasOwnProperty('nid')
            ) {
              const nid = pageItem[0].nid;
              await this.$axios
                  .get(process.env.CMS_SERVER_DOMAIN + '/api/news/' + nid)
                  .then((pageResponse) => {
                    this.pageType = false;
                    this.data = pageResponse.data[0];
                  });
            }
          });
      this.isLoading = false;
      this.isPageLoaded = true;
    },
  },
  metaInfo() {
    return {
      title:
        this.pageType == false ?
          this.data.title + " | News | " + this.metaItems.site :
          this.metaItems.site,
      meta: [
        {
          hid: "description",
          name: "description",
          content: this.data.seo_description,
        },
        {
          hid: "image",
          name: "image",
          content: this.data.seo_image,
        },
        {
          hid: "og:title",
          name: "og:title",
          content:
            this.pageType == false ?
              this.data.title + " | News" :
              this.metaItems.site,
        },
        {
          hid: "og:url",
          name: "og:url",
          content: "https://www.website.com" + this.data.link,
        },
        {
          hid: "og:image",
          name: "og:image",
          content: this.data.seo_image,
        },
        {
          hid: "og:description",
          name: "og:description",
          content: this.data.seo_description,
        },
        {
          hid: "twitter:card",
          name: "twitter:card",
          content: "summary",
        },
        {
          hid: "twitter:site",
          name: "twitter:site",
          content: this.metaItems.site,
        },
        {
          hid: "twitter:title",
          name: "twitter:title",
          content:
            this.pageType == false ?
              this.data.title + " | " + this.metaItems.site :
              this.metaItems.site,
        },
        {
          hid: "twitter:description",
          name: "twitter:description",
          content: this.data.seo_description,
        },
        {
          hid: "twitter:url",
          name: "twitter:url",
          content: "https://www.website.com" + this.data.link,
        },
        {
          hid: "twitter:creator",
          name: "twitter:creator",
          content: "@website",
        },
        {
          hid: "twitter:image",
          name: "twitter:image",
          content: this.data.seo_image,
        },
      ],
      link: [
        {
          rel: "canonical",
          href: "https://www.website.com" + this.data.link,
        },
      ],
    };
  },
};
</script>
```

Also as soon as I switch metaInfo() -> head() none of the meta prints....

**Comment by pimlie** [comment]
Have editted your post and added a comment _PUT IT HERE_ on the line where you should add/replace it ;)

Did you install vue-meta manually in Nuxt.js? If so, then its now installed twice. Nuxt.js has support for vue-meta out of the box. If you have a module/plugin anywhere where you manually do `Vue.use(VueMeta)` then you need to _remove_ that. If you dont manage to resolve it please create a reproduction of your project that has the same issue

**Comment by StirStudios** [comment]
Okay so I am still running into the same issue but I have gone a step further back and done as you suggested by uninstalling vue-meta completely.

Now something very interesting has come about. With no head() the app loads perfectly fine (of course no meta tags) but then if I add head() the app crashes with the following:

Cannot read property 'text' of undefined

If I add back what we had before metaInfo() the tags render and the app works again. So as you said I think there is still something stuck in the app causing vue-meta to be lost.

I will keep researching.

**Comment by StirStudios** [comment]
So you were right we had a very odd setup: both vue and vue-meta were installed. It is makes complete sense why things were working and then breaking once I uninstalled vue-meta. So with that said we now only use head and no more vue/vue-meta.

Alas we still have the exact same result.... All is showing in the inspector head but not in the source and this only occurs with pulling from the API.

Would it be possible for you to review our project/git?

**Comment by StirStudios** [comment]
Good news on this one. Having resolved the first issue we were able to use asyncData and it works perfectly now. We will look at optimizing the API!
