### ISSUE TITLE
__dangerouslyDisableSanitizersByTagID on SSR getting escaped

### ISSUE THREAD

**Issue by ariona** [nuxt/vue-meta#613]
When navigating to page, the content of script does not escaped. But when reloading the page and getting the SSR version, the script content getting escaped.

Below is the setting i used:
```js
{
    script: [
      {
          vmid: 'testing',
          type: 'text/javascript',
          innerHTML: `alert("test");`
      }
    ],
    __dangerouslyDisableSanitizersByTagID: {
      'testing': ['innerHTML']
    },
};
```

And here is the result when the page is loaded from SSR, notice that the script content getting escaped
This from SSR, the script content getting escaped:
```html
<script data-n-head="ssr" vmid="testing" type="text/javascript">alert(&quot;test&quot;);</script>
```

**Comment by pimlie** [comment]
@ariona `data-n-head` suggests you are using Nuxt.js? If so then you need to use `hid` and not `vmid` as identifier. See the nuxt docs

**Comment by ariona** [comment]
Yes i am using nuxt, changing `vmid` to `hid` as suggested solve the issue.
