### ISSUE TITLE
Console logging still occurring with debug set to false

### ISSUE THREAD

**Issue by philiplindberg** [nuxt/vue-meta#615]
It seems like console logging is still occurring even though I have `debug` set to `false` (which is the default value). An easy way to reproduce the issue is to enable `pageTracking` - this will log `GTM` messages in the console even though `debug` disabled.

**Comment by pimlie** [comment]
Could you please add a repro? Dont think GTM messages have anything to do with vue-meta?

**Comment by philiplindberg** [comment]
Sorry, my bad, created this issue in the wrong repo... 🤦‍♂️
