### ISSUE TITLE
meta get duplicated

### ISSUE THREAD

**Issue by s8v** [nuxt/vue-meta#620]
App.vue
```
    metaInfo () {
        return {
            titleTemplate: '%s - ' + appName,
            title: 'App',
            meta: [
                {
                    hid: 'description',
                    name: 'description',
                    content: 'description'
                },
                {
                    hid: 'og:url',
                    property: 'og:url',
                    content: this.getPath()
                }
            ]
        }
    }
```
Index.vue
```
  metaInfo () {
        return {
            title: 'Index',
            meta: [
                {
                    hid: 'description',
                    name: 'description',
                    content: 'description'
                },
                {
                    hid: 'og:url',
                    property: 'og:url',
                    content: this.getPath()
                }
            ]
        }
    }
````

**Comment by pimlie** [comment]
Please use tripple backticks to make the code readable

Can you eloborate on your question? Have no idea what you are asking here, please create a reproduction that shows the issue

**Comment by s8v** [comment]
> Please use tripple backticks to make the code readable
> 
> Can you eloborate on your question? Have no idea what you are asking here, please create a reproduction that shows the issue

Yes, sorry. When I visit the index, the meta tags should be replaced, but it doesn't happen. They get duplicated, so I have the meta from app.vue and index.vue

**Comment by s8v** [comment]
> Please use tripple backticks to make the code readable
> 
> Can you eloborate on your question? Have no idea what you are asking here, please create a reproduction that shows the issue

I've solved it by using "vmid" instead of "hid".
