### ISSUE TITLE
Displays the wrong title when routes have a delayed transitions

### ISSUE THREAD

**Issue by ivodolenc** [nuxt/vue-meta#621]
Hi 👋, when routes have transitions with a certain delay (example fade 500 ms), the wrong title flashes for a second. Here’s a gif to better understand what I’m talking about.

<img src="https://user-images.githubusercontent.com/51852491/96445171-c0991780-120f-11eb-8d43-0fb1964cdcf5.gif" width="400" />

I’ve found some similar topics about this, but none have a direct answer to whether this is a bug or intentional behavior? And if it’s a bug, does anyone have any advice on how we can fix this?

Also, this only happens when I want to add a canonical link or something similar with the need for `this.$route.path`

```js
// layouts/default.vue

export default {
  head() {
    return {
      link: [
        {
          rel: 'canonical',
          // Flicker only appears when 'this.$route.path' is added
          // if 'this.$route.path' is removed, everything works fine
          href: 'http://localhost:5500' + this.$route.path,
        },
      ],
    }
  },
}
```

```css
/* global css */

.page-enter-active,
.page-leave-active {
  transition: opacity 0.5s;
}
.page-enter,
.page-leave-to {
  opacity: 0;
}
```

A temp fix would be to set the global title and titleTemplate to `null`, so that the fallback title is not displayed when changing the route.

```js
// nuxt.config.js

export default {
  head: {
    /*
     ** Corrects the page title when routes have a delayed transition
     ** features: { transitions: true }
     */
    title: null,
    titleTemplate: null,
  },
}
```

- `create nuxt app`
- `nuxt:` '2.14.7'
- `target:` 'static'

**Comment by pimlie** [comment]
vue-meta supports a config option [`refreshOnceOnNavigation`](https://vue-meta.nuxtjs.org/api/#refreshonceonnavigation) which was added to (try to) prevent this issue. You could also combine it with debounceWait to wait longer before updating the meta tags.

The root-issue is unfixable tho by vue-meta as it has to do how page transitions work in Nuxt unfortunately

**Comment by ivodolenc** [comment]
Thanks for the fast reply. I’ve tried these options as you suggested, but unfortunately they don’t work as expected.

```js
// nuxt.config.js

export default {
  vueMeta: {
    refreshOnceOnNavigation: true,
    debounceWait: 500,
  },
}
```
<img src="https://user-images.githubusercontent.com/51852491/96454184-cac11300-121b-11eb-95f0-23858f100429.gif" width="400" />

So the best "fix" for that issue is to set global title and titleTemplate to `null` and add titles manually so we can avoid fallback display?

```js
// nuxt.config.js

export default {
  head: {
    title: null,
    titleTemplate: null,
  },
}
```

**Comment by ivodolenc** [comment]
Ok, here’s my current solution. I tested this in `dev` and `prod` mode and it works pretty well.

Remove the global title from the `nuxt.config.js` file:

```js
// nuxt.config.js

export default {
  head: {
    // Remove the default global title and title template
    // When we change the route, the global title (fallback) will not be displayed
    title: null,
    titleTemplate: null,
  },

  // Define a custom global title, separator, and title template so we can easily combine this later in the pages
  // You can name these values as you wish
  publicRuntimeConfig: {
    title: {
      name: 'Nuxt',
      separator: ' - ',
      template: 'Awesome title',
    },
  },
}
```

And then in the `index.vue` page we can set the title like this:

```js
// index.vue

export default {
  head() {
    return {
      // This will output 'Nuxt - Awesome title'
      title:
        this.$config.title.name +
        this.$config.title.separator +
        this.$config.title.template,
    }
  },
}
```

```js
// about.vue

export default {
  head() {
    return {
      // If you want to change the title on other pages, simply combine it with the $config values or define new one
      title:
        'About page' +
        this.$config.title.separator +
        this.$config.title.template,
    }
  },
}
```
<img src="https://user-images.githubusercontent.com/51852491/96621553-08e83080-1309-11eb-9516-dff699019cf7.gif" width="400" />
