### ISSUE TITLE
Uncaught TypeError: Cannot set property '$meta' of undefined

### ISSUE THREAD

**Issue by anburocky3** [nuxt/vue-meta#628]
I followed the instruction mentioned in the documentation (https://vue-meta.nuxtjs.org/)

#### For your knowledge:
- I'm using Vue 3 

```
vue-meta.esm.js?58ca:1997 Uncaught TypeError: Cannot set property '$meta' of undefined
    at Object.install (vue-meta.esm.js?58ca:1997)
    at Object.use (runtime-core.esm-bundler.js?5c40:2911)
    at eval (main.js?56d7:12)
    at Module../src/main.js (app.js:1243)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.1 (app.js:1400)
    at __webpack_require__ (app.js:854)
    at checkDeferredModules (app.js:46)
    at app.js:994
install @ vue-meta.esm.js?58ca:1997
use @ runtime-core.esm-bundler.js?5c40:2911
eval @ main.js?56d7:12
./src/main.js @ app.js:1243
__webpack_require__ @ app.js:854
fn @ app.js:151
1 @ app.js:1400
__webpack_require__ @ app.js:854
checkDeferredModules @ app.js:46
(anonymous) @ app.js:994
(anonymous) @ app.js:997
```

### For more info
`main.js`
```js
import {
  createApp
} from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
import store from "./store";
import VueMeta from 'vue-meta'

createApp(App)
  .use(store)
  .use(router)
  .use(VueMeta)
  .mount("#app");
```

`App.vue`
```vue
<template class="antialiased">
  <Navbar />
  <div class="h-screen bg-gray-200">
    <router-view />
  </div>
</template>

<script>
import Navbar from "./components/Navbar";

export default {
  components: {
    Navbar,
  },
  metaInfo: {
    title: "My Example App",
    titleTemplate: "%s - Yay!",
    htmlAttrs: {
      lang: "en",
      amp: true,
    },
  },
};
</script>
```

**Comment by pimlie** [comment]
Unfortunately Vue3 is not supported yet, see #558

**Comment by anburocky3** [comment]
Are there any ETAs? becoz, since we are planning to use vue3 for our project, we can wait if it will be arriving in few weeks?

Any approximate ETA will be great to think so.?

**Comment by romain130492** [comment]
any news about thias? is vue3 supported?

**Comment by BastiaanRudolf** [comment]
I can also verify issue is still not resolved. Any idea if Vue3 will be supported in the future?

**Comment by alashraf1991** [comment]
is there is any alternatives to manage metadata in vue3 dynamically?

**Comment by elzodxon** [comment]
Is there any news about meta data for Vue3?

**Comment by innakonon** [comment]
> Is there any news about meta data for Vue3?

also interested

**Comment by dselivanovvv** [comment]
??? any updates?

**Comment by HoodieDan** [comment]
so weird how vue-meta is not supported in the latest version of VUE.

**Comment by BastiaanRudolf** [comment]
Since January 2021 chore(release): 3.0.0-alpha.0 was released. For Vue3 support please checkout the [next](https://github.com/nuxt/vue-meta/tree/next) branch. Latest version is [3.0.0-alpha.10](https://github.com/nuxt/vue-meta/commit/e9adc99bdc909d6daa5f0678f57f321a6ff2d6f6). (Vue3 support for vue-meta is considered in mostly-stable-alpha stage, please read the documentation)

**Comment by javokhirbekkhaydarov** [comment]
When will vue 3 support vue-meta

**Comment by ICS-Vortex** [comment]
Any updates?

**Comment by creig-with-an-E** [comment]
Any updates?
