### ISSUE TITLE
Understanding Content Templates

### ISSUE THREAD

**Issue by 1e4** [nuxt/vue-meta#634]
I've been reading the docs and am struggling to understand how [Content Templates](https://vue-meta.nuxtjs.org/api/#content-templates) work.

My App.vue

```
export default {
    metaInfo: {
        title: 'Home',
        titleTemplate: '%s - A Product Name',
        meta: [
            {
                property: 'og:title',
                content: 'Home',
                template: chunk => `${chunk} - A Product Name`,
                vmid: 'og:title'
            }
        ]
    }
}
```

And my About.vue

```
export default {
    name: 'About Us',
    metaInfo: {
        title: 'About',
        meta: [
            {
                property: 'og:title',
                content: '%s - test'
            }
        ]
    }
}
```

If i overwrite the 'vmid' then I can't see to use `%s` to get the template from the parent

How can I make it use the template from the `App.vue` for og:title? I've tried various vmid's such as `ogTitle` but none seem to work. The documentation seems very limited in explaining how to use content templates in child views, it would be great if there was an example of using Content Templates in child views alongside the setup as it shows currently.

Thanks in advance for any tips on approaching this

**Comment by pimlie** [comment]
@1e4 Its not the most user friendly solution but you could have a look at the tests. See https://github.com/nuxt/vue-meta/blob/e04ae64d6bfc671804e698d6d2edfcf473c53472/test/unit/getMetaInfo.test.js#L239 and downwards for various other options/methods for content templates

**Comment by 1e4** [comment]
> @1e4 Its not the most user friendly solution but you could have a look at the tests. See
> 
> https://github.com/nuxt/vue-meta/blob/e04ae64d6bfc671804e698d6d2edfcf473c53472/test/unit/getMetaInfo.test.js#L239
> and downwards for various other options/methods for content templates

I was trying to avoid using the `chunk` part on every page, and only needing to change the suffix once, going by the tests it doesn't look like it's possible?

**Comment by pimlie** [comment]
@manniL Could you please chime-in here?

**Comment by 1e4** [comment]
I realise it's Christmas and New Year now, but a bump just letting you know I haven't been able to solve this

**Comment by manniL** [comment]
> 
> 
> I realise it's Christmas and New Year now, but a bump just letting you know I haven't been able to solve this

Thanks for your patience! Had to dig in into my 3yo code 🙈 

According to https://github.com/nuxt/vue-meta/pull/248 it should work like that:

`Parent.vue`

```js
metaInfo: {
    meta: [
      {
        vmid: "og:title",
        property: "og:title",
        content: "Test title",
        template: chunk => `${chunk} - My page`
      }
    ]
  }
};
```

`Child.vue`

```js
metaInfo: {
    title: "Hello",
    meta: [
      {
        vmid: "og:title",
        property: "og:title",
        content: "An important title!"
      }
    ]
  }
```

Result: `An important title! - My page` (for og:title)

Working Example: https://codesandbox.io/s/038mp9vkov?file=/src/components/HelloWorld.vue

**Comment by 1e4** [comment]
> > I realise it's Christmas and New Year now, but a bump just letting you know I haven't been able to solve this
> 
> Thanks for your patience! Had to dig in into my 3yo code see_no_evil
> 
> According to #248 it should work like that:
> 
> `Parent.vue`
> 
> ```js
> metaInfo: {
>     meta: [
>       {
>         vmid: "og:title",
>         property: "og:title",
>         content: "Test title",
>         template: chunk => `${chunk} - My page`
>       }
>     ]
>   }
> };
> ```
> 
> `Child.vue`
> 
> ```js
> metaInfo: {
>     title: "Hello",
>     meta: [
>       {
>         vmid: "og:title",
>         property: "og:title",
>         content: "An important title!"
>       }
>     ]
>   }
> ```
> 
> Result: `An important title! - My page` (for og:title)
> 
> Working Example: https://codesandbox.io/s/038mp9vkov?file=/src/components/HelloWorld.vue

Thank you for replying, I have the same issue with what you posted, however, I removed `content` from `parent.vue` and it works fine. So it seems that if you have content and template in the `parent.vue` and `content` in the child, it won't correctly use the title. Can I assume this is a bug or is it working as intended?

**Comment by FRSgit** [comment]
Bump, seems like a bug. Can you please confirm, so we can start looking into possible solutions?

**Comment by FRSgit** [comment]
Hey!
I believe I've found out an issue which could've been described in this topic - it seems that meta content templates **aren't working when nested deeper than 1 level**. See the example:
https://codesandbox.io/s/vue-meta-with-template-example-forked-s1ubs?file=/src/components/OtherComponent.vue

`OtherComponent.vue` is within `HelloWorld.vue` which is loaded by `App.vue`. `App.vue` describes `og:title` content template and well, it's not being taken into account when `OtherComponent.vue` sets new meta content :<

**Comment by 1e4** [comment]
> Hey!
> I believe I've found out an issue which could've been described in this topic - it seems that meta content templates **aren't working when nested deeper than 1 level**. See the example:
> https://codesandbox.io/s/vue-meta-with-template-example-forked-s1ubs?file=/src/components/OtherComponent.vue
> 
> `OtherComponent.vue` is within `HelloWorld.vue` which is loaded by `App.vue`. `App.vue` describes `og:title` content template and well, it's not being taken into account when `OtherComponent.vue` sets new meta content :<

This is the same use case I am using, so I would guess that yes this is the problem, not sure if it's intended or a bug though. thanks for replying with a demo

**Comment by FRSgit** [comment]
@pimlie What do you think?
I need an approval that this it indeed a bug so I can start work on some fix

**Comment by FRSgit** [comment]
Bump

**Comment by manniL** [comment]
This indeed looks like a bug.

**Comment by doutatsu** [comment]
Been in the rabbit hole to fix this myself... Bug it is then 😂

**Comment by mgiraldo** [comment]
i guess #728 implies that `titleTemplate` nesting is still not possible... any idea if it is?

i'd like:

```
- page: title: 'my website'
  - sub-page: title: 'category | my website'
    - sub-sub-page: title: 'subcategory | category | my website'
```
