### ISSUE TITLE
Pass Nuxt context to metaInfo function

### ISSUE THREAD

**Issue by Koc** [nuxt/vue-meta#638]
Hi!

It would be nice to pass [context ](https://nuxtjs.org/docs/2.x/internals-glossary/context) object into `metaInfo` function. This can be useful at least for i18n, just compare

```js
data() {
    return {
        title: this.$t('checkout.page_title'),
    }
},
metaInfo() {
    return {
        title: this.title,
    };
},
```
vs
```js
metaInfo({ $t }) {
    return {
        title: $t('checkout.page_title'),
    };
},
```

**Comment by pimlie** [comment]
@Koc As @Atinux indicated you need to use `head` and not `metaInfo` if you are using Nuxt. As long as head is a function and not an object you can use `this` normally as the head function will be added as a computed property to your component.

This means that general Vue reactivity caveats apply, see eg here for an example what you have to watch out for (but this is a Vue caveat, not vue-meta as so much): https://vue-meta.nuxtjs.org/guide/caveats.html#reactive-variables-in-template-functions

**Comment by Koc** [comment]
Wow, it really works, thank you for suggestion!

```js
head() {
    const title = this.$t('checkout.page_title');

    return {
        title,
    };
},
```
