### ISSUE TITLE
why it is not possible to use vue meta in child component?

### ISSUE THREAD

**Issue by farhadkb6868** [nuxt/vue-meta#640]
Hi. I am using vue meta in a vue js project with vue router library.
I have designed a `CourseComponent`  that it is the child component in Root Component.
The problem is when I try to use `metaInfo` method the  title and meta data does not appear in web page

`export default{

        metaInfo: {

            title: 'xyz'

        },

}
`
But when I use the same code in Root component everything works correct.
It is important for me to use `metaInfo` method in child component. because I want to get title and meta data dynamically with ajax.
Any idea?

**Comment by pimlie** [comment]
With the limited information provided it doesnt seem you have wrong expectations, this should just work. So could you please add a repro so we can see how your code works?
