### ISSUE TITLE
titlechunk is defaulted to pwa.meta

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [nuxt/vue-meta#641]
In my nuxt.config.js. I have a conditional `titleTemplate` and `pwa` implemented like below:

```
export default {
    ....
    head: {
    titleTemplate: (titleChunk) => {
      return titleChunk
        ? `${titleChunk}_hello`
        : 'hello'
    },
    pwa: {
      meta: {
        name: 'pwaName',
        theme_color: '#fa3b3f'
      },
      manifest: {
        name: 'pwaName',
        background_color: '#fa3b3f'
      },
      workbox: {
        skipWaiting: true,
        clientsClaim: true
    }
  },
```

Then if I have a page: `pages/test.vue` where I did not set any title, the title will be `pwaName_hello` instead of just `hello`

**Comment by pimlie** [comment]
This is because nuxt/pwa adds the name as title. See here: https://github.com/nuxt-community/pwa-module/blob/master/src/meta.ts#L130
