### ISSUE TITLE
__dangerouslyDisableSanitizersByTagID does not work in Nuxt SSR

### ISSUE THREAD

**Issue by michaelpumo** [nuxt/vue-meta#642]
I am using the `__dangerouslyDisableSanitizersByTagID` option but it does not work on a hard refresh / static generation of the HTML from within Nuxt.js.

I did, however, notice it's working when navigating the pages of my site via the router (so client-side only it seems).

**Incorrect:** Viewing page source (browser view source and running `npm run generate`) I see something like:
`<script data-n-head="ssr" vmid="ldjson-schema" type="application/ld+json">
{&quot;@context&quot;:&quot;https://schema.org&quot;}
</script>`

**Correct:** ...navigating the site via Vue router I see (in Chrome dev tools):
`<script data-n-head="ssr" vmid="ldjson-schema" type="application/ld+json">
{"@context":"https://schema.org"}
</script>`

This certainly feels like a bug to me but I'd be happy to hear if I'm doing anything wrong. I was following the documentation:
https://vue-meta.nuxtjs.org/api/#dangerouslydisablesanitizersbytagid

```
head() {
  return {
    meta: metas, // Array of meta objects.
    script: scripts, // Array of script objects.
    __dangerouslyDisableSanitizersByTagID: {
      'ldjson-schema': ['innerHTML'], // Matches the ID I set in the script.
    }
  }
}
```

I'm not seeing any console errors in either terminal or the browser.

**Comment by rlalak** [comment]
I did it in the same way and I have the same problem.

**Comment by michaelpumo** [comment]
> I did it in the same way and I have the same problem.But then I found this: [nuxt/nuxt.js#241 (comment)](https://github.com/nuxt/nuxt.js/issues/241#issuecomment-363395895)
> 
> So, you have to use `hid` instedof `vmid` to set tag id.

You are absolutely correct! That worked perfectly.

I guess it's not a bug then but lacking in documentation?

Thank you so much for your reply.

**Comment by francisjr1997** [comment]
I get the following error when I use the code below:
 Error:
```
 vue.esm.js:1897 TypeError: metaOpts[key].forEach is not a function
    at loop (vue-meta-info.js:71)
    at Object.setMetaInfo (vue-meta-info.js:79)
    at updateMetaInfo (vue-meta-info.js:97)
    at VueComponent.<anonymous> (vue-meta-info.js:172)
    at Watcher.run (vue.esm.js:4571)
    at flushSchedulerQueue (vue.esm.js:4313)
    at Array.<anonymous> (vue.esm.js:1989)
    at flushCallbacks (vue.esm.js:1915)
```
 Code:
```
 metaInfo(){
     return {
         script: [{ hid: 'ldjson-schema', innerHTML:JSON.stringify(preparedJson), type: 'application/ld+json' }],
         __dangerouslyDisableSanitizersByTagID: {
         'ldjson-schema': ['innerHTML']
      },
 }
```
**I want to get rid of this console error** What are your thoughts?

**Comment by pimlie** [comment]
@francisjr1997 Please create your own issue with a clear reproduction. But the error trace says its in `vue-meta-info.js` line `71` which I dont think is part of the vue-meta lib
