### ISSUE TITLE
titleTemplate function and const not defined

### ISSUE THREAD

**Issue by emilsgulbis** [nuxt/vue-meta#643]
Trying to create reusable name const for app name, but

**nuxt.config.js**
```
export const name = 'My app name'

export default {
  head: {
    titleTemplate: (titleChunk) => {
      return titleChunk ? `${titleChunk} - ${name}` : name
    },
    ...
  },

 ...
}

```

throws `name is not defined`

**Comment by emilsgulbis** [comment]
Thanks!


With this approach we need to remove `head.title` otherwise it shows title as `My app name - My app name`
```
export const titleTemplate = new Function('c', `return c ? c + ' - ${name}' : '${name}'`)
```

**Comment by manniL** [comment]
Correct (at least for the index page) 😋

But feel free to adapt your custom function as you like 👍
