### ISSUE TITLE
afterNavigation() is not giving page title

### ISSUE THREAD

**Issue by LionelPaulus** [nuxt/vue-meta#644]
Hi,

I'm using the [afterNavigation()](https://vue-meta.nuxtjs.org/api/#afternavigation) callback to track my page views but the `metaInfo` object returned always contain the fallback title set in `nuxt.config.js` instead of the page title.

# Reproduce
https://codesandbox.io/s/kind-clarke-iivq5?file=/pages/index.vue

Page 1 title: `Page 1`
Page 2 title: `Page 2`
Title returned by `afterNavigation()`: `Nuxt.js starter for CSB` (check the console)

![image](https://user-images.githubusercontent.com/789782/104491051-fad94180-55d1-11eb-99a7-8b813825e013.png)

**Comment by pimlie** [comment]
Are you afterNavigation runs immediately after vue-router's afterEach hook. By default Nuxt wraps all pages in a transition, this means that when afterNavigation runs the transition to the next page could still be running and the metadata for the new page just hasnt been set yet.

You could try 2 options:
- set `features.transitions = false` in nux.config to disable transitions
- default transition takes 500ms i believe, so you could try to set a timeout of 500ms in afterNavigation to track your page after the transition has finished

**Comment by LionelPaulus** [comment]
Thank you @pimlie !
And is there a way to also run `afterNavigation()` on page load to be able to track the first page view?
Like the `router.afterEach()` callback.
