### ISSUE TITLE
Possibility for creating <links> client-side only

### ISSUE THREAD

**Issue by blaadje** [nuxt/vue-meta#648]
Hi !
using the head property to manage images pre-loading e.g
```js
head() {
  return {
    link: [
      {		
        rel: 'prefetch', // <- here
        href: 'myimage.svg',		
        as: 'image',		
      },		
      {		
        rel: 'preload', // <- here
        href: 'myimage.svg',		
        as: 'image',		
      },		
    ]
  }
}
 ```
 I'm currently having both `preload` & ` prefetch` for the same image to do browser fallback https://caniuse.com/?search=prefetch https://caniuse.com/?search=preload
 
I'd like instead to use a guard checking the browser and either render `prefetch` or `preload` (which can be done easily cc https://github.com/w3c/preload/issues/7#issuecomment-566791118), to avoid double requests.
 
However my issue is that i'm currently using **nuxt** which will use this code server-side and won't be able to check browser.

Is there any way to force this code te be used client-side, or any other alternative ?

**Comment by pimlie** [comment]
@blaadje You can use process.client in your head method to choose what to return?

```js
head() {
  if (process.client) {
    // in the browser
  } else {
    // on the server
  }
}
```
