### ISSUE TITLE
tags created by set of addApp will be disappeared after SPA page tanstition

### ISSUE THREAD

**Issue by ymmooot** [nuxt/vue-meta#652]
I have created a nuxt plugin using `$meta().addApp()`.
Tags created by `set` will be disappeared after SPA page tansition if the component has `head` method.

It is working right if the component does not have `head` method.
I thought the meta created by `set` of `addApp` would not be affected by other meta like `head`.

Is this a bug or is there something wrong with my code or approach?

(The plugin works well when removing these lines.)
https://github.com/ymmooot/nuxt-jsonld/blob/16f6e5bef4c1382bc9924c5a6f9f7381879c6eff/examples/basic/pages/index.vue#L19-L23

**Comment by pimlie** [comment]
@ymmooot Could you add a repro for how you use addApp? Not sure if its a bug or not atm

**Comment by ymmooot** [comment]
This branch ([ymmooot/nuxt-jsonld/tree/use-addApp/](https://github.com/ymmooot/nuxt-jsonld/tree/use-addApp/)) 's `/src/` and `/examples/basic/`show how I use addApp.
But I will prepare reprocude repository with codesandbox.
Please wait for it. 🙏

**Comment by ymmooot** [comment]
@pimlie 
This is a repro [codesandbox.io](https://codesandbox.io/s/distracted-black-y400w?file=/pages/index.vue).
Github repo is [here](https://github.com/ymmooot/vue-meta-issue-652).

I keep `set` method and use in each component to update a script tag.
But it will disapper when the component have `head` method.
