### ISSUE TITLE
Scripts with innerHTML property added client-side are not executed

### ISSUE THREAD

**Issue by klausXR** [nuxt/vue-meta#653]
I have a list of scripts that I would like to load, however, I want the application to stabilize first ( performance has the priority ), so I would like to add them client-side and not server-side. 

This is essentially what I would like to do and have the "Hello" log to the console.

```html
<template>
  <div class="container">
    <Nuxt />
  </div>
</template>

<script>
export default {
  data() {
    return {
      scripts: [],
    };
  },
  head() {
    return {
      script: this.scripts,
    };
  },
  mounted() {
    this.scripts.push({
      innerHTML: `console.log('Hello')`,
      hid: "hello",
    });
  },
};
</script>
```

This does not work, I would assume it is because of the way Vue Meta creates the scripts. The browser does not want to execute javascript that is part of an element's innerHTML property, if it is rendered client-side. 

However, if you create a new script tag and append it to the document, it does work. How can I work around this with this library?

Paste this into the browser console ( not the Github one, though )

```js
const script = document.createElement("script")
script.innerHTML = `console.log("Ready")`
document.body.appendChild(script)
```

**Comment by pimlie** [comment]
@klausXR Did you disable the sanitization of innerHTML in vue-meta? Otherwise the quotes will be escaped. See https://vue-meta.nuxtjs.org/api/#dangerouslydisablesanitizersbytagid

**Comment by klausXR** [comment]
@pimlie Yes, it is disabled. Special characters in HTML are showing not escaped, but the script does not execute.
