### ISSUE TITLE
Nuxt app - automatically change page title when left website tab

### ISSUE THREAD

**Issue by iFeras93** [nuxt/vue-meta#659]
Hello guy's

I am facing a problem with the page title part, when I open a page the title comes out correctly, but when I leave and return to the page tab, the title changes automatically.

**Comment by pimlie** [comment]
@iFeras93 Please add a reproduction of the issue you are experiencing

**Comment by iFeras93** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/6824682/112893651-9f542580-90e3-11eb-81df-00f8d30374d2.gif)

**Comment by iFeras93** [comment]
@pimlie the title changed automatically when navigation browser tabs

**Comment by iFeras93** [comment]
I used:
- nuxtServerInit to get some data from external endpoint
- used i18n module
- used middleware to check website language
- used loading layout when the data from external endpoint not completely come.

**Comment by pimlie** [comment]
@iFeras93 Thanks but thats not really a reproduction because I cannot check the code. Eg from that gif its not rly clear to me what happens, it seems if you click on about you are redirected back to index?
