### ISSUE TITLE
[v3] Cannot use library in a client-only app?

### ISSUE THREAD

**Issue by LeBenLeBen** [nuxt/vue-meta#662]
When I try to use vue-meta@next in a Vue 3 app without SSR (I’m using Vite), I get the following error:

```
node_modules/vue-meta/dist/vue-meta.esm-bundler.js:850:35: error: Could not resolve "@vue/server-renderer"
```

So I installed `@vue/server-renderer` thinking it would fix the issue, but then I get another error:

```
Uncaught TypeError: vue.ssrUtils is null
```

Am I doing something wrong or does the current version absolutely requires an SSR app to work properly?

**Comment by pimlie** [comment]
@LeBenLeBen Only the browser builds have SSR removed, all the other builds include ssr indeed.

Im not sure where that `vue.ssrUtils` comes from, will look into that and maybe optimizing the esm-bundler build. We could probably move the renderer import/require into the renderToString method

**Comment by Tribevote** [comment]
I had a similar issue. I added the below code in `vue.config.js` file and I was able to resolve the render error 

 `configureWebpack :
    {
        resolve: { mainFields: ['main', 'module'] }
    }`

**Comment by pimlie** [comment]
@Tribevote Thats an unexpected solution. Which Vue dist file are you using, also the esm-bundler?

**Comment by glen-84** [comment]
I'm also having problems trying to get this to work in a webpack 5 project. I am not wanting to use SSR.

```
WARNING in ../../node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js 96:63-70
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@vue/server-renderer/index.js 4:2-64
 @ ../../node_modules/vue-meta/dist/vue-meta.cjs.js 854:27-58
 @ ../../node_modules/ts-loader/index.js??clonedRuleSet-5.use[0]!../../node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./app/site/views/index.vue?vue&type=script&lang=ts 2:0-35 8:32-39
 @ ./app/site/views/index.vue?vue&type=script&lang=ts 1:0-207 1:0-207 1:208-404 1:208-404
 @ ./app/site/views/index.vue 2:0-56 3:0-51 3:0-51 4:0-13 6:15-21
 @ ./router.ts
 @ ./main.ts 3:0-30 5:19-25

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ../../node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js 8:13-30
Module not found: Error: Can't resolve 'stream' in 'D:\Programming\Projects\*\v4\front-end\node_modules\@vue\server-renderer\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
resolve 'stream' in 'D:\Programming\Projects\*\v4\front-end\node_modules\@vue\server-renderer\dist'
  Parsed request is a module
  using description file: D:\Programming\Projects\*\v4\front-end\node_modules\@vue\server-renderer\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\Programming\Projects\*\v4\front-end\node_modules\@vue\server-renderer\dist\node_modules doesn't exist or is not a directory
      D:\Programming\Projects\*\v4\front-end\node_modules\@vue\server-renderer\node_modules doesn't exist or is not a directory
      D:\Programming\Projects\*\v4\front-end\node_modules\@vue\node_modules doesn't exist or is not a directory
      D:\Programming\Projects\*\v4\front-end\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in D:\Programming\Projects\*\v4\front-end\node_modules
        single file module
          using description file: D:\Programming\Projects\*\v4\front-end\package.json (relative path: ./node_modules/stream)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Programming\Projects\*\v4\front-end\node_modules\stream doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\Programming\Projects\*\v4\front-end\node_modules\stream.mjs doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\Programming\Projects\*\v4\front-end\node_modules\stream.ts doesn't exist
            .vue
              Field 'browser' doesn't contain a valid alias configuration
              D:\Programming\Projects\*\v4\front-end\node_modules\stream.vue doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Programming\Projects\*\v4\front-end\node_modules\stream.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\Programming\Projects\*\v4\front-end\node_modules\stream.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\Programming\Projects\*\v4\front-end\node_modules\stream.wasm doesn't exist
        D:\Programming\Projects\*\v4\front-end\node_modules\stream doesn't exist
      D:\Programming\Projects\*\v4\node_modules doesn't exist or is not a directory
      D:\Programming\Projects\*\node_modules doesn't exist or is not a directory
      D:\Programming\Projects\node_modules doesn't exist or is not a directory
      D:\Programming\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
 @ ../../node_modules/@vue/server-renderer/index.js 4:2-64
 @ ../../node_modules/vue-meta/dist/vue-meta.cjs.js 854:27-58
 @ ../../node_modules/ts-loader/index.js??clonedRuleSet-5.use[0]!../../node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./app/site/views/index.vue?vue&type=script&lang=ts 2:0-35 8:32-39
 @ ./app/site/views/index.vue?vue&type=script&lang=ts 1:0-207 1:0-207 1:208-404 1:208-404
 @ ./app/site/views/index.vue 2:0-56 3:0-51 3:0-51 4:0-13 6:15-21
 @ ./router.ts
 @ ./main.ts 3:0-30 5:19-25

webpack 5.30.0 compiled with 1 error and 1 warning in 14249 ms
```

It's complaining about needing `stream`, but that's just because it's trying to load SSR code, I guess.

**Comment by glen-84** [comment]
I'm assuming that webpack is using the `module` field in `package.json`, which references `dist/vue-meta.esm-bundler.js` (which is not browser-friendly).

Perhaps you need a `browser` field in `package.json`, or to use package exports?

**Comment by pimlie** [comment]
@glen-84 Thanks, moving the require into the renderToStringWithMeta method and make it a dynamic import should solve it too I think as your bundler will then just tree-shake that method from your build. Will release a new version with that later today

**Comment by glen-84** [comment]
I tried `alpha.3`, but it doesn't work unless I add `"browser": "dist/vue-meta.esm-browser.js"` to the `package.json` file.

Package exports would likely also work.

**Comment by glen-84** [comment]
@pimlie Are you able to push a fix for this?

**Comment by mixalbl4-127** [comment]
+1
`    "vue-meta": "^3.0.0-alpha.3",`
same error
```
 ERROR  Failed to compile with 1 error
This dependency was not found:
* @vue/server-renderer in ./node_modules/vue-meta/dist/vue-meta.esm-bundler.js
To install it, you can run: npm install --save @vue/server-renderer
```

help please @pimlie

**Comment by pimlie** [comment]
Thanks, just published `alpha.4` with a browser field. Also removed @vue/server-renderer as peer dependency. Im still confused why adding the browser field is needed, I would expect that when using the esm-bundler dist the server-renderer dependency is shaked out if you are not using it. But for now this should work I suppose.

**Comment by mixalbl4-127** [comment]
I saw :)
@pimlie thx 3.0.0-alpha.4 fixed it!

**Comment by themojilla** [comment]
Tried latest fix `"vue-meta": "3.0.0-alpha.4",` with Vite. Still getting the error.

```
 vue-meta.esm-bundler.js:851:44: error: Could not resolve "@vue/server-renderer" (mark it as external to exclude it from the bundle)
const { renderToString } = await import('@vue/server-renderer');

```

**Comment by pimlie** [comment]
@themojilla Can you share a minimal repro?

**Comment by jdmr** [comment]
Have the same issue and published a minimal repo here:

https://github.com/jdmr/meta

**Comment by marcodarko** [comment]
oh no, I'm running into the same still with the latest version mentioned here. is there a newer fix?

**Comment by muttering-oldman** [comment]
@marcodarko , command from Readme.md:
`npm install vue-meta@next --save`
installs version 3.0.0-alpha.2, which has this problem.
I reinstalled the dependency with an explicit version with the command `npm install vue-meta@3.0.0-alpha.4` and the error disappeared. Maybe you have the same problem.
@pimlie , it would be great to fix it.

**Comment by marcodarko** [comment]
@muttering-oldman my package.json > "vue-meta": "^3.0.0-alpha.4" , thank you but I think the issue still persists even after that. I've disabled this featured on my project until there's a clear fix but would helpful to new users to clearly indicate that this version is so far only for SSR apps.

**Comment by pimlie** [comment]
@jdmr Thanks for the repro, very helpful!

This should be fixed in `alpha.5`. I have removed the ssr stuff from the default bundle, the issue is/was that tree-shaking only works when passing through terser but in dev the code isnt minimized. 

For ssr support you now need to import as follows:
```js
import { renderToStringWithMeta } from 'vue-meta/ssr'
```

**Comment by jdmr** [comment]
Thanks @pimlie! It's now running. Unfortunately it does not change the meta (page title). I'm getting the following:

```
runtime-core.esm-bundler.js:38 [Vue warn]: Failed to locate Teleport target with selector "htmlAttrs". Note the target element must exist before the component is mounted - i.e. the target cannot be rendered by the component itself, and ideally should be outside of the entire Vue component tree. 
  at <Metainfo> 
  at <App>
warn @ runtime-core.esm-bundler.js:38
runtime-core.esm-bundler.js:38 [Vue warn]: Invalid Teleport target on mount: null (object) 
  at <Metainfo> 
  at <App>
```

I've updated the small vite demo repo to use alpha.5

**Comment by pimlie** [comment]
@jdmr Hmm yeah, sorry. I think I made a logic error as rendering of attributes is different in the browser and during SSR. So that means that for the esm-bundler build we need a toggle on the render function so we can indicate that we are rendering for SSR. Will work on adding a isSSR arg to the render function.

In the mean time it should work if you explicitly use the esm-browser build, this will probably log an error though about a missing injection, also you have to remove the title tag from index.html as vue-meta will not check if a title tag already exists:
```js
import { createMetaManager } from 'vue-meta/dist/vue-meta.esm-browser'
```

**Comment by jdmr** [comment]
Thanks @pimlie

**Comment by enzostvs** [comment]
@jdmr Hi, can you update our repo with correct configuration please ? I have the same issue and it could help me!
Thanks a lot :)

**Comment by jdmr** [comment]
What repo @enzostvs?

**Comment by enzostvs** [comment]
@jdmr https://github.com/jdmr/meta This one is a view-meta test repo, right?
If that's the case, can you update it with the requirements to use vue-meta properly? Thanks!

**Comment by jdmr** [comment]
I didn't quite get how to enable it with the createMetaManager, sorry.

**Comment by pimlie** [comment]
I've updated @jdmr 's example here, this should work fully: https://github.com/pimlie/vue-meta-vite-example

**Comment by jdmr** [comment]
Thanks @pimlie!!!

**Comment by deathemperor** [comment]
> @jdmr Thanks for the repro, very helpful!
> 
> This should be fixed in `alpha.5`. I have removed the ssr stuff from the default bundle, the issue is/was that tree-shaking only works when passing through terser but in dev the code isnt minimized.
> 
> For ssr support you now need to import as follows:
> 
> ```js
> import { renderToStringWithMeta } from 'vue-meta/ssr'
> ```

I've tried `alpha6` but still get this

```
Uncaught TypeError: Cannot destructure property 'createComponentInstance' of 'vue.ssrUtils' as it is null.
    at node_modules/@vue/server-renderer/dist/server-renderer.cjs.js (server-renderer.cjs.js:126)
    at __require (chunk-QMTEDKHV.js?v=f98dbd74:6)
    at node_modules/@vue/server-renderer/index.js (index.js:6)
    at __require (chunk-QMTEDKHV.js?v=f98dbd74:6)
    at vue-meta.esm-bundler.js:850
```

**Comment by pimlie** [comment]
@deathemperor Could you add a small repro? The error doesnt originate directly from vue-meta it seems, so maybe its something else?

Also please note that the SSR example in the Readme was wrong, see the updated readme. `renderToStringWithMeta` no longer calls renderToString for the app anymore, it only calls it for meta teleports

**Comment by OmgImAlexis** [comment]
I'm using `vite@2.3.8` + `vue@3.0.5` + `vue-meta@3.0.0-alpha.9` with the steps from https://github.com/pimlie/vue-meta-vite-example and it works. Make sure to do `npm i vue-meta@3.0.0-alpha.9` as `npm vue-meta@next` seems to still install an old alpha.

In saying that @pimlie I'm still seeing this issue with the types.

<img width="466" alt="Screen Shot 2021-07-06 at 9 13 41 pm" src="https://user-images.githubusercontent.com/6525926/124594555-15b0b280-de9f-11eb-92b9-7773001eae48.png">
<img width="757" alt="Screen Shot 2021-07-06 at 9 13 36 pm" src="https://user-images.githubusercontent.com/6525926/124594564-18130c80-de9f-11eb-977e-df959af5adc9.png">

**Comment by TonhaoSantos** [comment]
In version **3.0.0-alpha.7** this error does not occur, I was only able to continue developing like this.

`yarn add vue-meta@3.0.0-alpha.7`

**Comment by nicooprat** [comment]
Worth noting that `npm install --save vue-meta@next` actually installs `^3.0.0-alpha.2`, which has this issue. Using `npm install vue-meta@3.0.0-alpha.7 --save` solved it.
