### ISSUE TITLE
No manager or current instance

### ISSUE THREAD

**Issue by Tribevote** [nuxt/vue-meta#663]
I'm using the basic implementation of declaring useMeta in setup function 

`useMeta({
      title: 'My Example App',
      htmlAttrs: {
        lang: 'en',
        amp: true
      }
    })`

Code in template of the component 

 `<metainfo>
      <template v-slot:title="{ content }">{{ content }} - Yay!</template>
  </metainfo>`

When I run this I keep getting this error 

 `runtime-core.cjs.js?b7d1:516 Error: No manager or current instance`

**Comment by pimlie** [comment]
@Tribevote Did you create & register a meta manager in your App setup? 

```js
import { createApp } from 'vue'
import { createMetaManager, defaultConfig, deepestResolver } from 'vue-meta'

const app = createApp(App)
app.use(createMetaManager(defaultConfig, deepestResolver))
app.mount()
```

Btw, in the next version the arguments to createMetaManager will have a default value similar to above and thus be optional

**Comment by Tribevote** [comment]
This resolved the issue. 

However I'm unable to figure out the right way to update the page title. 

Here is the code I used 


setup() {

    const state = reactive({
      date: null,
      metaUpdated
    })

    const counter = ref(0)

  
    const computedMeta = computed(() => ({
      title: 'My Title',
      description : 'My Description'
    }))

     const { meta, onRemoved } = useMeta(computedMeta)

    return {  
       ...toRefs(state),
       meta }



Code in Template 

`   <title>{{meta.title}}</title>
`

This doesn't seem to work, could you let me know the right way to update title and other og tags?

**Comment by pimlie** [comment]
Did you check/run the example? Eg see this file https://github.com/nuxt/vue-meta/blob/next/examples/vue-router/App.js

**Comment by Tribevote** [comment]
I'm trying to run this a Vue 3 Composition API which uses Vue Router 

My use case is only 1 route needs to be SEO friendly, the og tags should be picked up. 
Example: /seopage is the url 
Component is linked to the route via router.js file 

 `{
        path: '/seopage',
        component: () =>
        import ( /* webpackChunkName: "Dynamic Page" */ './pages/DynamicPage.vue'),
        meta: {  layout: "sidebar" }
    }`


Code inside my Component 
` <template>`
` <metainfo>`
 `    <template v-slot:base="{ content }">http://nuxt.dev:3000{{ content }}</template>`
  `    <template v-slot:title="{ content, metadata }">{{ content }} - {{ metadata.description }} - Hello</template>`
  `    <template v-slot:og(title)="{ content, metadata, og }">`
   `     {{ content }} - {{ og.description }} - {{ metadata.description }} - Hello Again`
  `    </template>`
    
 `</metainfo>`
` </template>`


`import { useMeta, useActiveMeta } from 'vue-meta'`
`import { reactive, toRefs } from 'vue'`

`const { metadata } = useMeta({`
      `charset: 'utf8',`
      `title: 'My Title',`
      `description: 'The Description',`
      `og: {`
       ` title: 'Og Title',`
        `description: 'Bla bla',`
        `image: [`
         ` 'https://picsum.photos/600/400/?image=80',`
         ` 'https://picsum.photos/600/400/?image=82'`
       ` ]`
     ` },`
     ` twitter: {`
       ` title: 'Twitter Title'`
      `}`
    `})`
 


   ` const state = reactive({
      date: null,
      metaUpdated
    })
`

`return {  ...toRefs(state),
       metadata}`


I'm getting this error when I open the url 

TypeError: Cannot read property 'tag' of undefined

Reference - https://prnt.sc/114vxud

My App doesn't use nuxt, could that be causing the issue?

**Comment by pimlie** [comment]
You should get the active metadata from `useActiveMeta`, that returns the global / total aggregated meta state.  `useMeta` returns a `meta` prop which is a proxy to the object you passed as arg to useMeta

Nope, lack of docs is the only cause here (sorry!) ;)

**Comment by Tribevote** [comment]
I changed 
  
`const { metadata } = useMeta({` to `const { meta } = useMeta({`

and added this line 

`const metadata = useActiveMeta()`

But I still keep getting the error : 

`TypeError: Cannot read property 'tag' of undefined`

What else am I missing here?

**Comment by pimlie** [comment]
@Tribevote Im not sure, could you post a repro with code so I could have a look?

Btw, if you post code on Github between triple tick marks followed by the language then the code will be formatted as a block and not per line :)

**Comment by Tribevote** [comment]
@pimlie I created a nuxt app to implement this, I couldn't get the Vue app to work. Thank you for the formatting tip 😀

**Comment by MartinMa** [comment]
> @Tribevote Did you create & register a meta manager in your App setup?
> 
> ```js
> import { createApp } from 'vue'
> import { createMetaManager, defaultConfig, deepestResolver } from 'vue-meta'
> 
> const app = createApp(App)
> app.use(createMetaManager(defaultConfig, deepestResolver))
> app.mount()
> ```
> 
> Btw, in the next version the arguments to createMetaManager will have a default value similar to above and thus be optional

I'm using `3.0.0-alpha.5`. Is it still necessary to pass anything to `createMetaManager`? I have the following TypeScript problem with `deepestResolver`.

```
(alias) namespace deepestResolver
import deepestResolver
Argument of type 'typeof deepest_d' is not assignable to parameter of type 'MetaResolver'.
  Types of property 'setup' are incompatible.
    Type '(context: MergeResolveContextDeepest) => void' is not assignable to type 'MetaResolveSetup'.
      Types of parameters 'context' and 'context' are incompatible.
        Type 'MetaResolveContext' is not assignable to type 'MergeResolveContextDeepest'.
          Property 'depth' is missing in type 'MetaResolveContext' but required in type '{ depth: number; }'.ts(2345)
vue-meta.d.ts(185, 5): 'depth' is declared here.
```

Either way, I'm not able to get a very simple example running. The `metainfo` component seems to work, but everything I pass to `useMeta` is ignored.

Without `app.use(createMetaManager())` I get `No manager or current instance`. Maybe that hint can be added to the `README`.

Oh and I'm using Vite instead of Webpack. Do you think that might be an issue?

**Comment by pimlie** [comment]
@MartinMa Try `alpha.6`, should be fixed. The included router example is written in TS now too.
