### ISSUE TITLE
How to use it with Vuejs 3 + TypeScript ?

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [nuxt/vue-meta#665]
How to use it with Vuejs 3 + TypeScript ?

**Comment by ayoubkhan558** [comment]
```js
Argument of type 'typeof import("E:/Ayoub Khan/Porfolios/ayoubkhan-portfolio/node_modules/vue-meta/dist/vue-meta")' is not assignable to parameter of type 'Plugin_2'.
  Property 'install' is missing in type 'typeof import("E:/Ayoub Khan/Porfolios/ayoubkhan-portfolio/node_modules/vue-meta/dist/vue-meta")' but required in type '{ install: PluginInstallFunction; }'.ts(2345)
```

![image](https://user-images.githubusercontent.com/20210961/113616903-934bf480-960a-11eb-9095-8033fb634fbc.png)

**Comment by mixalbl4-127** [comment]
1. Make shure that you use vue-meta@**3.0.0-alpha.4**
2.
```
import { createMetaManager } from "vue-meta";
...
const metaManager = createMetaManager();

app.use(metaManager).mount("#app");
```

**Comment by pimlie** [comment]
Just added a types entry in package.json, that was missing in versions before alpha.4.

**Comment by mixalbl4-127** [comment]
@pimlie offtopic: cant find "how to destroy/revert" all of changes of meta when component unmounted. is this a bug?
ex:

```
<template>
  <div>tst</div>
   <metainfo />
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useMeta } from "vue-meta";

export default defineComponent({
    setup() {
        const { meta } = useMeta({
            title: "My Title",
            htmlAttrs: {
                amp: true,
                lang: ["en", "nl"]
            },
        });
    }
});
</script>
```

when this component unmounted - title and htmlAttrs will not change and still present. In react-helmet this will revert meta when component whitch made it is unmounted

**Comment by charles-allen** [comment]
I needed to do 6 things:

1. Update `vue-meta` to v3 (in package.json)
    ```diff
    - "vue-meta": "^2.4.0",
    + "vue-meta": "^3.0.0-alpha.4",
    ```
1. Add `metaManager` to my Vue app
    ```ts
    createApp(App)
        .use(router)
        .use(store)
        .use(createMetaManager()) // add this line
    
      await store.dispatch(ACTIONS.init)
      await router.isReady()
      app.mount('#app')
    ```
1. Add `<metainfo>` to App.vue `<template>` (this is also where I set a "title template")
    ```vue
    <metainfo>
      <template v-slot:title="{ content }">{{ content ? `${content} | SITE_NAME` : `SITE_NAME` }}</template>
    </metainfo>
    <header />
    <router-view />
    <footer />
    ```
1. Add meta data to App.vue `<script>` (here's an example using `vue-class-component`)
    ```ts
    export default class App extends Vue {
      meta = setup(() => {
        useMeta({
          title: '',
          htmlAttrs: {
            lang: 'en',
            amp: true
          }
        })
        return { metadata: useActiveMeta() }
      })
    }
    ```
1. Override meta in each component (again, example for `vue-class-component`)
    ```ts
    export default class Events extends Vue {
      meta = setup(() => {
        useMeta({ title: 'Events' })
        return { }
      })
    }
    ```
1. Comment out the title in `/public/index.html` (see #667)
    ```html
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <!-- <title><%= htmlWebpackPlugin.options.title %></title> -->
        ...
      </head>
      ...
    </html>
    ```

@pimlie - Please correct me if I missed something or if a step is unnecessary!

**Comment by pimlie** [comment]
@charles-allen Thanks for the detailed log, this seems to be ok. Returning `metadata: useActiveMeta` shouldnt be strictly necessary though, in the examples its being returned to print the active meta state on the page as a stringified json object. But maybe you are using metadata yourself outside of the metainfo componnet?

**Comment by charles-allen** [comment]
Thanks for the feedback! I've updated my project & fixed the example above. I've also added a vanilla Vue 3 version for people not using `vue-class-component` :)

**Comment by misterboe** [comment]
Have a look at the docs on the new alpha tag > https://github.com/nuxt/vue-meta/tree/v3.0.0-alpha.5

Works out of the box.

**Comment by Trinovantes** [comment]
`alpha.5` moved ssr functionality to a separate file but it's currently missing declarations `dist/ssr/index.d.ts`

**Comment by ataylor32** [comment]
I'm working on a Vue 3 project that does *not* use the composition API. Instead, it uses the traditional syntax (with the help of `defineComponent`). I tried getting vue-meta v3.0.0-alpha.5 to work with this project, but the `<title>` wasn't reactive.

An example use case: let's suppose your route is /articles/some-article. Before the article is loaded, we only know the slug (`some-article`). Once it loads, we have all of the article's information, including its title. At that point, I would like the `<title>` to be set to the article's title. I haven't been able to get this working in my project and I'm wondering if it's because I'm not using the composition API.

**Comment by charles-allen** [comment]
@ataylor32 - I'm not using `defineComponent`, but I also had some issues with a dynamic title. For me, I think my mistake was not initializing my "article" field (leaving it as `undefined`); changing it to be initialized as `null` seems to have made the difference (presumably because that ensures it's reactive).

My code is using `vue-class-component`, but here's the relevant part anyway in case it triggers any other insights or useful discussion:
```ts
export default class Profile extends Vue.with(class {
  slug!: string
}) {
  user: User | null = null

  meta = setup(() => useMeta(computed(() => ({
    title: this.user?.name ?? 'Profile'
  }))))

  async mounted(): Promise<void> {
    this.user = (await db.collection(USERS).doc(this.slug).get()).data() as (User | undefined) ?? null
  }
}
```

**Comment by Sirius-KiH** [comment]
How would you use og or twitter meta tags with metaInfo?

```
<metainfo>
  <template v-slot:og:title="{ content }">{{ content }}</template>
</metainfo>
```

^^ This does not work.

Also, is there an elegant way to use the same value for multiple fields (like `title`, `og:title` and `twitter:title`)? Right now I would use something like this:

```
        useMeta({
                title: 'My title',
                "og:title": 'My title',
                "twitter:title": 'My title',
        });
```

**Comment by pimlie** [comment]
@Sirius-KiH With the default vue-meta configuration opengraph & twitter can be added by using nested objects.

```js
description: description,
og: {
  description: ogDescription,
},
twitter: {
  description: twitterDescription,
}
```

then in the component you could do:
```vue
      <template v-slot:og(description)="{ content, metainfo }">{{ content || metainfo.description }}</template>
      <template v-slot:twitter(description)="{ content, metainfo }">{{ content || metainfo.description }}</template>
```

this way if `ogDescription` or `twitterDescription` are empty they will fallback to the default `description`

**Comment by romain130492** [comment]
why Am i still getting that error...: `Uncaught SyntaxError: The requested module '/node_modules/.vite/vue-meta.js?v=4865df67' does not provide an export named 'createMetaManager'`? 
I followed the exact steps from above

* Vue3 project with no SSR and using Vite and using "vue-meta": "^3.0.0-alpha.4",

**Comment by doutatsu** [comment]
@romain130492 You need to update the version - `alpha.9` is the latest and I think plugin was added in alpha.8

**Comment by doutatsu** [comment]
What is the latest update on the Vue 3 support? Documentation is very sparse, not quite sure how to migrate the old version to this one

**Comment by tripflex** [comment]
For anybody showing up later searching, this project is no longer maintained ( https://github.com/nuxt/vue-meta/issues/808 ) and suggest looking at using something like https://github.com/unjs/unhead/
