### ISSUE TITLE
[v3] Nested meta objects do not react on changes

### ISSUE THREAD

**Issue by ardier16** [nuxt/vue-meta#666]
### Description

When using `vue-meta` like this:

```js
setup() {
  const ogTitle = ref("OG title");

  const { meta } = useMeta(
    computed(() => ({
      title: ogTitle.value,
      og: { title: ogTitle.value },
    }))
  );

  return { meta, ogTitle };
}
```

nested object props (e.g. `og`) are not updated on `ogTitle` property change, but first level props (like `title`) work fine.

### Reproduction link

https://codesandbox.io/s/vue-meta-og-tdq6m

**Comment by ardier16** [comment]
@pimlie does not Vue proxy conflict with VueMeta merge proxy?

**Comment by pimlie** [comment]
This should be fixed in `alpha.5`

**Comment by ardier16** [comment]
@pimlie works fine, thanks 🎉

**Comment by ardier16** [comment]
@pimlie works fine, thanks 🎉
