### ISSUE TITLE
[v3] "two <title>" and doen't clean html after unmount

### ISSUE THREAD

**Issue by mixalbl4-127** [nuxt/vue-meta#667]
```html
<template>
  <div>tst</div>
   <metainfo />
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useMeta } from "vue-meta";

export default defineComponent({
    setup() {
        const { onRemoved } = useMeta({
            title: "My Title",
            htmlAttrs: {
                amp: true,
                lang: ["en", "nl"]
            }
        });
        onRemoved(() => {
            alert("onRemoved");
        });
    }
});
</script>
```
@pimlie 
1. This code will add SECOND `<title>` tag to `<head>` instead of replace it.
2. after component removing SECOND `title` is removed but `<html lang="en,nl" amp="true">` still present :(

**Comment by pimlie** [comment]
We use vue-portals to render all the tags which means we cannot easily overwrite existing tags afaik. Im not sure whether we'd should add that complexity, maybe for title because its pretty easy (and we could maybe use document.title again) but if we have to start checking any tag if it already existed in the template then that defies the purpose of using portals a bit.

**Comment by charles-allen** [comment]
@pimlie - Does this mean that we should remove all dynamic title/meta from `public`, and instead declare them *only* in `App.vue`?

**Comment by johanvanhelden** [comment]
I would love to have a title for people with noscript running. So there is at least something.

So if you could implement a solution for At least the title I would be very happy.

**Comment by pimlie** [comment]
@johanvanhelden makes sense, will update that. Thanks

**Comment by pimlie** [comment]
Should be fixed in alpha.7

**Comment by johanvanhelden** [comment]
> 
> 
> Should be fixed in alpha.7

I've just updated and can confirm it is working flawlessly. Thanks a lot @pimlie !
