### ISSUE TITLE
[v3] MetaManager constructor should create new instance of `active` instead of using global state

### ISSUE THREAD

**Issue by Trinovantes** [nuxt/vue-meta#673]
vue-meta works correctly on the first page load in my ssr application. Subsequent page refreshes results in double `<title>` tags and causes hydration errors.

I think this is caused by the global `active` variable used in `manager.ts`: https://github.com/nuxt/vue-meta/blob/bffa8f15aa8487b294cac5105a47038407031143/src/manager.ts#L27

Edit: I see that there's already a PR addressing this https://github.com/nuxt/vue-meta/pull/668#issue-616581186

**Comment by pimlie** [comment]
@Trinovantes It probably is, but could you please confirm this is still an issue with `alpha.6` ?

**Comment by Trinovantes** [comment]
`alpha.6` is currently missing typescript definitions for ssr

**Comment by Trinovantes** [comment]
My other concern is that `ssr/index.js` is compiled as ES6 module. My server dist is compiled with `webpack-node-externals` which means it doesn't get processed into commonjs2 by webpack. As a result, I had to add this awkward line to my webpack build config specifically for vue-meta:

```ts
externals: [
        nodeExternals({
            allowlist: [
                /^vue-meta*/,
```

Can `ssr/index.js` be in cjs format instead? 

I guess a broader question is why the decision to move ssr into a separate module? I'm assuming every user of vue-meta is already using some bundler anyways to process vue SFC (webpack, vite, etc.). Why not use the `sideEffects` flag in package.json to enable tree shaking in these bundlers instead?

**Comment by pimlie** [comment]
@Trinovantes Thanks for your comments.

- The ssr types were exported as `dist/vue-meta-ssr.d.ts`, will move them to ssr/index
- I am sorry, I forgot to update the readme last week. See the new readme, the renderToStringWithMeta function no longer calls renderToString for you anymore
- With regards to packaging, see https://github.com/nuxt/vue-meta/issues/662#issuecomment-831132626. We already list `sideEffects: false` in package.json, but afaik tree-shaking with rollup is done by terser which is not executed in development mode. If you have a better suggestion for how to make ssr support optional during development mode for a client only app then Im all ears!

Your fix for the es module isnt that awkward to me. Unless there are a lot more requests for exporting ssr support as cjs then I prefer to keep it as es. That's where we should be moving towards to with the Node.js ecosystem now that esm modules are stable & supported by the latest LTS.

**Comment by Trinovantes** [comment]
I think `ssr/index.d.ts` is still missing in alpha.7. But I can confirm that this issue is resolved in alpha.7 with my manual `index.d.ts`.

I wouldn't worry about the `externals` issue. It's just something specific to my setup. I have no idea why my esm server bundles won't run with node14 on my machine or why removing `webpack-node-externals` breaks everything but that's out of the scope of `vue-meta`.

**Comment by Trinovantes** [comment]
@pimlie I see that you've now included `ssr/index.d.ts` in `package.json` but `alpha-8` is still missing the file. I'm assuming you just forgot to build before publishing? If so, can I suggest adding `"prepublishOnly": "yarn build",` to your `scripts` in `package.json` so it'll automatically build again before publishing in the future?

**Comment by pimlie** [comment]
@Trinovantes Thanks for the tip, actually I forgot to add index.d.ts to package.json before releasing 8 and only added that commit after publishing (you can compare the times). Was hoping to get some more work done to release with the ssr types fix, but didnt finish that today. So just published `alpha.9` with just the ssr types fix. Sorry for the wait.

vue-meta uses [standard-version](https://github.com/conventional-changelog/standard-version) for releasing, you can check the release hooks we use here: https://github.com/nuxt/vue-meta/blob/next/.versionrc (ie luckily I dont have to do that manually :smile_cat: )

**Comment by Trinovantes** [comment]
Huh, guess I learn something new everyday

Thanks for all your work
