### ISSUE TITLE
Option to re-append a script after each page navigation?

### ISSUE THREAD

**Issue by drewbaker** [nuxt/vue-meta#674]
So I'm always being asked by clients to add some legacy script to the head - like a chat widget, a GDPR cookie manager, or a HubSpot tracking code snippet. These code snippets are always written to expect hard-page loads between each page of the site - so not a JS framework site like a Vue or Nuxt site.

It would be very useful to have an option for each script tag to remove it and re-add it (so the scripts built in init functions run) after each page navigation has happened. Otherwise I end up having to write a plugin for everyone of these scripts and try to figure out it's init() function to call after route change.

I imagine something like this:

```
            script: [
                {
                    src: "//js.hs-scripts.com/12345678.js",
                    id: "hs-script-loader",
                    async: true,
                    defer: true,
                    body: true,
                    reload: true // This would reload the script after each page navigation
                }
            ],
``` 

Or is there a better way to do solve this use case? Or perhaps it can be solved by setting a hid or key to`this.$route.path?`?

**Comment by pimlie** [comment]
If you add a watcher on `$route.path` which increments an id and use that id as part of your `vmid / hid` then it should work as you suggest. There is a small chance that a browser optimizes this if you do everything within the same tick, so you might need to increment the id in $nextTick or maybe even [$forceNextTick](https://github.com/twickstrom/vue-force-next-tick)

**Comment by drewbaker** [comment]
OK thanks @pimlie I'll try that next time.
