### ISSUE TITLE
[v3] SSR Docs - should make a note that manager needs to be created/rendered outside of async components

### ISSUE THREAD

**Issue by Trinovantes** [nuxt/vue-meta#680]
When you get a chance to update the docs for v3's release, you should make a note about how this plugin handles ssr duplicate tag removal:

https://github.com/nuxt/vue-meta/blob/a8d6f0ab0ea3cf4f3c3fbdc6993693569eb3725d/src/manager.ts#L183-L189

To prevent duplicate tags in sites that are prerendered or generated via SSR, this plugin deletes all DOM nodes marked with ` data-vm-ssr` property on the `DOMContentLoaded` event. This means that the manager needs to be created and rendered (via `mount`) before the `main.js` script finishes its synchronous execution. Otherwise, the DOM event will fire before this plugin can register its event listener.

As a result these 2 code patterns are not possible:
```ts
async main() {
    const app = createApp(AppLoader)

    const metaManager = createMetaManager(true)
    app.use(metaManager)

    const router = createAppRouter()
    app.use(router)

    await router.isReady()
    app.mount('#app')
}

main().catch() // Execution will immediately finish and the DOM event will fire before mount is called
```
Solution is to simply remove the `await router.isReady()` and change `main()` to a synchronous function. I'm not too sure what the implications are if you rely `<transition>`. The [vue-router docs](https://next.router.vuejs.org/guide/migration/#all-navigations-are-now-always-asynchronous) aren't too clear what happens when the `await isReady()` is omitted. 

```ts
<template>
    <suspense>
        <template #default>
            <!-- <metainfo> cannot be a child inside suspense -->
        </template>
    </suspense>
</template>
```
Solution is to simply declare `<metainfo>` outside of the outer-most suspense

**Comment by Trinovantes** [comment]
Looks I jumped the gun here. I was only able to prevent duplicate tags in dev mode but not production builds. It's probably due to one of my custom configurations; I will need to investigate this later...

As an aside, I think the `window.addEventListener` should be called on creation `createMetaManager` rather than in the render function. Right now I'm still not too sure about when/if `render` actually gets called inside `mount` in all conditions

**Comment by pimlie** [comment]
@Trinovantes Thanks for all your feedback!

I think this commit might fix the issue? https://github.com/nuxt/vue-meta/commit/1785d4fef6b2c2adaa645e44419c3da883863562 So instead of always adding the DOM event listener we only add it if the DOM is still loading and otherwise just immediately cleanup the ssr tags

**Comment by pimlie** [comment]
That fix has been released in alpha.7

**Comment by Trinovantes** [comment]
Thanks! I can confirm both my dev/prod builds works as expected without any changes
