### ISSUE TITLE
3.0.0-alpha.6 issue with useMeta -> description. Please. Help!

### ISSUE THREAD

**Issue by Folsten** [nuxt/vue-meta#682]
Current version: 3.0.0-alpha.6
Follow official docs, also checked other websites & guides.

I'm using this

![Screenshot_3](https://user-images.githubusercontent.com/37974295/119271901-477dfa80-bc0c-11eb-8703-6b63c1c5acc6.jpg)

  
The title works right, but description - not.

![description](https://user-images.githubusercontent.com/37974295/119271877-2f0de000-bc0c-11eb-9533-93fdd4c03836.jpg)

On the screenshot you can clearly see, that it finally implements to `<meta content="">` without a name "description".

This should be `<meta name="description" content="any text">`

**What I'm doing wrong, how to fix this?**

**Comment by pimlie** [comment]
This was a bug and first reported in #681. This should be fixed in alpha.7. Thanks!
