### ISSUE TITLE
Error: Module parse failed

### ISSUE THREAD

**Issue by tymmesyde** [nuxt/vue-meta#687]
Hi,
I tried to install `vue-meta@3.0.0-alpha.9` via npm and got this error when I started the vue-cli dev server with `npm run serve`: 
```
Module parse failed: Unexpected token (8:7170)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
I tried, removing `package-lock.json` and `node_modules` and reinstalling the packages, tried to rollback to `alpha.5` which was working fine but I'm now stuck with this error message.
What did I do wrong ?

**Comment by tymmesyde** [comment]
I installed `vue-meta@3.0.0-alpha.4` and it worked !

**Comment by pimlie** [comment]
@tymmesyde Are you using SSR? Then you might need to make sure that vue-meta/ssr gets transformed by babel

**Comment by anuzhin** [comment]
@pimlie Error when import plugin (vue-meta@3.0.0-alpha.8 and later):
```
> vue-cli-service build --mode development --watch "--port" "8080"
-  Building for development...
 ERROR  Failed to compile with 1 error16:58:24
 error  in ./node_modules/vue-meta/dist/vue-met
```
vue-cli-service version: latest (4.5.13)

**Comment by timmyomahony** [comment]
I'm also getting this error  with `vue-meta@3.0.0-alpha.9` using `yarn serve` (which uses `vue-cli-service serve`).
