### ISSUE TITLE
required from "dist/vue-meta.cjs.js" exist optional chaining

### ISSUE THREAD

**Issue by johnnywang1994** [nuxt/vue-meta#691]
hi~

version: 3.0.0-alpha.9

Question:
I use nodejs require the commonjs module which leads to error with optional chaining. (which was not occured in alpha.2)

Nodejs: v12.22.1

Position:
dist/vue-meta.cjs.js:959

Error:
"SyntaxError: Unexpected token '.'" in 
if (!instance?.type || !(options.keyName in instance.type)) {

Did I need to update my nodejs version ^14...?

**Comment by johnnywang1994** [comment]
I changed the webpack to output library type "module", and use "babel-node" to compile my server so that optional chaining can be compiled.

**Comment by pimlie** [comment]
@johnnywang1994  You don't _need_ v14, but v14 has been LTS for quite some time now so why do we need to still support older versions out of the box? If you need cjs support for ssr, then you can easily transpile this code with babel. That said, we will probalby add a cjs build for ssr too later on

**Comment by CyberAP** [comment]
Having the same issue with both client and server bundle. I am using exactly the same node version. This fails for me on optional chaining and class properties. Hope the stable bundle will be completely transpiled, `transpileDependencies` in `vue-cli` fails for me on this very package for some reason.
