### ISSUE TITLE
Merging meta from mixins doesn't work anymore

### ISSUE THREAD

**Issue by Kapcash** [nuxt/vue-meta#695]
## Description of the problem

I'm working on a Nuxt app and I just found out using `head()` from a mixins doesn't merge if the component using the mixin also declares a `head()`.

-> **Mixin and component meta function doesn't merge properly**

## Reproduction

Usable [Codesandbox](https://codesandbox.io/s/nuxt-vue-meta-mixins-merging-20u17)
Both `index` and `about` pages use the same mixins `SeoMixin` which declares the meta `title` and a canonical link.

- The `index` page doesn't have its own `head` method, so it has the meta info from the mixin as expected. (tab title is "Title from mixin")
- The `about` page has its own `head` method, and it doesn't merge with the mixin results (see the tab title)

### Steps to reproduce

- Create a Vue mixins that declare a meta function (`head`, `metaInfo` or whatever depending on the configuration)
- Create a component that uses the mixin and declare its own meta function
- Both results from mixin + component are not merged

## Notes

There were a similar issues before, which has been fixed by PR https://github.com/nuxt/vue-meta/pull/262
But it looks like the last releases has introduced a regression for this.

I started adding a unit test on the code source to check it wasn't working.  
I'll try to fix it myself as soon as I have time for this.

**Comment by pimlie** [comment]
Thanks for the report, this seems to be a very old regression indeed. As this seems to be an edge-case Im not sure if I will fix this, sorry. A PR is always welcome ofc!
