### ISSUE TITLE
Meta `name` attribute is being set to "meta" instead of "description"

### ISSUE THREAD

**Issue by glen-84** [nuxt/vue-meta#696]
Using:

```ts
useMeta({
    meta: [
        {
            name: "description",
            content: "xxx"
        }
    ]
});
```

And getting:

```html
<meta name="meta" content="xxx">
```

Why is the `name` set to `meta`?

![image](https://user-images.githubusercontent.com/261509/122798531-fd4a7080-d2c0-11eb-9088-ed4cd0132b8f.png)

L599, sets the `name` attribute to `meta`. Why is this?

**Comment by abdurahmanrizal** [comment]
i got same problem, what's solution?

**Comment by yingming25** [comment]
Try below.
template(App.vue):
```
  <metainfo>
    <template v-slot:title="{ content }">{{ content }}</template>
    <template v-slot:description="{ metainfo }">{{ metainfo.description }}</template>
  </metainfo>
```
script(child component):
```
  setup () {
    useMeta({
      title: '',
      description: 'your description'
    })
  }
```

**Comment by abdurahmanrizal** [comment]
how about <meta name='title' > ?  i use 
`setup() {
      useMeta({
          title: ''
      })
}`

rendering title, not meta name='title'

**Comment by Felix-Puetz** [comment]
I've ran into the same issue.
For my case the cause of it was this
https://github.com/nuxt/vue-meta/blob/eec4e7c7c00dfff74edd29675421052596bbada1/src/config/tags.ts#L16
![image](https://user-images.githubusercontent.com/50131232/125314761-c7842f00-e336-11eb-9c5f-a90c33dbeac5.png)


by removing this line I was able to resolve that issue

**Comment by jgrauel** [comment]
@glen-84  I am seeing the same issue in v3.0.0-alpha.9

**Comment by glen-84** [comment]
@pimlie Are you still maintaining this project?

**Comment by jgrauel** [comment]
I have a fix for this I hope to get a PR in later this week for review.

**Comment by glen-84** [comment]
I switched to [@vueuse/head](https://github.com/vueuse/head/).

**Comment by zkd8907** [comment]
same issue in v3.0.0-alpha.9
