### ISSUE TITLE
How to set meta properties imperatively (client-side)?

### ISSUE THREAD

**Issue by kdekooter** [nuxt/vue-meta#701]
I am trying to set meta attributes outside the vue-router machinery - from a modal popup. `metaInfo` seems to be ignored in this case. 

Is there a way to set meta data from my own code? According to the docs `$meta().inject` is limited to SSR solutions. It would be great to do something similar from the browser.

**Comment by pimlie** [comment]
vue-meta isnt really linked to vue-router, but it is bound to the app $root instance. If you create your modals and instantiate eg a new Vue $root component then the modal $root is not the same as the app $root so metaInfo will be ignored (vuetify does this too). You should be able to use addApp to link them when you create the modal $root https://vue-meta.nuxtjs.org/api/#meta-addapp but addApp work outside of the component options & auto-merging.
