### ISSUE TITLE
titleTemplate not working

### ISSUE THREAD

**Issue by OmgImAlexis** [nuxt/vue-meta#702]
I can't seem to get `titleTemplate` working.
Is this because it's not finished in the alpha or am I possibly hitting a bug/user error?

My `App.vue` contains this.

```js
metaInfo: {
    // if no subcomponents specify a metaInfo.title, this title will be used
    title: 'Default title',
    // all titles will be injected into this template
    titleTemplate: `%s | ${window.location.hostname.toLowerCase()}`
},
```

My `NotFound.vue` contains this. `NotFound.vue` is mounted in the `App.vue` via a `<router-view>`.

```js
metaInfo: {
    title: `404 - Not Found`
},
```

Viewing the NotFound page only shows `404 - Not Found`. Moving the titleTemplate from `App.vue` to `NotFound.vue` makes the title start working. I DO have a component between these which is my layout component it's simply a template with a `<slot></slot>` in the middle to wrap my page. Could this be the issue?

**Comment by Felix-Puetz** [comment]
@OmgImAlexis wasn't working for me either. 
This is my current solution
```vue
<template>
  <metainfo>
    <template v-slot:title="{ metainfo }">{{
      metainfo.titleTemplate(metainfo.title)
    }}</template>
  </metainfo>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useMeta } from 'vue-meta';

export default defineComponent({
  setup() {
  useMeta({
    titleTemplate(chunk: string) {
      return `${chunk}${import.meta.env.VITE_TITLE_APPEND}`;
    },
  })
  },
});
</script>
```

This will have a smiliar behaviour except that you HAVE to use a function

**Comment by BrayanCaro** [comment]
Instead of using your layout as a wrapper with `slots`, you can use another `router link`:
```vue

<template>
  <div>
    <div>
      navbar:
      <router-link to="/">home</router-link>
      <router-link to="/fdsfds">not found</router-link>
    </div>
    <hr/>
    <router-view></router-view>
    <hr/>
    <p>footer</p>
  </div>
</template>
```

And your routes can be something like this:

```js
import BaseLayout from "@/components/BaseLayout";
import Home from "@/components/Home";
import NotFound from "@/components/NotFound";

export default [
    {
        path: '',
        component: BaseLayout,
        children: [
            {path: '', component: Home},
            {path: '/:catchAll(.*)', component: NotFound}
        ]
    }
]
```

## Demo (vue 2, vue-meta 2, vue router 3)

⚠️ To see the tabs click on Browser -> Open in new window (the last button)

![image](https://user-images.githubusercontent.com/41640423/126874944-37a89ba5-1bc3-4fdc-83e4-12f54df0c317.png)

[![Edit Vue meta (title example)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-meta-title-example-7p19c?fontsize=14&hidenavigation=1&theme=dark)

**Comment by jgrauel** [comment]
@OmgImAlexis  I am unable to get the titleTemplate to function as well. Has anyone come up with a fix not using Composition API (aka setup()) But using the Options API ?
I have tried both a string for the template as well as a function. The code simply outputs a `<titletemplate></titletemplate>` tag.

**Comment by tinyfly** [comment]
This stale bot should be turned off. There seems to be no maintainers for this repo and unanswered questions shouldn't be marked as stale automatically.

**Comment by flx-sta** [comment]
Agree.
Been having that issue with some other issues too but I can't just go ahead and regularly re-invent the wheel in the issues

**Comment by DengSihan** [comment]
https://github.com/nuxt/vue-meta/issues/783#issuecomment-1286392985

this works for me
