### ISSUE TITLE
Cannot add meta title to dynamic url

### ISSUE THREAD

**Issue by jmaric** [nuxt/vue-meta#703]
Hi! i cannot find soultion dynamic title for dynamic url "/:id".  It would be great to have it.

**Comment by Felix-Puetz** [comment]
@jmaric maybe this helps you
https://github.com/nuxt/vue-meta/issues/702#issuecomment-878520691

**Comment by BrayanCaro** [comment]
You can do the trick with vue router (v4), with a `User.vue` like this:
```vue

<template>User 👤 {{ id }}</template>

<script>
import { useMeta } from "vue-meta";

export default {
  name: "User",
  props: ["id"],
  setup(props) {
    useMeta({
      title: `usr ${props.id}`,
    });
  },
};
</script>

```

And your `router.js` must have the attribute `props: true`:
```js
import User from "@/components/User";
import { createRouter, createWebHistory } from "vue-router";

const routes = [
  { path: "user/:id", component: User, props: true },
  // other routes ...
];

export default createRouter({
  routes,
  history: createWebHistory()
});

```
So, if you go to `/user/23`, `vue-router` is going to pass `23` as a prop called `id` to `User.vue`, the same as `<User :id="23" />`.

And don't forget to put in your parent component:
```vue

<metainfo>
  <template v-slot:title="{ content }">{{ content }} - Yay!</template>
</metainfo>
```

# Live Example (vue 3, vue-meta 3, vue-router 4)

⚠️ To se the tabs click on Browser -> Open in new window (the last button)

![image](https://user-images.githubusercontent.com/41640423/126874944-37a89ba5-1bc3-4fdc-83e4-12f54df0c317.png)


[![Edit headless-flower-rte8v](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-flower-rte8v?fontsize=14&hidenavigation=1&theme=dark)
