### ISSUE TITLE
vue-meta.min.js setOptions invalid

### ISSUE THREAD

**Issue by lzxb** [nuxt/vue-meta#705]
```vue
<script>
export default {
          name: "entry-wrap-meta-info",
          mounted: function() {
              var meta = this.$meta();
              meta.setOptions({
                // invalid
                //   refreshOnceOnNavigation: true
                // effective
                  I: true
              })
          },
          render: function(t) {
              return t(e)
          }
      }
</script>
```
## vue-meta.min.js
invalid
![image](https://user-images.githubusercontent.com/8424643/125558284-51cfe988-3a55-476f-bd95-8046d739b0a4.png)

## vue-meta.js
effective
![image](https://user-images.githubusercontent.com/8424643/125558305-22deeab3-e83f-4e31-b31c-ce974d585a9a.png)

**Comment by lzxb** [comment]
Full named parameter passing is not supported in the minimum package

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/125559117-52fac2b5-79ca-4e7c-89ba-edd26cb40a1c.png)

**Comment by pimlie** [comment]
Thanks, this looks like a bug though. See the docs, ` refreshOnceOnNavigation` is marked as a runtime options so it should have been possible to change this...
