### ISSUE TITLE
[Version 3.0.0-alpha.9] Duplicate Meta tags created when present on dom before Vue App init

### ISSUE THREAD

**Issue by jgrauel** [nuxt/vue-meta#713]
When not leveraging SSR, if a meta tag present on the Dom before the Vue App is create. When MetaInfo is first set, meta data does not update the existing tags, but creates duplicates.

I would expect the existing tags to be updated with the newer information.

**Comment by jlabresh1** [comment]
Were there any updates on this? We are also experiencing this.

**Comment by jagoncalves14** [comment]
I noticed the same thing is happening.
