### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by 719media** [nuxt/vue-meta#740]
Hi,
I'm just wondering if there is any public information about the status of this project? I've been using this alpha version in some production facing sites for the past few months, and seems like development has died on this project. Is there plans to resurrect this project, or is there another recommended alternative?
Thank you for your time in creating a useful tool!

**Comment by keevitaja** [comment]
anyone knows if there is a reliable alternative we could use with vue 3? using alpha software can be painful. 

i do hope this project is not abandoned. thank you for your effort!

**Comment by P4sca1** [comment]
vueuse/head might be worth to check out: https://github.com/vueuse/head#api
