### ISSUE TITLE
Vue meta when setting meta, you can view the set meta through F12. However, you can't see the added meta by right clicking the web page source code. Excuse me, how can I view meta through right clicking

### ISSUE THREAD

**Issue by PTJ12** [nuxt/vue-meta#772]
Vue meta when setting meta, you can view the set meta through F12. However, you can't see the added meta by right clicking the web page source code. Excuse me, how can I view meta through right clicking.
This is the meta from F12.
![image](https://user-images.githubusercontent.com/67055263/178432975-f5adbb5e-9525-493b-a939-d3c73395ebd0.png)

**Comment by PTJ12** [comment]
I want to look at meta in the source code by right-click

**Comment by nexorianus** [comment]
you can not. (if not Server-side-rendering)
Because whenever you are viewing the "Website Source Code" (e.g. rightclicking and "show source code") you get the bare content of your index.html - without any content or changes in the Content/HEAD/what ever.
