### ISSUE TITLE
vue-meta for AMP

### ISSUE THREAD

**Issue by hvalcourtSerdy** [nuxt/vue-meta#99]
Hi,

only a suggestion,

I use vue-meta to manage meta, but also to respect AMP requierement (Google Accelerated Mobile Page).

They have some required mark-up, always the same
https://www.ampproject.org/docs/tutorials/create/basic_markup

Maybe it's possible to add an AMP option to respect some of the requierement.

Like :
_"Contain a <script async src="https://cdn.ampproject.org/v0.js"></script> tag as the second child of their <head> tag (this includes and loads the AMP JS library)."_

An AMP option could force AMP cdn.ampproject.org to be the second child after the head
 (scripts can be declare in more then one component, it could be difficult to put the script at the second child if we have many scripts in many components).

Or if no AMP option, maybe give us a way to order the scripts ?

Thanks for the good work

**Comment by hvalcourtSerdy** [comment]
I will write this in the same ticket because it's another problem I have with AMP.

Exemple of the noscript needed by Google AMP :
```
<noscript **data-vue-meta="true"**>
    <style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style>
</noscript>
```
Google requierement dont accept the data-vue-meta="true"
https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md

Is it possible to have an option to remove the data-vue-meta attribute ?

Thanks again

**Comment by zengxiaoluan** [comment]
在 vue 框架中使用 AMP 是一个好的选择吗？

**Comment by manniL** [comment]
Stale. Please ping/answer here if the issue persists.
